
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2021-01-27T17:52:52-0700",
 "dirty": false,
 "error": null,
 "full-revisionid": "8d4a2eee4ffd9a947bbbc2d1e85fa28a6cf53d9c",
 "version": "0.1.4"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
