
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2021-02-02T16:31:48-0500",
 "dirty": false,
 "error": null,
 "full-revisionid": "77c18343810384f7d87beccf82a218a54091cbd0",
 "version": "2021.2.2"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
