# Generated by Django 2.2.4 on 2019-08-22 22:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('capacity', '0002_auto_20190517_1736'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='resources',
            name='id_old',
        ),
    ]
