# Generated by Django 2.2.16 on 2021-01-11 08:43

from django.db import migrations
import trionyx.models


class Migration(migrations.Migration):

    dependencies = [
        ('trionyx_invoices', '0003_invoicepage'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='payments_received',
            field=trionyx.models.PriceField(blank=True, decimal_places=4, default=0.0, max_digits=11, verbose_name='Payments received'),
        ),
    ]
