# Generated by Django 2.2 on 2019-04-25 19:15

from django.db import migrations
import django.db.models.deletion
import isc_common.fields.related


class Migration(migrations.Migration):

    dependencies = [
        ('ckk', '0039_auto_20190425_1146'),
        ('production', '0006_auto_20190425_1840'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='operation_plan_template_locations',
            options={'verbose_name': 'Место положение для для шаблонов заданий в производство'},
        ),
        migrations.AddField(
            model_name='operation_plan_template_locations',
            name='item_line',
            field=isc_common.fields.related.ForeignKeyProtect(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='ckk.Item', verbose_name='Товарная позиция спецификации'),
        ),
    ]
