# Generated by Django 2.2.1 on 2019-05-29 13:41

from django.db import migrations
import django.db.models.deletion
import isc_common.fields.related


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0039_auto_20190529_1341'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resource',
            name='category',
            field=isc_common.fields.related.ForeignKeyProtect(on_delete=django.db.models.deletion.PROTECT, to='production.Resource_categories'),
        ),
        migrations.AlterField(
            model_name='resource',
            name='location',
            field=isc_common.fields.related.ForeignKeyProtect(on_delete=django.db.models.deletion.PROTECT, to='ckk.Locations'),
        ),
    ]
