# Generated by Django 2.2.1 on 2019-05-30 13:47

from django.db import migrations
import django.db.models.deletion
import isc_common.fields.related


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0044_auto_20190530_1207'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='operations',
            name='parent',
        ),
        migrations.AlterField(
            model_name='operations',
            name='category',
            field=isc_common.fields.related.ForeignKeyProtect(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='production.Operation_categories'),
        ),
        migrations.AlterField(
            model_name='operations',
            name='type',
            field=isc_common.fields.related.ForeignKeyProtect(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='production.Operations_type'),
        ),
    ]
