# Generated by Django 2.2.7 on 2019-11-19 14:18

import bitfield.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0120_launch_item_line_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='launch_operation_resources',
            name='props',
            field=bitfield.models.BitField((('enabled', 'Доступность в данной производственной спецификации'), ('added', 'Добавлено в данную производственную спецификацию'), ('edited', 'Изменено в данной производственной спецификации'), ('deleted', 'Удалено из данной производственной спецификации')), db_index=True, default=1),
        ),
        migrations.AlterField(
            model_name='launch_operations_item',
            name='props',
            field=bitfield.models.BitField((('enabled', 'Доступность в данной производственной спецификации'), ('added', 'Добавлено в данную производственную спецификацию'), ('edited', 'Изменено в данной производственной спецификации'), ('refreshed', 'Просмотрено при переформировании')), db_index=True, default=1),
        ),
        migrations.AlterField(
            model_name='launch_operations_material',
            name='props',
            field=bitfield.models.BitField((('enabled', 'Доступность в данной производственной спецификации'), ('added', 'Добавлено в данную производственную спецификацию'), ('edited', 'Изменено в данной производственной спецификации'), ('deleted', 'Удалено из данной производственной спецификации')), db_index=True, default=1),
        ),
    ]
