# Generated by Django 2.2.8 on 2019-12-06 11:51

from django.db import migrations
import django.db.models.deletion
import isc_common.fields.related


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0149_auto_20191204_2017'),
    ]

    operations = [
        migrations.AlterField(
            model_name='launch_operations_item',
            name='ed_izm',
            field=isc_common.fields.related.ForeignKeyProtect(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='ckk.Ed_izm'),
        ),
    ]
