# Generated by Django 3.0.3 on 2020-02-08 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0171_auto_20200208_1427'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='launch_operations_item',
            unique_together=set(),
        ),
        migrations.AddConstraint(
            model_name='launch_operations_item',
            constraint=models.UniqueConstraint(condition=models.Q(num=None), fields=('item', 'launch'), name='Launch_operations_item_unique_constraint_0'),
        ),
        migrations.AddConstraint(
            model_name='launch_operations_item',
            constraint=models.UniqueConstraint(fields=('item', 'launch', 'num'), name='Launch_operations_item_unique_constraint_1'),
        ),
    ]
