# Generated by Django 3.0.3 on 2020-02-16 20:08

from django.db import migrations
import django.db.models.deletion
import isc_common.fields.related


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0184_ready_2_launch_detail_mat_view_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ready_2_launch_detail',
            name='item_refs',
        ),
        migrations.AlterField(
            model_name='ready_2_launch_detail',
            name='ready',
            field=isc_common.fields.related.ForeignKeyProtect(on_delete=django.db.models.deletion.PROTECT, to='production.Ready_2_launch'),
        ),
    ]
