# Generated by Django 3.0.3 on 2020-02-23 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0206_auto_20200223_1549'),
    ]

    operations = [
        migrations.AlterField(
            model_name='launch_item_refs',
            name='qty',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
