# Generated by Django 3.0.7 on 2020-06-06 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0231_auto_20200305_1733'),
    ]

    operations = [
        migrations.AlterField(
            model_name='launch_item_refs',
            name='item_full_name',
            field=models.TextField(db_index=True),
        ),
        migrations.AlterField(
            model_name='launch_item_refs',
            name='qty',
            field=models.FloatField(db_index=True),
        ),
        migrations.AlterField(
            model_name='launch_item_refs',
            name='qty_per_one',
            field=models.FloatField(db_index=True),
        ),
        migrations.AlterField(
            model_name='launches',
            name='date',
            field=models.DateTimeField(db_index=True),
        ),
        migrations.AlterField(
            model_name='launches',
            name='qty',
            field=models.PositiveIntegerField(db_index=True),
        ),
    ]
