# Generated by Django 3.0.7 on 2020-06-16 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0235_auto_20200615_0311'),
    ]

    operations = [
        migrations.AddField(
            model_name='launches',
            name='priority',
            field=models.PositiveIntegerField(db_index=True, default=0),
        ),
    ]
