# Generated by Django 3.0.7 on 2020-06-16 15:48

from django.contrib.postgres.fields import ArrayField
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0237_auto_20200616_1548'),
    ]
    #django.db.models.ArrayField

    operations = [
        migrations.AlterField(
            model_name='launches',
            name='load_part',
            field=ArrayField(base_field=models.PositiveIntegerField(), default=list, size=None),
        ),
    ]
