# Generated by Django 3.0.7 on 2020-06-17 07:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0240_auto_20200617_0546'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='launch_operation_resources',
            name='Launch_operation_resources_unique_constraint_2',
        ),
        migrations.RemoveConstraint(
            model_name='launch_operation_resources',
            name='Launch_operation_resources_unique_constraint_3',
        ),
        migrations.RemoveField(
            model_name='launch_operation_resources',
            name='location',
        ),
    ]
