# Generated by Django 3.0.7 on 2020-06-19 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0244_auto_20200619_0927'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='launch_item_refs',
            name='Launch_item_refs_unique_constraint_0',
        ),
        migrations.RemoveConstraint(
            model_name='launch_item_refs',
            name='Launch_item_refs_unique_constraint_1',
        ),
        migrations.AddConstraint(
            model_name='launch_item_refs',
            constraint=models.UniqueConstraint(condition=models.Q(parent_id=None), fields=('child_id', 'launch_id', 'props', 'qty', 'qty_per_one'), name='Launch_item_refs_unique_constraint_0'),
        ),
        migrations.AddConstraint(
            model_name='launch_item_refs',
            constraint=models.UniqueConstraint(fields=('child_id', 'launch_id', 'parent_id', 'props', 'qty', 'qty_per_one'), name='Launch_item_refs_unique_constraint_1'),
        ),
    ]
