# Generated by Django 3.0.8 on 2020-07-12 09:14

from django.db import migrations
import django.db.models.deletion
import isc_common.fields.related


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0278_auto_20200712_0614'),
    ]

    operations = [
        migrations.AlterField(
            model_name='launch_operation_resources',
            name='operation_resources',
            field=isc_common.fields.related.ForeignKeyProtect(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='production.Operation_resources'),
        ),
        migrations.AlterField(
            model_name='launch_operations_material',
            name='operation_material',
            field=isc_common.fields.related.ForeignKeyProtect(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='production.Operation_material'),
        ),
    ]
