# Generated by Django 3.0.8 on 2020-07-14 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0279_auto_20200712_0914'),
    ]

    operations = [
        migrations.AddField(
            model_name='launch_operations_item',
            name='old_num',
            field=models.PositiveIntegerField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='operations_item',
            name='old_num',
            field=models.PositiveIntegerField(blank=True, db_index=True, null=True),
        ),
    ]
