# Generated by Django 3.0.8 on 2020-07-14 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0280_auto_20200714_1009'),
    ]

    operations = [
        migrations.AddField(
            model_name='launch_operations_item',
            name='new_num',
            field=models.PositiveIntegerField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='operations_item',
            name='new_num',
            field=models.PositiveIntegerField(blank=True, default=None, null=True),
        ),
    ]
