# Generated by Django 3.0.8 on 2020-07-19 12:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ckk', '0238_item_refs_history'),
        ('production', '0283_auto_20200716_1618'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='operations_item',
            unique_together={('item', 'operation', 'props')},
        ),
    ]
