# Generated by Django 3.0.8 on 2020-07-20 20:03

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('production', '0287_auto_20200720_1956'),
    ]

    operations = [
        migrations.AlterField(
            model_name='launch_operations_item',
            name='num',
            field=models.PositiveIntegerField(db_index=True),
        ),
    ]
