# Generated by Django 3.1 on 2020-08-04 12:12

from django.db import migrations
import django.db.models.deletion
import isc_common.fields.related


class Migration(migrations.Migration):

    dependencies = [
        ('ckk', '0247_auto_20200803_1529'),
        ('production', '0299_auto_20200801_0822'),
    ]

    operations = [
        migrations.AlterField(
            model_name='launch_operations_item',
            name='operationitem',
            field=isc_common.fields.related.ForeignKeySetNull(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='production.operations_item'),
        ),
        migrations.AlterUniqueTogether(
            name='launch_operations_item',
            unique_together={('item', 'launch', 'operation', 'num')},
        ),
    ]
