# Generated by Django 3.1 on 2020-08-16 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0314_auto_20200816_1837'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='launch_operations_item',
            name='Launch_operations_item_unique_constraint_0',
        ),
        migrations.RemoveConstraint(
            model_name='launch_operations_item',
            name='Launch_operations_item_unique_constraint_1',
        ),
        migrations.AddConstraint(
            model_name='launch_operations_item',
            constraint=models.UniqueConstraint(condition=models.Q(('color', None), ('operationitem', None)), fields=('item', 'launch', 'operation'), name='Launch_operations_item_unique_constraint_0'),
        ),
        migrations.AddConstraint(
            model_name='launch_operations_item',
            constraint=models.UniqueConstraint(condition=models.Q(operationitem=None), fields=('color', 'item', 'launch', 'operation'), name='Launch_operations_item_unique_constraint_1'),
        ),
        migrations.AddConstraint(
            model_name='launch_operations_item',
            constraint=models.UniqueConstraint(condition=models.Q(color=None), fields=('item', 'launch', 'operation', 'operationitem'), name='Launch_operations_item_unique_constraint_2'),
        ),
        migrations.AddConstraint(
            model_name='launch_operations_item',
            constraint=models.UniqueConstraint(fields=('color', 'item', 'launch', 'operation', 'operationitem'), name='Launch_operations_item_unique_constraint_3'),
        ),
    ]
