# Generated by Django 3.1.4 on 2020-12-15 16:02

from django.db import migrations
import django.db.models.deletion
import isc_common.fields.related


class Migration(migrations.Migration):

    dependencies = [
        ('ckk', '0270_auto_20201113_0846'),
        ('production', '0322_auto_20201204_0703'),
    ]

    operations = [
        migrations.AlterField(
            model_name='launch_item_line',
            name='item_line',
            field=isc_common.fields.related.ForeignKeySetNull(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='ckk.item_line'),
        ),
        migrations.AlterField(
            model_name='launch_item_refs',
            name='item_refs',
            field=isc_common.fields.related.ForeignKeySetNull(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='ckk.item_refs'),
        ),
    ]
