# coding: utf-8

"""
    Antenny API

    This is an api that allows you to interact with the Antenny platform. It allows you to manage your clients and subscriptions.  # noqa: E501

    The version of the OpenAPI document: 1.0.0
    Contact: admin@antenny.io
    Generated by: https://openapi-generator.tech
"""


import pprint
import re  # noqa: F401

import six

from antenny.configuration import Configuration


class Registration(object):
    """NOTE: This class is auto generated by OpenAPI Generator.
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """

    """
    Attributes:
      openapi_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    openapi_types = {
        'id': 'str',
        'customer_id': 'str',
        'secret': 'str',
        'status': 'str',
        'clients': 'list[str]',
        'subscriptions': 'list[str]',
        'created': 'date',
        'modified': 'date'
    }

    attribute_map = {
        'id': 'id',
        'customer_id': 'customerId',
        'secret': 'secret',
        'status': 'status',
        'clients': 'clients',
        'subscriptions': 'subscriptions',
        'created': 'created',
        'modified': 'modified'
    }

    def __init__(self, id=None, customer_id=None, secret=None, status=None, clients=None, subscriptions=None, created=None, modified=None, local_vars_configuration=None):  # noqa: E501
        """Registration - a model defined in OpenAPI"""  # noqa: E501
        if local_vars_configuration is None:
            local_vars_configuration = Configuration()
        self.local_vars_configuration = local_vars_configuration

        self._id = None
        self._customer_id = None
        self._secret = None
        self._status = None
        self._clients = None
        self._subscriptions = None
        self._created = None
        self._modified = None
        self.discriminator = None

        if id is not None:
            self.id = id
        if customer_id is not None:
            self.customer_id = customer_id
        if secret is not None:
            self.secret = secret
        if status is not None:
            self.status = status
        if clients is not None:
            self.clients = clients
        if subscriptions is not None:
            self.subscriptions = subscriptions
        if created is not None:
            self.created = created
        if modified is not None:
            self.modified = modified

    @property
    def id(self):
        """Gets the id of this Registration.  # noqa: E501


        :return: The id of this Registration.  # noqa: E501
        :rtype: str
        """
        return self._id

    @id.setter
    def id(self, id):
        """Sets the id of this Registration.


        :param id: The id of this Registration.  # noqa: E501
        :type id: str
        """

        self._id = id

    @property
    def customer_id(self):
        """Gets the customer_id of this Registration.  # noqa: E501


        :return: The customer_id of this Registration.  # noqa: E501
        :rtype: str
        """
        return self._customer_id

    @customer_id.setter
    def customer_id(self, customer_id):
        """Sets the customer_id of this Registration.


        :param customer_id: The customer_id of this Registration.  # noqa: E501
        :type customer_id: str
        """

        self._customer_id = customer_id

    @property
    def secret(self):
        """Gets the secret of this Registration.  # noqa: E501


        :return: The secret of this Registration.  # noqa: E501
        :rtype: str
        """
        return self._secret

    @secret.setter
    def secret(self, secret):
        """Sets the secret of this Registration.


        :param secret: The secret of this Registration.  # noqa: E501
        :type secret: str
        """

        self._secret = secret

    @property
    def status(self):
        """Gets the status of this Registration.  # noqa: E501


        :return: The status of this Registration.  # noqa: E501
        :rtype: str
        """
        return self._status

    @status.setter
    def status(self, status):
        """Sets the status of this Registration.


        :param status: The status of this Registration.  # noqa: E501
        :type status: str
        """

        self._status = status

    @property
    def clients(self):
        """Gets the clients of this Registration.  # noqa: E501


        :return: The clients of this Registration.  # noqa: E501
        :rtype: list[str]
        """
        return self._clients

    @clients.setter
    def clients(self, clients):
        """Sets the clients of this Registration.


        :param clients: The clients of this Registration.  # noqa: E501
        :type clients: list[str]
        """

        self._clients = clients

    @property
    def subscriptions(self):
        """Gets the subscriptions of this Registration.  # noqa: E501


        :return: The subscriptions of this Registration.  # noqa: E501
        :rtype: list[str]
        """
        return self._subscriptions

    @subscriptions.setter
    def subscriptions(self, subscriptions):
        """Sets the subscriptions of this Registration.


        :param subscriptions: The subscriptions of this Registration.  # noqa: E501
        :type subscriptions: list[str]
        """

        self._subscriptions = subscriptions

    @property
    def created(self):
        """Gets the created of this Registration.  # noqa: E501


        :return: The created of this Registration.  # noqa: E501
        :rtype: date
        """
        return self._created

    @created.setter
    def created(self, created):
        """Sets the created of this Registration.


        :param created: The created of this Registration.  # noqa: E501
        :type created: date
        """

        self._created = created

    @property
    def modified(self):
        """Gets the modified of this Registration.  # noqa: E501


        :return: The modified of this Registration.  # noqa: E501
        :rtype: date
        """
        return self._modified

    @modified.setter
    def modified(self, modified):
        """Sets the modified of this Registration.


        :param modified: The modified of this Registration.  # noqa: E501
        :type modified: date
        """

        self._modified = modified

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.openapi_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, Registration):
            return False

        return self.to_dict() == other.to_dict()

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        if not isinstance(other, Registration):
            return True

        return self.to_dict() != other.to_dict()
