# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'dlgModel.ui'
#
# Created: Fri Jun 14 13:40:14 2013
#      by: PyQt4 UI code generator 4.9.5
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    _fromUtf8 = lambda s: s

class Ui_dlgModel(object):
    def setupUi(self, dlgModel):
        dlgModel.setObjectName(_fromUtf8("dlgModel"))
        dlgModel.setWindowModality(QtCore.Qt.NonModal)
        dlgModel.resize(589, 341)
        self.verticalLayout = QtGui.QVBoxLayout(dlgModel)
        self.verticalLayout.setSizeConstraint(QtGui.QLayout.SetFixedSize)
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.groupBox_2 = QtGui.QGroupBox(dlgModel)
        self.groupBox_2.setObjectName(_fromUtf8("groupBox_2"))
        self.verticalLayout_4 = QtGui.QVBoxLayout(self.groupBox_2)
        self.verticalLayout_4.setObjectName(_fromUtf8("verticalLayout_4"))
        self.labelDatas = QtGui.QLabel(self.groupBox_2)
        font = QtGui.QFont()
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.labelDatas.setFont(font)
        self.labelDatas.setObjectName(_fromUtf8("labelDatas"))
        self.verticalLayout_4.addWidget(self.labelDatas)
        self.verticalLayout.addWidget(self.groupBox_2)
        self.groupBox = QtGui.QGroupBox(dlgModel)
        self.groupBox.setMinimumSize(QtCore.QSize(0, 70))
        self.groupBox.setMaximumSize(QtCore.QSize(571, 95))
        self.groupBox.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.groupBox.setObjectName(_fromUtf8("groupBox"))
        self.formLayout = QtGui.QFormLayout(self.groupBox)
        self.formLayout.setObjectName(_fromUtf8("formLayout"))
        self.label_3 = QtGui.QLabel(self.groupBox)
        self.label_3.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.formLayout.setWidget(0, QtGui.QFormLayout.LabelRole, self.label_3)
        self.labelDescription = QtGui.QLabel(self.groupBox)
        self.labelDescription.setEnabled(False)
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(170, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Mid, brush)
        brush = QtGui.QBrush(QtGui.QColor(170, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(170, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Mid, brush)
        brush = QtGui.QBrush(QtGui.QColor(170, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(170, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Mid, brush)
        brush = QtGui.QBrush(QtGui.QColor(120, 120, 120))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Text, brush)
        self.labelDescription.setPalette(palette)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        font.setKerning(False)
        self.labelDescription.setFont(font)
        self.labelDescription.setObjectName(_fromUtf8("labelDescription"))
        self.formLayout.setWidget(0, QtGui.QFormLayout.FieldRole, self.labelDescription)
        self.label_5 = QtGui.QLabel(self.groupBox)
        self.label_5.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_5.setObjectName(_fromUtf8("label_5"))
        self.formLayout.setWidget(1, QtGui.QFormLayout.LabelRole, self.label_5)
        self.labelAuthor = QtGui.QLabel(self.groupBox)
        self.labelAuthor.setEnabled(False)
        self.labelAuthor.setObjectName(_fromUtf8("labelAuthor"))
        self.formLayout.setWidget(1, QtGui.QFormLayout.FieldRole, self.labelAuthor)
        self.verticalLayout.addWidget(self.groupBox)
        self.gbParameters = QtGui.QGroupBox(dlgModel)
        self.gbParameters.setObjectName(_fromUtf8("gbParameters"))
        self.verticalLayout_3 = QtGui.QVBoxLayout(self.gbParameters)
        self.verticalLayout_3.setObjectName(_fromUtf8("verticalLayout_3"))
        self.gridParameters = QtGui.QGridLayout()
        self.gridParameters.setObjectName(_fromUtf8("gridParameters"))
        self.label_6 = QtGui.QLabel(self.gbParameters)
        self.label_6.setObjectName(_fromUtf8("label_6"))
        self.gridParameters.addWidget(self.label_6, 0, 1, 1, 1)
        self.label_7 = QtGui.QLabel(self.gbParameters)
        self.label_7.setObjectName(_fromUtf8("label_7"))
        self.gridParameters.addWidget(self.label_7, 0, 2, 1, 1)
        self.label_8 = QtGui.QLabel(self.gbParameters)
        self.label_8.setObjectName(_fromUtf8("label_8"))
        self.gridParameters.addWidget(self.label_8, 0, 3, 1, 1)
        self.label_9 = QtGui.QLabel(self.gbParameters)
        self.label_9.setObjectName(_fromUtf8("label_9"))
        self.gridParameters.addWidget(self.label_9, 0, 4, 1, 1)
        self.label_4 = QtGui.QLabel(self.gbParameters)
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.gridParameters.addWidget(self.label_4, 0, 0, 1, 1)
        self.verticalLayout_3.addLayout(self.gridParameters)
        self.updateFit = QtGui.QCheckBox(self.gbParameters)
        self.updateFit.setChecked(True)
        self.updateFit.setObjectName(_fromUtf8("updateFit"))
        self.verticalLayout_3.addWidget(self.updateFit)
        self.verticalLayout.addWidget(self.gbParameters)
        self.groupBox_3 = QtGui.QGroupBox(dlgModel)
        self.groupBox_3.setObjectName(_fromUtf8("groupBox_3"))
        self.gridLayout = QtGui.QGridLayout(self.groupBox_3)
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.gridLayout_3 = QtGui.QGridLayout()
        self.gridLayout_3.setObjectName(_fromUtf8("gridLayout_3"))
        self.label = QtGui.QLabel(self.groupBox_3)
        self.label.setObjectName(_fromUtf8("label"))
        self.gridLayout_3.addWidget(self.label, 0, 0, 1, 1)
        self.sliderQmax = QtGui.QSlider(self.groupBox_3)
        self.sliderQmax.setOrientation(QtCore.Qt.Horizontal)
        self.sliderQmax.setObjectName(_fromUtf8("sliderQmax"))
        self.gridLayout_3.addWidget(self.sliderQmax, 1, 1, 1, 1)
        self.label_2 = QtGui.QLabel(self.groupBox_3)
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.gridLayout_3.addWidget(self.label_2, 1, 0, 1, 1)
        self.sliderQmin = QtGui.QSlider(self.groupBox_3)
        self.sliderQmin.setOrientation(QtCore.Qt.Horizontal)
        self.sliderQmin.setObjectName(_fromUtf8("sliderQmin"))
        self.gridLayout_3.addWidget(self.sliderQmin, 0, 1, 1, 1)
        self.editQmin = QtGui.QLineEdit(self.groupBox_3)
        self.editQmin.setEnabled(False)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.editQmin.sizePolicy().hasHeightForWidth())
        self.editQmin.setSizePolicy(sizePolicy)
        self.editQmin.setMinimumSize(QtCore.QSize(50, 0))
        self.editQmin.setObjectName(_fromUtf8("editQmin"))
        self.gridLayout_3.addWidget(self.editQmin, 0, 2, 1, 1)
        self.editQmax = QtGui.QLineEdit(self.groupBox_3)
        self.editQmax.setEnabled(False)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.editQmax.sizePolicy().hasHeightForWidth())
        self.editQmax.setSizePolicy(sizePolicy)
        self.editQmax.setMinimumSize(QtCore.QSize(50, 0))
        self.editQmax.setObjectName(_fromUtf8("editQmax"))
        self.gridLayout_3.addWidget(self.editQmax, 1, 2, 1, 1)
        self.gridLayout.addLayout(self.gridLayout_3, 0, 1, 1, 1)
        self.verticalLayout.addWidget(self.groupBox_3)
        self.groupPlotExp = QtGui.QGroupBox(dlgModel)
        self.groupPlotExp.setObjectName(_fromUtf8("groupPlotExp"))
        self.verticalLayout_2 = QtGui.QVBoxLayout(self.groupPlotExp)
        self.verticalLayout_2.setObjectName(_fromUtf8("verticalLayout_2"))
        self.gridLayoutPlotExp = QtGui.QGridLayout()
        self.gridLayoutPlotExp.setObjectName(_fromUtf8("gridLayoutPlotExp"))
        self.verticalLayout_2.addLayout(self.gridLayoutPlotExp)
        self.verticalLayout.addWidget(self.groupPlotExp)
        self.gridLayout_4 = QtGui.QGridLayout()
        self.gridLayout_4.setObjectName(_fromUtf8("gridLayout_4"))
        self.btnFit = QtGui.QPushButton(dlgModel)
        self.btnFit.setFlat(False)
        self.btnFit.setObjectName(_fromUtf8("btnFit"))
        self.gridLayout_4.addWidget(self.btnFit, 0, 4, 1, 1)
        self.btnFitBounds = QtGui.QPushButton(dlgModel)
        self.btnFitBounds.setObjectName(_fromUtf8("btnFitBounds"))
        self.gridLayout_4.addWidget(self.btnFitBounds, 0, 5, 1, 1)
        self.btnReport = QtGui.QPushButton(dlgModel)
        self.btnReport.setObjectName(_fromUtf8("btnReport"))
        self.gridLayout_4.addWidget(self.btnReport, 0, 3, 1, 1)
        self.btnPaste = QtGui.QPushButton(dlgModel)
        self.btnPaste.setObjectName(_fromUtf8("btnPaste"))
        self.gridLayout_4.addWidget(self.btnPaste, 0, 2, 1, 1)
        self.btnCopy = QtGui.QPushButton(dlgModel)
        self.btnCopy.setObjectName(_fromUtf8("btnCopy"))
        self.gridLayout_4.addWidget(self.btnCopy, 0, 1, 1, 1)
        self.buttonBox = QtGui.QDialogButtonBox(dlgModel)
        self.buttonBox.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtGui.QDialogButtonBox.Ok)
        self.buttonBox.setCenterButtons(False)
        self.buttonBox.setObjectName(_fromUtf8("buttonBox"))
        self.gridLayout_4.addWidget(self.buttonBox, 0, 6, 1, 1)
        self.verticalLayout.addLayout(self.gridLayout_4)

        self.retranslateUi(dlgModel)
        QtCore.QObject.connect(self.buttonBox, QtCore.SIGNAL(_fromUtf8("accepted()")), dlgModel.accept)
        QtCore.QObject.connect(self.buttonBox, QtCore.SIGNAL(_fromUtf8("rejected()")), dlgModel.reject)
        QtCore.QMetaObject.connectSlotsByName(dlgModel)

    def retranslateUi(self, dlgModel):
        dlgModel.setWindowTitle(QtGui.QApplication.translate("dlgModel", "Dialog", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox_2.setTitle(QtGui.QApplication.translate("dlgModel", "Datas :", None, QtGui.QApplication.UnicodeUTF8))
        self.labelDatas.setText(QtGui.QApplication.translate("dlgModel", "TextLabel", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox.setTitle(QtGui.QApplication.translate("dlgModel", "Model :", None, QtGui.QApplication.UnicodeUTF8))
        self.label_3.setText(QtGui.QApplication.translate("dlgModel", "Description :", None, QtGui.QApplication.UnicodeUTF8))
        self.labelDescription.setText(QtGui.QApplication.translate("dlgModel", "TextLabel", None, QtGui.QApplication.UnicodeUTF8))
        self.label_5.setText(QtGui.QApplication.translate("dlgModel", "Author :", None, QtGui.QApplication.UnicodeUTF8))
        self.labelAuthor.setText(QtGui.QApplication.translate("dlgModel", "TextLabel", None, QtGui.QApplication.UnicodeUTF8))
        self.gbParameters.setTitle(QtGui.QApplication.translate("dlgModel", "Parameters :", None, QtGui.QApplication.UnicodeUTF8))
        self.label_6.setText(QtGui.QApplication.translate("dlgModel", "Value", None, QtGui.QApplication.UnicodeUTF8))
        self.label_7.setText(QtGui.QApplication.translate("dlgModel", "Fit ?", None, QtGui.QApplication.UnicodeUTF8))
        self.label_8.setText(QtGui.QApplication.translate("dlgModel", "Min", None, QtGui.QApplication.UnicodeUTF8))
        self.label_9.setText(QtGui.QApplication.translate("dlgModel", "Max", None, QtGui.QApplication.UnicodeUTF8))
        self.label_4.setText(QtGui.QApplication.translate("dlgModel", "Parameter", None, QtGui.QApplication.UnicodeUTF8))
        self.updateFit.setText(QtGui.QApplication.translate("dlgModel", "Update values when parameters changes", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox_3.setTitle(QtGui.QApplication.translate("dlgModel", "Q range :", None, QtGui.QApplication.UnicodeUTF8))
        self.label.setText(QtGui.QApplication.translate("dlgModel", "qmin :", None, QtGui.QApplication.UnicodeUTF8))
        self.label_2.setText(QtGui.QApplication.translate("dlgModel", "qmax :", None, QtGui.QApplication.UnicodeUTF8))
        self.groupPlotExp.setTitle(QtGui.QApplication.translate("dlgModel", "X type :", None, QtGui.QApplication.UnicodeUTF8))
        self.btnFit.setText(QtGui.QApplication.translate("dlgModel", "Fit", None, QtGui.QApplication.UnicodeUTF8))
        self.btnFitBounds.setText(QtGui.QApplication.translate("dlgModel", "Fit with bounds", None, QtGui.QApplication.UnicodeUTF8))
        self.btnReport.setText(QtGui.QApplication.translate("dlgModel", "Report", None, QtGui.QApplication.UnicodeUTF8))
        self.btnPaste.setText(QtGui.QApplication.translate("dlgModel", "Paste", None, QtGui.QApplication.UnicodeUTF8))
        self.btnCopy.setText(QtGui.QApplication.translate("dlgModel", "Copy", None, QtGui.QApplication.UnicodeUTF8))

