# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'QtMatplotlib.ui'
#
# Created: Tue Mar 12 16:39:05 2013
#      by: PyQt4 UI code generator 4.9.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    _fromUtf8 = lambda s: s

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName(_fromUtf8("MainWindow"))
        MainWindow.resize(704, 565)
        self.centralwidget = QtGui.QWidget(MainWindow)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.centralwidget.sizePolicy().hasHeightForWidth())
        self.centralwidget.setSizePolicy(sizePolicy)
        self.centralwidget.setObjectName(_fromUtf8("centralwidget"))
        self.gridLayout_2 = QtGui.QGridLayout(self.centralwidget)
        self.gridLayout_2.setObjectName(_fromUtf8("gridLayout_2"))
        self.verticalLayout = QtGui.QVBoxLayout()
        self.verticalLayout.setSpacing(0)
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.mplwidget = MatplotlibWidget(self.centralwidget)
        self.mplwidget.setObjectName(_fromUtf8("mplwidget"))
        self.verticalLayout.addWidget(self.mplwidget)
        self.gridLayout_2.addLayout(self.verticalLayout, 0, 0, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtGui.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 704, 21))
        self.menubar.setObjectName(_fromUtf8("menubar"))
        self.menuFile = QtGui.QMenu(self.menubar)
        self.menuFile.setObjectName(_fromUtf8("menuFile"))
        self.menuPlot = QtGui.QMenu(self.menubar)
        self.menuPlot.setObjectName(_fromUtf8("menuPlot"))
        self.menuAxes = QtGui.QMenu(self.menubar)
        self.menuAxes.setObjectName(_fromUtf8("menuAxes"))
        self.menuY_X_exp = QtGui.QMenu(self.menubar)
        self.menuY_X_exp.setObjectName(_fromUtf8("menuY_X_exp"))
        self.menuScale = QtGui.QMenu(self.menubar)
        self.menuScale.setObjectName(_fromUtf8("menuScale"))
        self.menuCurves = QtGui.QMenu(self.menubar)
        self.menuCurves.setObjectName(_fromUtf8("menuCurves"))
        self.menuLines = QtGui.QMenu(self.menuCurves)
        self.menuLines.setObjectName(_fromUtf8("menuLines"))
        self.menuMarker = QtGui.QMenu(self.menuCurves)
        self.menuMarker.setObjectName(_fromUtf8("menuMarker"))
        MainWindow.setMenuBar(self.menubar)
        self.actionSave_As = QtGui.QAction(MainWindow)
        self.actionSave_As.setObjectName(_fromUtf8("actionSave_As"))
        self.actionPage_Setup = QtGui.QAction(MainWindow)
        self.actionPage_Setup.setObjectName(_fromUtf8("actionPage_Setup"))
        self.actionPrint = QtGui.QAction(MainWindow)
        self.actionPrint.setObjectName(_fromUtf8("actionPrint"))
        self.actionPrint_Preview = QtGui.QAction(MainWindow)
        self.actionPrint_Preview.setObjectName(_fromUtf8("actionPrint_Preview"))
        self.action_Close = QtGui.QAction(MainWindow)
        self.action_Close.setObjectName(_fromUtf8("action_Close"))
        self.actionGridON = QtGui.QAction(MainWindow)
        self.actionGridON.setCheckable(True)
        self.actionGridON.setChecked(True)
        self.actionGridON.setObjectName(_fromUtf8("actionGridON"))
        self.actionGridOFF = QtGui.QAction(MainWindow)
        self.actionGridOFF.setCheckable(True)
        self.actionGridOFF.setObjectName(_fromUtf8("actionGridOFF"))
        self.actionAutoscale = QtGui.QAction(MainWindow)
        self.actionAutoscale.setCheckable(True)
        self.actionAutoscale.setChecked(True)
        self.actionAutoscale.setObjectName(_fromUtf8("actionAutoscale"))
        self.actionXlin_ylin = QtGui.QAction(MainWindow)
        self.actionXlin_ylin.setCheckable(True)
        self.actionXlin_ylin.setObjectName(_fromUtf8("actionXlin_ylin"))
        self.actionXlin_ylog = QtGui.QAction(MainWindow)
        self.actionXlin_ylog.setCheckable(True)
        self.actionXlin_ylog.setObjectName(_fromUtf8("actionXlin_ylog"))
        self.actionXlog_ylin = QtGui.QAction(MainWindow)
        self.actionXlog_ylin.setCheckable(True)
        self.actionXlog_ylin.setObjectName(_fromUtf8("actionXlog_ylin"))
        self.actionXlog_ylog = QtGui.QAction(MainWindow)
        self.actionXlog_ylog.setCheckable(True)
        self.actionXlog_ylog.setObjectName(_fromUtf8("actionXlog_ylog"))
        self.actionAbout = QtGui.QAction(MainWindow)
        self.actionAbout.setEnabled(False)
        self.actionAbout.setObjectName(_fromUtf8("actionAbout"))
        self.actionLegend_ON = QtGui.QAction(MainWindow)
        self.actionLegend_ON.setCheckable(True)
        self.actionLegend_ON.setChecked(True)
        self.actionLegend_ON.setObjectName(_fromUtf8("actionLegend_ON"))
        self.actionLegend_OFF = QtGui.QAction(MainWindow)
        self.actionLegend_OFF.setCheckable(True)
        self.actionLegend_OFF.setObjectName(_fromUtf8("actionLegend_OFF"))
        self.actionTest = QtGui.QAction(MainWindow)
        self.actionTest.setObjectName(_fromUtf8("actionTest"))
        self.actionTest_2 = QtGui.QAction(MainWindow)
        self.actionTest_2.setObjectName(_fromUtf8("actionTest_2"))
        self.actionPoint = QtGui.QAction(MainWindow)
        self.actionPoint.setObjectName(_fromUtf8("actionPoint"))
        self.actionLine = QtGui.QAction(MainWindow)
        self.actionLine.setObjectName(_fromUtf8("actionLine"))
        self.actionPoint_Line = QtGui.QAction(MainWindow)
        self.actionPoint_Line.setObjectName(_fromUtf8("actionPoint_Line"))
        self.actionCircle = QtGui.QAction(MainWindow)
        self.actionCircle.setObjectName(_fromUtf8("actionCircle"))
        self.actionDiamond = QtGui.QAction(MainWindow)
        self.actionDiamond.setObjectName(_fromUtf8("actionDiamond"))
        self.actionCross = QtGui.QAction(MainWindow)
        self.actionCross.setObjectName(_fromUtf8("actionCross"))
        self.actionPixel = QtGui.QAction(MainWindow)
        self.actionPixel.setObjectName(_fromUtf8("actionPixel"))
        self.actionDash_Line = QtGui.QAction(MainWindow)
        self.actionDash_Line.setObjectName(_fromUtf8("actionDash_Line"))
        self.actionNo_Marker = QtGui.QAction(MainWindow)
        self.actionNo_Marker.setCheckable(True)
        self.actionNo_Marker.setChecked(True)
        self.actionNo_Marker.setObjectName(_fromUtf8("actionNo_Marker"))
        self.actionNo_Line = QtGui.QAction(MainWindow)
        self.actionNo_Line.setCheckable(True)
        self.actionNo_Line.setChecked(True)
        self.actionNo_Line.setObjectName(_fromUtf8("actionNo_Line"))
        self.actionLine_3 = QtGui.QAction(MainWindow)
        self.actionLine_3.setObjectName(_fromUtf8("actionLine_3"))
        self.actionDash_Line_2 = QtGui.QAction(MainWindow)
        self.actionDash_Line_2.setObjectName(_fromUtf8("actionDash_Line_2"))
        self.actionError_Bar = QtGui.QAction(MainWindow)
        self.actionError_Bar.setCheckable(True)
        self.actionError_Bar.setChecked(True)
        self.actionError_Bar.setObjectName(_fromUtf8("actionError_Bar"))
        self.actionDash_dot = QtGui.QAction(MainWindow)
        self.actionDash_dot.setObjectName(_fromUtf8("actionDash_dot"))
        self.actionDotted = QtGui.QAction(MainWindow)
        self.actionDotted.setObjectName(_fromUtf8("actionDotted"))
        self.actionTitle = QtGui.QAction(MainWindow)
        self.actionTitle.setObjectName(_fromUtf8("actionTitle"))
        self.actionSet_x_text = QtGui.QAction(MainWindow)
        self.actionSet_x_text.setObjectName(_fromUtf8("actionSet_x_text"))
        self.actionSet_Y_label = QtGui.QAction(MainWindow)
        self.actionSet_Y_label.setObjectName(_fromUtf8("actionSet_Y_label"))
        self.actionFigure_Options = QtGui.QAction(MainWindow)
        self.actionFigure_Options.setObjectName(_fromUtf8("actionFigure_Options"))
        self.actionSet_Marker_size = QtGui.QAction(MainWindow)
        self.actionSet_Marker_size.setObjectName(_fromUtf8("actionSet_Marker_size"))
        self.actionWxcwxc = QtGui.QAction(MainWindow)
        self.actionWxcwxc.setObjectName(_fromUtf8("actionWxcwxc"))
        self.actionCopy_to_cliipboard = QtGui.QAction(MainWindow)
        self.actionCopy_to_cliipboard.setObjectName(_fromUtf8("actionCopy_to_cliipboard"))
        self.actionTitle_and_axes_labels = QtGui.QAction(MainWindow)
        self.actionTitle_and_axes_labels.setObjectName(_fromUtf8("actionTitle_and_axes_labels"))
        self.actionDsd = QtGui.QAction(MainWindow)
        self.actionDsd.setObjectName(_fromUtf8("actionDsd"))
        self.actionQsd = QtGui.QAction(MainWindow)
        self.actionQsd.setObjectName(_fromUtf8("actionQsd"))
        self.actionSet_marker_size = QtGui.QAction(MainWindow)
        self.actionSet_marker_size.setObjectName(_fromUtf8("actionSet_marker_size"))
        self.actionAutoscaling = QtGui.QAction(MainWindow)
        self.actionAutoscaling.setObjectName(_fromUtf8("actionAutoscaling"))
        self.actionSet_X_range = QtGui.QAction(MainWindow)
        self.actionSet_X_range.setObjectName(_fromUtf8("actionSet_X_range"))
        self.actionSet_Y_range = QtGui.QAction(MainWindow)
        self.actionSet_Y_range.setObjectName(_fromUtf8("actionSet_Y_range"))
        self.actionFix_scale = QtGui.QAction(MainWindow)
        self.actionFix_scale.setCheckable(True)
        self.actionFix_scale.setObjectName(_fromUtf8("actionFix_scale"))
        self.actionSetTitle = QtGui.QAction(MainWindow)
        self.actionSetTitle.setObjectName(_fromUtf8("actionSetTitle"))
        self.actionX_label = QtGui.QAction(MainWindow)
        self.actionX_label.setObjectName(_fromUtf8("actionX_label"))
        self.actionY_label = QtGui.QAction(MainWindow)
        self.actionY_label.setObjectName(_fromUtf8("actionY_label"))
        self.menuFile.addAction(self.actionSave_As)
        self.menuFile.addSeparator()
        self.menuFile.addAction(self.action_Close)
        self.menuFile.addSeparator()
        self.menuPlot.addAction(self.actionGridON)
        self.menuPlot.addAction(self.actionLegend_ON)
        self.menuPlot.addSeparator()
        self.menuPlot.addAction(self.actionSetTitle)
        self.menuPlot.addAction(self.actionX_label)
        self.menuPlot.addAction(self.actionY_label)
        self.menuScale.addAction(self.actionAutoscaling)
        self.menuScale.addSeparator()
        self.menuScale.addAction(self.actionSet_X_range)
        self.menuScale.addAction(self.actionSet_Y_range)
        self.menuScale.addSeparator()
        self.menuMarker.addAction(self.actionSet_marker_size)
        self.menuMarker.addSeparator()
        self.menuCurves.addAction(self.menuLines.menuAction())
        self.menuCurves.addAction(self.menuMarker.menuAction())
        self.menuCurves.addAction(self.actionError_Bar)
        self.menubar.addAction(self.menuFile.menuAction())
        self.menubar.addAction(self.menuPlot.menuAction())
        self.menubar.addAction(self.menuAxes.menuAction())
        self.menubar.addAction(self.menuScale.menuAction())
        self.menubar.addAction(self.menuCurves.menuAction())
        self.menubar.addAction(self.menuY_X_exp.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QObject.connect(self.action_Close, QtCore.SIGNAL(_fromUtf8("triggered()")), MainWindow.close)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(QtGui.QApplication.translate("MainWindow", "MainWindow", None, QtGui.QApplication.UnicodeUTF8))
        self.menuFile.setTitle(QtGui.QApplication.translate("MainWindow", "File", None, QtGui.QApplication.UnicodeUTF8))
        self.menuPlot.setTitle(QtGui.QApplication.translate("MainWindow", "Plot", None, QtGui.QApplication.UnicodeUTF8))
        self.menuAxes.setTitle(QtGui.QApplication.translate("MainWindow", "Axes", None, QtGui.QApplication.UnicodeUTF8))
        self.menuY_X_exp.setTitle(QtGui.QApplication.translate("MainWindow", "Y/X exp", None, QtGui.QApplication.UnicodeUTF8))
        self.menuScale.setTitle(QtGui.QApplication.translate("MainWindow", "Scale", None, QtGui.QApplication.UnicodeUTF8))
        self.menuCurves.setTitle(QtGui.QApplication.translate("MainWindow", "Curves", None, QtGui.QApplication.UnicodeUTF8))
        self.menuLines.setTitle(QtGui.QApplication.translate("MainWindow", "Lines", None, QtGui.QApplication.UnicodeUTF8))
        self.menuMarker.setTitle(QtGui.QApplication.translate("MainWindow", "Marker", None, QtGui.QApplication.UnicodeUTF8))
        self.actionSave_As.setText(QtGui.QApplication.translate("MainWindow", "Save As", None, QtGui.QApplication.UnicodeUTF8))
        self.actionPage_Setup.setText(QtGui.QApplication.translate("MainWindow", "Page Setup", None, QtGui.QApplication.UnicodeUTF8))
        self.actionPrint.setText(QtGui.QApplication.translate("MainWindow", "Print Preview", None, QtGui.QApplication.UnicodeUTF8))
        self.actionPrint_Preview.setText(QtGui.QApplication.translate("MainWindow", "Print", None, QtGui.QApplication.UnicodeUTF8))
        self.action_Close.setText(QtGui.QApplication.translate("MainWindow", "Close", None, QtGui.QApplication.UnicodeUTF8))
        self.actionGridON.setText(QtGui.QApplication.translate("MainWindow", "Grid ON", None, QtGui.QApplication.UnicodeUTF8))
        self.actionGridOFF.setText(QtGui.QApplication.translate("MainWindow", "OFF", None, QtGui.QApplication.UnicodeUTF8))
        self.actionAutoscale.setText(QtGui.QApplication.translate("MainWindow", "Autoscale", None, QtGui.QApplication.UnicodeUTF8))
        self.actionXlin_ylin.setText(QtGui.QApplication.translate("MainWindow", "xlin - ylin", None, QtGui.QApplication.UnicodeUTF8))
        self.actionXlin_ylog.setText(QtGui.QApplication.translate("MainWindow", "xlin - ylog", None, QtGui.QApplication.UnicodeUTF8))
        self.actionXlog_ylin.setText(QtGui.QApplication.translate("MainWindow", "xlog - ylin", None, QtGui.QApplication.UnicodeUTF8))
        self.actionXlog_ylog.setText(QtGui.QApplication.translate("MainWindow", "xlog - ylog", None, QtGui.QApplication.UnicodeUTF8))
        self.actionAbout.setText(QtGui.QApplication.translate("MainWindow", "About", None, QtGui.QApplication.UnicodeUTF8))
        self.actionLegend_ON.setText(QtGui.QApplication.translate("MainWindow", "Legend ON", None, QtGui.QApplication.UnicodeUTF8))
        self.actionLegend_OFF.setText(QtGui.QApplication.translate("MainWindow", "Legend OFF", None, QtGui.QApplication.UnicodeUTF8))
        self.actionTest.setText(QtGui.QApplication.translate("MainWindow", "test", None, QtGui.QApplication.UnicodeUTF8))
        self.actionTest_2.setText(QtGui.QApplication.translate("MainWindow", "Line", None, QtGui.QApplication.UnicodeUTF8))
        self.actionPoint.setText(QtGui.QApplication.translate("MainWindow", "Point", None, QtGui.QApplication.UnicodeUTF8))
        self.actionLine.setText(QtGui.QApplication.translate("MainWindow", "Line", None, QtGui.QApplication.UnicodeUTF8))
        self.actionPoint_Line.setText(QtGui.QApplication.translate("MainWindow", "Point+Line", None, QtGui.QApplication.UnicodeUTF8))
        self.actionCircle.setText(QtGui.QApplication.translate("MainWindow", "Circle", None, QtGui.QApplication.UnicodeUTF8))
        self.actionDiamond.setText(QtGui.QApplication.translate("MainWindow", "Diamond", None, QtGui.QApplication.UnicodeUTF8))
        self.actionCross.setText(QtGui.QApplication.translate("MainWindow", "Cross", None, QtGui.QApplication.UnicodeUTF8))
        self.actionPixel.setText(QtGui.QApplication.translate("MainWindow", "Square", None, QtGui.QApplication.UnicodeUTF8))
        self.actionDash_Line.setText(QtGui.QApplication.translate("MainWindow", "Dash Line", None, QtGui.QApplication.UnicodeUTF8))
        self.actionNo_Marker.setText(QtGui.QApplication.translate("MainWindow", "No Marker", None, QtGui.QApplication.UnicodeUTF8))
        self.actionNo_Line.setText(QtGui.QApplication.translate("MainWindow", "No Line", None, QtGui.QApplication.UnicodeUTF8))
        self.actionLine_3.setText(QtGui.QApplication.translate("MainWindow", "Solid", None, QtGui.QApplication.UnicodeUTF8))
        self.actionDash_Line_2.setText(QtGui.QApplication.translate("MainWindow", "Dashed", None, QtGui.QApplication.UnicodeUTF8))
        self.actionError_Bar.setText(QtGui.QApplication.translate("MainWindow", "Error Bar", None, QtGui.QApplication.UnicodeUTF8))
        self.actionDash_dot.setText(QtGui.QApplication.translate("MainWindow", "Dash-dot", None, QtGui.QApplication.UnicodeUTF8))
        self.actionDotted.setText(QtGui.QApplication.translate("MainWindow", "Dotted", None, QtGui.QApplication.UnicodeUTF8))
        self.actionTitle.setText(QtGui.QApplication.translate("MainWindow", "Set Title", None, QtGui.QApplication.UnicodeUTF8))
        self.actionSet_x_text.setText(QtGui.QApplication.translate("MainWindow", "Set X label", None, QtGui.QApplication.UnicodeUTF8))
        self.actionSet_Y_label.setText(QtGui.QApplication.translate("MainWindow", "Set Y label", None, QtGui.QApplication.UnicodeUTF8))
        self.actionFigure_Options.setText(QtGui.QApplication.translate("MainWindow", "Figure Options", None, QtGui.QApplication.UnicodeUTF8))
        self.actionSet_Marker_size.setText(QtGui.QApplication.translate("MainWindow", "Set Marker size", None, QtGui.QApplication.UnicodeUTF8))
        self.actionWxcwxc.setText(QtGui.QApplication.translate("MainWindow", "wxcwxc", None, QtGui.QApplication.UnicodeUTF8))
        self.actionCopy_to_cliipboard.setText(QtGui.QApplication.translate("MainWindow", "Copy to cliipboard", None, QtGui.QApplication.UnicodeUTF8))
        self.actionTitle_and_axes_labels.setText(QtGui.QApplication.translate("MainWindow", "Title and axes labels", None, QtGui.QApplication.UnicodeUTF8))
        self.actionDsd.setText(QtGui.QApplication.translate("MainWindow", "dsd", None, QtGui.QApplication.UnicodeUTF8))
        self.actionQsd.setText(QtGui.QApplication.translate("MainWindow", "qsd", None, QtGui.QApplication.UnicodeUTF8))
        self.actionSet_marker_size.setText(QtGui.QApplication.translate("MainWindow", "Set marker size", None, QtGui.QApplication.UnicodeUTF8))
        self.actionAutoscaling.setText(QtGui.QApplication.translate("MainWindow", "Autoscale", None, QtGui.QApplication.UnicodeUTF8))
        self.actionSet_X_range.setText(QtGui.QApplication.translate("MainWindow", "Set X range", None, QtGui.QApplication.UnicodeUTF8))
        self.actionSet_Y_range.setText(QtGui.QApplication.translate("MainWindow", "Set Y range", None, QtGui.QApplication.UnicodeUTF8))
        self.actionFix_scale.setText(QtGui.QApplication.translate("MainWindow", "Fix scale", None, QtGui.QApplication.UnicodeUTF8))
        self.actionSetTitle.setText(QtGui.QApplication.translate("MainWindow", "Title", None, QtGui.QApplication.UnicodeUTF8))
        self.actionX_label.setText(QtGui.QApplication.translate("MainWindow", "X label", None, QtGui.QApplication.UnicodeUTF8))
        self.actionY_label.setText(QtGui.QApplication.translate("MainWindow", "Y label", None, QtGui.QApplication.UnicodeUTF8))

from pySAXS.guisaxs.qt.matplotlibwidget import MatplotlibWidget
