
# This file was generated by 'versioneer.py' (0.19) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2021-01-28T14:36:00+0100",
 "dirty": false,
 "error": null,
 "full-revisionid": "c88d9c812e3cbb8e3c8f41341fa354fe451b0a8a",
 "version": "0.22.0"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
