
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2021-02-02T22:18:05+0000",
 "dirty": false,
 "error": null,
 "full-revisionid": "7ba752c1320c0b144e6e83970a9fbbc016c42999",
 "version": "0.6.2.post.dev146"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
