# Generated by Django 3.0.7 on 2020-07-05 03:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0013_auto_20200705_0346'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tmp_buffer',
            name='id',
            field=models.BigIntegerField(primary_key=True, serialize=False, verbose_name='Идентификатор'),
        ),
    ]
