# Generated by Django 3.0.8 on 2020-07-09 07:41

from django.conf import settings
from django.db import migrations
import django.db.models.deletion
import isc_common.fields.related


class Migration(migrations.Migration):

    dependencies = [
        ('ckk', '0230_auto_20200708_1517'),
        ('isc_common', '0053_delete_mat_view'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('sales', '0137_demand_date_sign'),
        ('production', '0271_auto_20200706_1130'),
        ('accounting', '0019_auto_20200709_0739'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tmp_buffer',
            name='color',
            field=isc_common.fields.related.ForeignKeyCascade(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='isc_common.Standard_colors'),
        ),
        migrations.AlterField(
            model_name='tmp_buffer',
            name='demand',
            field=isc_common.fields.related.ForeignKeyCascade(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='sales.Demand'),
        ),
        migrations.AlterField(
            model_name='tmp_buffer',
            name='edizm',
            field=isc_common.fields.related.ForeignKeyCascade(on_delete=django.db.models.deletion.CASCADE, to='ckk.Ed_izm'),
        ),
        migrations.AlterField(
            model_name='tmp_buffer',
            name='launch',
            field=isc_common.fields.related.ForeignKeyCascade(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='production.Launches'),
        ),
        migrations.AlterField(
            model_name='tmp_buffer',
            name='location',
            field=isc_common.fields.related.ForeignKeyCascade(on_delete=django.db.models.deletion.CASCADE, to='ckk.Locations'),
        ),
        migrations.AlterField(
            model_name='tmp_buffer',
            name='resource',
            field=isc_common.fields.related.ForeignKeyCascade(on_delete=django.db.models.deletion.CASCADE, to='production.Resource'),
        ),
        migrations.AlterField(
            model_name='tmp_buffer',
            name='user',
            field=isc_common.fields.related.ForeignKeyCascade(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
