
# This file was generated by 'versioneer.py' (0.15) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json
import sys

version_json = '''
{
 "dirty": false,
 "error": null,
 "full-revisionid": "8426d03a8b4b4abd4a6e36a627f6816f8db5fb06",
 "version": "2401"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
