# Generated by Django 2.2.1 on 2019-05-24 09:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0032_auto_20190524_0926'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='demand',
            name='parent',
        ),
    ]
