# Generated by Django 2.2.1 on 2019-05-24 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0033_remove_demand_parent'),
    ]

    operations = [
        migrations.AddField(
            model_name='demand',
            name='date',
            field=models.DateTimeField(blank=True, db_index=True, default=None, null=True, verbose_name='Дата'),
        ),
    ]
