# Generated by Django 2.2.2 on 2019-06-16 05:51

from django.db import migrations
import isc_common.fields.name_field


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0048_auto_20190529_0609'),
    ]

    operations = [
        migrations.AddField(
            model_name='demand',
            name='name',
            field=isc_common.fields.name_field.NameField(),
        ),
    ]
