# Generated by Django 2.2.6 on 2019-10-21 17:15

import django.db.models.deletion
from django.db import migrations

import isc_common.fields.related


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0070_auto_20191021_1657'),
    ]

    operations = [
        migrations.AddField(
            model_name='precent_dogovors',
            name='document',
            field=isc_common.fields.related.ForeignKeyProtect(default=None, on_delete=django.db.models.deletion.PROTECT, to='sales.Dogovors'),
        ),
        migrations.AddField(
            model_name='precent_dogovors',
            name='precent',
            field=isc_common.fields.related.ForeignKeyProtect(default=None, on_delete=django.db.models.deletion.PROTECT, to='sales.Precent'),
        ),
    ]
