# Generated by Django 2.2.6 on 2019-10-29 07:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0103_auto_20191029_0710'),
    ]

    operations = [
        migrations.RenameField(
            model_name='precent',
            old_name='type',
            new_name='precent_type',
        ),
    ]
