# Generated by Django 2.2.7 on 2019-11-21 12:10

import bitfield.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0118_auto_20191117_1623'),
    ]

    operations = [
        migrations.AlterField(
            model_name='statusdogovor',
            name='props',
            field=bitfield.models.BitField(('disabled', 'Неактивная запись в гриде'), db_index=True, default=1),
        ),
    ]
