# Generated by Django 3.0.7 on 2020-06-18 17:02

import django.db.models.deletion
from django.db import migrations, models

import isc_common.fields.related


class Migration(migrations.Migration):

    dependencies = [
        ('ckk', '0226_auto_20200421_1007'),
        ('sales', '0129_demand_qty_for_launch'),
    ]

    operations = [
        migrations.AddField(
            model_name='demand_materials',
            name='edizm',
            field=isc_common.fields.related.ForeignKeyProtect(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='ckk.Ed_izm'),
        ),
        migrations.AddField(
            model_name='demand_materials',
            name='material',
            field=isc_common.fields.related.ForeignKeyProtect(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='ckk.Materials'),
        ),
        migrations.AddField(
            model_name='demand_materials',
            name='material_askon',
            field=isc_common.fields.related.ForeignKeyProtect(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='ckk.Material_askon'),
        ),
        migrations.AddField(
            model_name='demand_materials',
            name='qty',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
