# Generated by Django 3.0.7 on 2020-06-18 17:22

import django.db.models.deletion
from django.db import migrations, models

import isc_common.fields.related


class Migration(migrations.Migration):

    dependencies = [
        ('ckk', '0226_auto_20200421_1007'),
        ('sales', '0131_auto_20200618_1709'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='demand_materials',
            name='precent_material',
        ),
        migrations.AlterField(
            model_name='demand_materials',
            name='edizm',
            field=isc_common.fields.related.ForeignKeyProtect(default=None, on_delete=django.db.models.deletion.PROTECT, to='ckk.Ed_izm'),
        ),
        migrations.AlterField(
            model_name='demand_materials',
            name='qty',
            field=models.PositiveIntegerField(default=None),
        ),
    ]
