# Generated by Django 3.0.7 on 2020-06-29 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0136_remove_demand_prority'),
    ]

    operations = [
        migrations.AddField(
            model_name='demand',
            name='date_sign',
            field=models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='Срок поставки'),
        ),
    ]
