# AUTOGENERATED BY NBDEV! DO NOT EDIT!

__all__ = ["index", "modules", "custom_doc_links", "git_url"]

index = {"union": "priceSdk.ipynb",
         "Endpoints": "priceSdk.ipynb",
         "PricingSdk": "priceSdk.ipynb",
         "uploadDf": "priceSdk.ipynb",
         "ingestData": "priceSdk.ipynb",
         "branchQuery": "priceSdk.ipynb",
         "queryAll2": "priceSdk.ipynb",
         "querySingleProduct2": "priceSdk.ipynb"}

modules = ["price.py"]

doc_url = "https://thanakijwanavit.github.io/villaPricingSdk/"

git_url = "https://github.com/thanakijwanavit/villaPricingSdk/tree/master/"

def custom_doc_links(name): return None
