# Generated by Django 2.2.1 on 2019-05-17 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kd', '0023_pathes_view'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document_attrs',
            name='value_str',
            field=models.TextField(blank=True, db_index=True, null=True, verbose_name='Значение атрибута'),
        ),
    ]
