# Generated by Django 2.2.3 on 2019-07-14 10:07

from django.db import migrations
import django.db.models.deletion
import isc_common.fields.related


class Migration(migrations.Migration):

    dependencies = [
        ('kd', '0059_auto_20190714_0906'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='uploades',
            name='log',
        ),
        migrations.AlterField(
            model_name='uploades_documents',
            name='document',
            field=isc_common.fields.related.ForeignKeyCascade(on_delete=django.db.models.deletion.CASCADE, to='kd.Documents'),
        ),
        migrations.AlterField(
            model_name='uploades_documents',
            name='upload',
            field=isc_common.fields.related.ForeignKeyCascade(on_delete=django.db.models.deletion.CASCADE, to='kd.Uploades'),
        ),
    ]
