# Generated by Django 2.2.3 on 2019-07-20 13:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kd', '0072_auto_20190720_1313'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='document_attr_cross',
            name='props',
        ),
    ]
