# Generated by Django 2.2.8 on 2019-12-13 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kd', '0086_lotsman_documents'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lotsman_documents',
            name='id',
            field=models.BigIntegerField(primary_key=True, serialize=False, verbose_name='Идентификатор'),
        ),
    ]
