
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2021-01-29T15:00:24-0700",
 "dirty": false,
 "error": null,
 "full-revisionid": "8da6a9d7e520fe51004e071eabc4eecb3310261a",
 "version": "2.1.0-beta.2"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
