# Generated by Django 2.1.4 on 2019-10-28 01:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trosnoth', '0027_auto_20191003_1109'),
    ]

    operations = [
        migrations.AddField(
            model_name='trosnotharena',
            name='balance_bot_difficulty',
            field=models.IntegerField(blank=True, default=20, null=True, verbose_name='Difficulty for BalanceBot.'),
        ),
        migrations.AddField(
            model_name='trosnotharena',
            name='machines_difficulty',
            field=models.IntegerField(default=50, verbose_name='Bot difficulty for Humans vs. Machines'),
        ),
    ]
