# Generated by Django 2.2.12 on 2021-01-27 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trosnoth', '0030_trosnotharena_require_everyone_ready'),
    ]

    operations = [
        migrations.AddField(
            model_name='trosnotharena',
            name='balance_bot_kind',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='trosnotharena',
            name='machines_bot_kind',
            field=models.TextField(default=''),
        ),
    ]
