
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2021-02-01T17:58:29-0800",
 "dirty": false,
 "error": null,
 "full-revisionid": "f01fcb52bd8a64a6a8b2c5e511d169a499c91293",
 "version": "2.2.8"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
