# Generated by Django 2.2.8 on 2019-12-07 18:11

from django.db import migrations
import django.db.models.deletion
import isc_common.fields.related


class Migration(migrations.Migration):

    dependencies = [
        ('planing', '0040_auto_20191207_1810'),
    ]

    operations = [
        migrations.AlterField(
            model_name='operation_launch_operation_material',
            name='launch_operation_material',
            field=isc_common.fields.related.ForeignKeyProtect(on_delete=django.db.models.deletion.PROTECT, to='production.Launch_operations_material'),
        ),
        migrations.AlterField(
            model_name='operation_launch_operation_resources',
            name='launch_operation_resources',
            field=isc_common.fields.related.ForeignKeyProtect(on_delete=django.db.models.deletion.PROTECT, to='production.Launch_operation_resources'),
        ),
        migrations.AlterField(
            model_name='operation_launch_operations_item',
            name='launch_operations_item',
            field=isc_common.fields.related.ForeignKeyProtect(on_delete=django.db.models.deletion.PROTECT, to='production.Launch_operations_item'),
        ),
    ]
