# Generated by Django 2.2.8 on 2019-12-07 23:57

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import isc_common.fields.related


class Migration(migrations.Migration):

    dependencies = [
        ('planing', '0045_operation_item_operation_locations_operation_material_operation_resources_operation_standard_prod'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='operations',
            name='level',
        ),
        migrations.RemoveField(
            model_name='operations',
            name='value',
        ),
        migrations.CreateModel(
            name='Operation_value',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False, verbose_name='Идентификатор')),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='Дата мягкого удаления')),
                ('editing', models.BooleanField(default=True, verbose_name='Возможность редактирования')),
                ('deliting', models.BooleanField(default=True, verbose_name='Возможность удаления')),
                ('lastmodified', models.DateTimeField(db_index=True, default=django.utils.timezone.now, editable=False, verbose_name='Последнее обновление')),
                ('value', models.DecimalField(decimal_places=4, max_digits=19)),
                ('operation', isc_common.fields.related.ForeignKeyProtect(on_delete=django.db.models.deletion.PROTECT, to='planing.Operations')),
            ],
            options={
                'verbose_name': 'Кросс таблица значений операции',
            },
        ),
    ]
