# Generated by Django 3.0.2 on 2020-01-19 11:30

from django.db import migrations
import django.db.models.deletion
import isc_common.fields.related


class Migration(migrations.Migration):

    dependencies = [
        ('planing', '0064_auto_20200119_0800'),
    ]

    operations = [
        migrations.AlterField(
            model_name='operation_value',
            name='operation',
            field=isc_common.fields.related.ForeignKeyCascade(on_delete=django.db.models.deletion.CASCADE, to='planing.Operations'),
        ),
    ]
