# Generated by Django 3.0.2 on 2020-01-31 11:09

from django.db import migrations, models
import django.db.models.expressions


class Migration(migrations.Migration):

    dependencies = [
        ('planing', '0083_auto_20200122_0752'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='operation_refs',
            unique_together={('child', 'parent')},
        ),
        migrations.AddConstraint(
            model_name='operation_refs',
            constraint=models.CheckConstraint(check=models.Q(_negated=True, child=django.db.models.expressions.F('parent')), name='Operation_refs_not_circulate_refs'),
        ),
    ]
