# Generated by Django 3.0.7 on 2020-06-06 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planing', '0125_auto_20200305_1729'),
    ]

    operations = [
        migrations.AlterField(
            model_name='levels',
            name='code',
            field=models.PositiveIntegerField(db_index=True),
        ),
        migrations.AlterField(
            model_name='operation_item',
            name='item_full_name',
            field=models.TextField(db_index=True),
        ),
        migrations.AlterField(
            model_name='operation_operation',
            name='num',
            field=models.PositiveIntegerField(db_index=True),
        ),
        migrations.AlterField(
            model_name='operation_operation',
            name='qty',
            field=models.PositiveIntegerField(blank=True, db_index=True, null=True),
        ),
    ]
