# Generated by Django 3.0.7 on 2020-06-14 10:04

import django.db.models.deletion
from django.db import migrations

import isc_common.fields.related


class Migration(migrations.Migration):
    dependencies = [
        ('ckk', '0226_auto_20200421_1007'),
        ('planing', '0133_auto_20200614_0958'),
    ]

    operations = [
        migrations.AddField(
            model_name='operation_item_add',
            name='item',
            field=isc_common.fields.related.ForeignKeyCascade(default=None, on_delete=django.db.models.deletion.CASCADE, to='ckk.Item'),
        ),
        migrations.AlterUniqueTogether(
            name='operation_item_add',
            unique_together={('item', 'item_full_name')},
        ),
        migrations.RemoveField(
            model_name='operation_item_add',
            name='operation_item',
        ),
    ]
