# Generated by Django 3.0.7 on 2020-06-14 10:13

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('production', '0233_auto_20200609_1920'),
        ('ckk', '0226_auto_20200421_1007'),
        ('planing', '0137_auto_20200614_1010'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='operation_item_add',
            unique_together={('item', 'item_full_name', 'launch')},
        ),
    ]
