# Generated by Django 3.0.7 on 2020-06-15 05:17

import bitfield.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('planing', '0140_auto_20200615_0347'),
    ]

    operations = [
        migrations.AlterField(
            model_name='operation_refs',
            name='props',
            field=bitfield.models.BitField((('inner_routing', 'Связь операций внутри товарной позиции'), ('outer_routing', 'Связь операций между товарными позициями'), ('product_order_routing', 'Связи в блоке заказы на производство'), ('product_meking', 'Связи в блоке выпуска')), db_index=True, default=0),
        ),
    ]
