# Generated by Django 3.0.7 on 2020-06-17 06:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('planing', '0145_auto_20200617_0652'),
    ]

    operations = [
        migrations.RenameField(
            model_name='operation_material',
            old_name='material',
            new_name='launch_operations_material',
        ),
    ]
