# Generated by Django 3.0.7 on 2020-06-17 18:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('planing', '0153_auto_20200617_1839'),
    ]

    operations = [
        migrations.RenameField(
            model_name='operation_resources',
            old_name='launch_operation_resources',
            new_name='resources',
        ),
    ]
