# Generated by Django 3.0.7 on 2020-06-17 18:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0242_auto_20200617_0805'),
        ('planing', '0154_auto_20200617_1840'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='operation_resources',
            unique_together={('operation', 'resources')},
        ),
    ]
