# Generated by Django 3.0.7 on 2020-06-17 20:53

import bitfield.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planing', '0159_auto_20200617_1929'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Production_order',
        ),
        migrations.AlterField(
            model_name='operation_value',
            name='props',
            field=bitfield.models.BitField((('perone', 'Из расчета на еденицу продукции'), ('used_in_start', 'Учавствовало в учете запуска'), ('used_in_release', 'Учавствовало в учете выпуска')), db_index=True, default=0),
        ),
        migrations.CreateModel(
            name='Production_order',
            fields=[
                ('operations_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='planing.Operations')),
            ],
            options={
                'verbose_name': 'Заказы на производство',
                'db_table': 'planing_production_order_view',
                'managed': False,
            },
            bases=('planing.operations',),
        ),
    ]
