# Generated by Django 3.0.7 on 2020-06-23 09:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ckk', '0228_auto_20200623_0550'),
        ('production', '0255_delete_launch_item_add'),
        ('planing', '0165_operation_item_add_edizm'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='operation_item_add',
            unique_together={('item', 'item_full_name', 'launch', 'edizm')},
        ),
    ]
