# Generated by Django 3.0.8 on 2020-07-06 14:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('planing', '0179_operation_resources_location_fin'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='operation_resources',
            unique_together=set(),
        ),
    ]
