# Generated by Django 3.0.8 on 2020-07-17 03:08

from django.db import migrations, models
import django.db.models.deletion
import isc_common.fields.code_field
import isc_common.fields.date_time_field
import isc_common.fields.related


class Migration(migrations.Migration):

    dependencies = [
        ('planing', '0200_auto_20200715_2231'),
    ]

    operations = [
        migrations.AddField(
            model_name='operation_history',
            name='date',
            field=isc_common.fields.date_time_field.DateTimeField(default=None),
        ),
        migrations.AddField(
            model_name='operation_history',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='operation_history',
            name='num',
            field=isc_common.fields.code_field.CodeStrictField(),
        ),
        migrations.AddField(
            model_name='operation_history',
            name='opertype',
            field=isc_common.fields.related.ForeignKeyProtect(default=None, on_delete=django.db.models.deletion.PROTECT, to='planing.Operation_types'),
        ),
    ]
