# Generated by Django 3.0.8 on 2020-08-01 04:41

from django.db import migrations
import django.db.models.deletion
import isc_common.fields.related


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0297_auto_20200801_0441'),
        ('planing', '0216_auto_20200725_1110'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='operation_resources',
            name='Operation_resources_unique_constraint_01',
        ),
        migrations.RemoveConstraint(
            model_name='operation_resources',
            name='Operation_resources_unique_constraint_11',
        ),
        migrations.AddField(
            model_name='operation_resources',
            name='resource_fin',
            field=isc_common.fields.related.ForeignKeyProtect(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='planing_resource_fin_res', to='production.Resource'),
        ),
    ]
