# Generated by Django 3.1 on 2020-08-05 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planing', '0221_auto_20200805_0857'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='operation_operation',
            constraint=models.UniqueConstraint(condition=models.Q(color=None), fields=('operation', 'production_operation'), name='Operation_operation_unique_constraint_0'),
        ),
        migrations.AddConstraint(
            model_name='operation_operation',
            constraint=models.UniqueConstraint(fields=('color', 'operation', 'production_operation'), name='Operation_operation_unique_constraint_1'),
        ),
    ]
