# Generated by Django 3.1 on 2020-08-17 09:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('planing', '0225_auto_20200813_1048'),
    ]

    operations = [
        migrations.RunSQL('''update planing_operation_value
                                set edizm_id = (select id from ckk_ed_izm where code = 'шт')
                                where edizm_id is null''')
    ]
