# Generated by Django 3.1 on 2020-08-21 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planing', '0231_auto_20200821_1956'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='tmp_operation_value',
            name='Tmp_operation_value_unique_constraint_0',
        ),
        migrations.RemoveConstraint(
            model_name='tmp_operation_value',
            name='Tmp_operation_value_unique_constraint_1',
        ),
        migrations.AddConstraint(
            model_name='tmp_operation_value',
            constraint=models.UniqueConstraint(condition=models.Q(parent=None), fields=('child', 'main', 'launch', 'user'), name='Tmp_operation_value_unique_constraint_0'),
        ),
        migrations.AddConstraint(
            model_name='tmp_operation_value',
            constraint=models.UniqueConstraint(fields=('child', 'main', 'launch', 'parent', 'user'), name='Tmp_operation_value_unique_constraint_1'),
        ),
    ]
