# Generated by Django 3.1 on 2020-08-22 04:34

from django.db import migrations
import django.db.models.deletion
import isc_common.fields.related


class Migration(migrations.Migration):

    dependencies = [
        ('ckk', '0248_auto_20200821_1509'),
        ('planing', '0232_auto_20200821_1959'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tmp_operation_value',
            name='main',
            field=isc_common.fields.related.ForeignKeyCascade(on_delete=django.db.models.deletion.CASCADE, related_name='Tmp_operation_value_main', to='ckk.item'),
        ),
    ]
