# Generated by Django 3.1 on 2020-08-22 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planing', '0238_auto_20200822_1014'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tmp_operation_value',
            name='need_value',
            field=models.DecimalField(decimal_places=4, max_digits=19),
        ),
    ]
