# Generated by Django 3.1 on 2020-08-22 14:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('planing', '0240_auto_20200822_1218'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tmp_operation_value',
            name='last_tech_operation',
        ),
    ]
