# Generated by Django 3.1 on 2020-08-22 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planing', '0243_remove_tmp_operation_value_need_value'),
    ]

    operations = [
        migrations.AddField(
            model_name='tmp_operation_value',
            name='need_value',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=19, null=True),
        ),
    ]
