# Generated by Django 3.1 on 2020-08-25 20:03

import bitfield.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('planing', '0248_auto_20200823_0821'),
    ]

    operations = [
        migrations.AddField(
            model_name='operation_launches',
            name='props',
            field=bitfield.models.BitField((('auxiliary', 'Прикрипленный запуск'),), db_index=True, default=0),
        ),
    ]
