# Generated by Django 3.1.1 on 2020-10-01 05:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('planing', '0250_auto_20200924_1407'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Operation_locations_view',
        ),
    ]
