# Generated by Django 3.1.3 on 2020-11-20 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planing', '0259_auto_20201120_1001'),
    ]

    operations = [
        migrations.AddField(
            model_name='production_order_tmp',
            name='parent_id_f',
            field=models.BigIntegerField(blank=True, db_index=True, null=True),
        ),
    ]
