# Generated by Django 3.1.3 on 2020-11-20 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planing', '0265_production_order_tmp_edizm'),
    ]

    operations = [
        migrations.AlterField(
            model_name='production_order_tmp',
            name='process',
            field=models.BigIntegerField(db_index=True, default=None),
        ),
    ]
