# Generated by Django 3.1.3 on 2020-11-20 13:34

from django.db import migrations
import django.db.models.deletion
import isc_common.fields.related


class Migration(migrations.Migration):

    dependencies = [
        ('isc_common', '0056_last_used_processes'),
        ('planing', '0266_auto_20201120_1316'),
    ]

    operations = [
        migrations.AddField(
            model_name='production_order_tmp',
            name='color',
            field=isc_common.fields.related.ForeignKeyProtect(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='Production_order_tmp_color', to='isc_common.standard_colors'),
        ),
    ]
