# Generated by Django 3.1.4 on 2020-12-03 12:49

import django.contrib.postgres.fields
from django.db import migrations
import isc_common.fields.code_field


class Migration(migrations.Migration):

    dependencies = [
        ('planing', '0273_production_order_tmp_childs'),
    ]

    operations = [
        migrations.AlterField(
            model_name='production_order_tmp',
            name='childs',
            field=django.contrib.postgres.fields.ArrayField(base_field=isc_common.fields.code_field.JSONFieldIVC(default=dict), blank=True, default=list, null=True, size=None),
        ),
    ]
