# Generated by Django 3.1.4 on 2020-12-04 13:54

from django.db import migrations, models
import isc_common.fields.code_field
import isc_common.fields.name_field


class Migration(migrations.Migration):

    dependencies = [
        ('planing', '0283_production_order_made_history_grouped_view'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='production_order_made_history',
            name='launch',
        ),
        migrations.RemoveField(
            model_name='production_order_made_history',
            name='status',
        ),
        migrations.AddField(
            model_name='production_order_made_history',
            name='launch__code',
            field=isc_common.fields.code_field.CodeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='production_order_made_history',
            name='launch__date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='production_order_made_history',
            name='status__code',
            field=isc_common.fields.code_field.CodeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='production_order_made_history',
            name='status__name',
            field=isc_common.fields.name_field.NameField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='production_order_made_history',
            name='value1_sum',
            field=isc_common.fields.code_field.CodeField(blank=True, null=True),
        ),
        migrations.AlterModelTable(
            name='production_order_made_history_grouped_view',
            table='planing_production_order_made_history_grouped_view',
        ),
    ]
