# Generated by Django 3.1.4 on 2020-12-04 14:49

from django.db import migrations
import isc_common.fields.name_field


class Migration(migrations.Migration):

    dependencies = [
        ('planing', '0289_auto_20201204_1444'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='production_order_made_history',
            name='item',
        ),
        migrations.AddField(
            model_name='production_order_made_history',
            name='item_STMP_1_value_str',
            field=isc_common.fields.name_field.NameField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='production_order_made_history',
            name='item_STMP_2_value_str',
            field=isc_common.fields.name_field.NameField(blank=True, null=True),
        ),
    ]
