# Generated by Django 3.1.4 on 2020-12-04 16:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('planing', '0292_remove_production_order_made_history_opertype'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='production_order_made_history',
            name='arranges_exucutors',
        ),
        migrations.RemoveField(
            model_name='production_order_made_history',
            name='child_launches',
        ),
        migrations.RemoveField(
            model_name='production_order_made_history',
            name='childs',
        ),
        migrations.RemoveField(
            model_name='production_order_made_history',
            name='cnt_opers',
        ),
        migrations.RemoveField(
            model_name='production_order_made_history',
            name='demand_ids',
        ),
        migrations.RemoveField(
            model_name='production_order_made_history',
            name='enabled',
        ),
        migrations.RemoveField(
            model_name='production_order_made_history',
            name='exucutors',
        ),
        migrations.RemoveField(
            model_name='production_order_made_history',
            name='exucutors_old',
        ),
        migrations.RemoveField(
            model_name='production_order_made_history',
            name='has_color',
        ),
        migrations.RemoveField(
            model_name='production_order_made_history',
            name='has_launched',
        ),
        migrations.RemoveField(
            model_name='production_order_made_history',
            name='isDeleted',
        ),
        migrations.RemoveField(
            model_name='production_order_made_history',
            name='launches_odd',
        ),
        migrations.RemoveField(
            model_name='production_order_made_history',
            name='location_ids',
        ),
        migrations.RemoveField(
            model_name='production_order_made_history',
            name='location_ids_old',
        ),
        migrations.RemoveField(
            model_name='production_order_made_history',
            name='location_sector_ids',
        ),
        migrations.RemoveField(
            model_name='production_order_made_history',
            name='location_status_colors',
        ),
        migrations.RemoveField(
            model_name='production_order_made_history',
            name='location_status_ids',
        ),
        migrations.RemoveField(
            model_name='production_order_made_history',
            name='location_statuses',
        ),
        migrations.RemoveField(
            model_name='production_order_made_history',
            name='locations_sector_full_name',
        ),
        migrations.RemoveField(
            model_name='production_order_made_history',
            name='num',
        ),
        migrations.RemoveField(
            model_name='production_order_made_history',
            name='parent_item',
        ),
        migrations.RemoveField(
            model_name='production_order_made_history',
            name='parent_item_ids',
        ),
        migrations.RemoveField(
            model_name='production_order_made_history',
            name='parent_mul',
        ),
    ]
