# Generated by Django 3.1.4 on 2020-12-09 06:06

import bitfield.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('planing', '0299_production_order_tmp_location_values_made'),
    ]

    operations = [
        migrations.AlterField(
            model_name='production_order_tmp',
            name='props',
            field=bitfield.models.BitField((('absorption', 'Для поглощения'), ('qty_not_editing', 'Без возможности правки кол-ва')), db_index=True, default=0),
        ),
    ]
