# coding: utf-8

"""
    Coin CRDB Rest API

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 3.0.0
    Contact: devops@coin.nl
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


import pprint

import six

from coin_sdk.number_portability.messages.portingperformed.porting_performed import PortingPerformed  # noqa: F401,E501


class PortingPerformedBody(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'portingperformed': 'PortingPerformed'
    }

    attribute_map = {
        'portingperformed': 'portingperformed'
    }

    def __init__(self, portingperformed=None):  # noqa: E501
        """PortingPerformedBody - a model defined in Swagger"""  # noqa: E501

        self._portingperformed = None
        self.discriminator = None

        self.portingperformed = portingperformed

    @property
    def portingperformed(self):
        """Gets the portingperformed of this PortingPerformedBody.  # noqa: E501


        :return: The portingperformed of this PortingPerformedBody.  # noqa: E501
        :rtype: PortingPerformed
        """
        return self._portingperformed

    @portingperformed.setter
    def portingperformed(self, portingperformed):
        """Sets the portingperformed of this PortingPerformedBody.


        :param portingperformed: The portingperformed of this PortingPerformedBody.  # noqa: E501
        :type: PortingPerformed
        """
        if portingperformed is None:
            raise ValueError("Invalid value for `portingperformed`, must not be `None`")  # noqa: E501

        self._portingperformed = portingperformed

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(PortingPerformedBody, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, PortingPerformedBody):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
