# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'mainGuisaxs.ui'
#
# Created: Thu Jun 27 10:22:20 2013
#      by: PyQt4 UI code generator 4.9.5
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    _fromUtf8 = lambda s: s

class Ui_mainGuisaxsWindows(object):
    def setupUi(self, mainGuisaxsWindows):
        mainGuisaxsWindows.setObjectName(_fromUtf8("mainGuisaxsWindows"))
        mainGuisaxsWindows.resize(453, 690)
        mainGuisaxsWindows.setStatusTip(_fromUtf8(""))
        self.centralwidget = QtGui.QWidget(mainGuisaxsWindows)
        self.centralwidget.setObjectName(_fromUtf8("centralwidget"))
        self.verticalLayout_5 = QtGui.QVBoxLayout(self.centralwidget)
        self.verticalLayout_5.setObjectName(_fromUtf8("verticalLayout_5"))
        self.treeWidget = QtGui.QTreeWidget(self.centralwidget)
        self.treeWidget.setMinimumSize(QtCore.QSize(0, 400))
        self.treeWidget.setAlternatingRowColors(False)
        self.treeWidget.setRootIsDecorated(True)
        self.treeWidget.setItemsExpandable(True)
        self.treeWidget.setAnimated(True)
        self.treeWidget.setExpandsOnDoubleClick(True)
        self.treeWidget.setObjectName(_fromUtf8("treeWidget"))
        self.treeWidget.headerItem().setText(0, _fromUtf8("1"))
        self.verticalLayout_5.addWidget(self.treeWidget)
        self.groupBox_2 = QtGui.QGroupBox(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox_2.sizePolicy().hasHeightForWidth())
        self.groupBox_2.setSizePolicy(sizePolicy)
        self.groupBox_2.setMaximumSize(QtCore.QSize(16777215, 400))
        self.groupBox_2.setObjectName(_fromUtf8("groupBox_2"))
        self.verticalLayout_4 = QtGui.QVBoxLayout(self.groupBox_2)
        self.verticalLayout_4.setObjectName(_fromUtf8("verticalLayout_4"))
        self.multitxt = QtGui.QTextBrowser(self.groupBox_2)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.multitxt.sizePolicy().hasHeightForWidth())
        self.multitxt.setSizePolicy(sizePolicy)
        self.multitxt.setObjectName(_fromUtf8("multitxt"))
        self.verticalLayout_4.addWidget(self.multitxt)
        self.verticalLayout_5.addWidget(self.groupBox_2)
        mainGuisaxsWindows.setCentralWidget(self.centralwidget)
        self.menubar = QtGui.QMenuBar(mainGuisaxsWindows)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 453, 21))
        self.menubar.setObjectName(_fromUtf8("menubar"))
        self.menuFile = QtGui.QMenu(self.menubar)
        self.menuFile.setObjectName(_fromUtf8("menuFile"))
        self.menuRecents = QtGui.QMenu(self.menuFile)
        self.menuRecents.setObjectName(_fromUtf8("menuRecents"))
        self.menuEdit = QtGui.QMenu(self.menubar)
        self.menuEdit.setObjectName(_fromUtf8("menuEdit"))
        self.menuData_Treatment = QtGui.QMenu(self.menubar)
        self.menuData_Treatment.setObjectName(_fromUtf8("menuData_Treatment"))
        self.menuFit = QtGui.QMenu(self.menubar)
        self.menuFit.setObjectName(_fromUtf8("menuFit"))
        self.menuTools = QtGui.QMenu(self.menubar)
        self.menuTools.setObjectName(_fromUtf8("menuTools"))
        self.menuHelp = QtGui.QMenu(self.menubar)
        self.menuHelp.setObjectName(_fromUtf8("menuHelp"))
        self.menuDocuments = QtGui.QMenu(self.menuHelp)
        self.menuDocuments.setObjectName(_fromUtf8("menuDocuments"))
        mainGuisaxsWindows.setMenuBar(self.menubar)
        self.statusbar = QtGui.QStatusBar(mainGuisaxsWindows)
        self.statusbar.setObjectName(_fromUtf8("statusbar"))
        mainGuisaxsWindows.setStatusBar(self.statusbar)
        self.actionOpen = QtGui.QAction(mainGuisaxsWindows)
        self.actionOpen.setObjectName(_fromUtf8("actionOpen"))
        self.actionOpen_Dataset = QtGui.QAction(mainGuisaxsWindows)
        self.actionOpen_Dataset.setObjectName(_fromUtf8("actionOpen_Dataset"))
        self.actionExit = QtGui.QAction(mainGuisaxsWindows)
        self.actionExit.setObjectName(_fromUtf8("actionExit"))
        self.actionSave = QtGui.QAction(mainGuisaxsWindows)
        self.actionSave.setObjectName(_fromUtf8("actionSave"))
        self.actionSave_As = QtGui.QAction(mainGuisaxsWindows)
        self.actionSave_As.setObjectName(_fromUtf8("actionSave_As"))
        self.actionReset_datas = QtGui.QAction(mainGuisaxsWindows)
        self.actionReset_datas.setObjectName(_fromUtf8("actionReset_datas"))
        self.actionSelect_All = QtGui.QAction(mainGuisaxsWindows)
        self.actionSelect_All.setObjectName(_fromUtf8("actionSelect_All"))
        self.actionUnselect_All = QtGui.QAction(mainGuisaxsWindows)
        self.actionUnselect_All.setObjectName(_fromUtf8("actionUnselect_All"))
        self.actionRefresh_from_file = QtGui.QAction(mainGuisaxsWindows)
        self.actionRefresh_from_file.setObjectName(_fromUtf8("actionRefresh_from_file"))
        self.actionRename = QtGui.QAction(mainGuisaxsWindows)
        self.actionRename.setObjectName(_fromUtf8("actionRename"))
        self.actionRemove = QtGui.QAction(mainGuisaxsWindows)
        self.actionRemove.setObjectName(_fromUtf8("actionRemove"))
        self.actionDuplicate = QtGui.QAction(mainGuisaxsWindows)
        self.actionDuplicate.setObjectName(_fromUtf8("actionDuplicate"))
        self.actionDuplicate_without_links = QtGui.QAction(mainGuisaxsWindows)
        self.actionDuplicate_without_links.setObjectName(_fromUtf8("actionDuplicate_without_links"))
        self.actionClip_Q_range = QtGui.QAction(mainGuisaxsWindows)
        self.actionClip_Q_range.setObjectName(_fromUtf8("actionClip_Q_range"))
        self.actionScale_Q_range = QtGui.QAction(mainGuisaxsWindows)
        self.actionScale_Q_range.setObjectName(_fromUtf8("actionScale_Q_range"))
        self.actionConcatenate = QtGui.QAction(mainGuisaxsWindows)
        self.actionConcatenate.setObjectName(_fromUtf8("actionConcatenate"))
        self.actionDerivate = QtGui.QAction(mainGuisaxsWindows)
        self.actionDerivate.setObjectName(_fromUtf8("actionDerivate"))
        self.actionSmooth = QtGui.QAction(mainGuisaxsWindows)
        self.actionSmooth.setObjectName(_fromUtf8("actionSmooth"))
        self.actionFind_Peaks = QtGui.QAction(mainGuisaxsWindows)
        self.actionFind_Peaks.setObjectName(_fromUtf8("actionFind_Peaks"))
        self.actionInterpolate = QtGui.QAction(mainGuisaxsWindows)
        self.actionInterpolate.setObjectName(_fromUtf8("actionInterpolate"))
        self.actionCalculator = QtGui.QAction(mainGuisaxsWindows)
        self.actionCalculator.setObjectName(_fromUtf8("actionCalculator"))
        self.actionStatistics = QtGui.QAction(mainGuisaxsWindows)
        self.actionStatistics.setObjectName(_fromUtf8("actionStatistics"))
        self.actionGenerate_Noise = QtGui.QAction(mainGuisaxsWindows)
        self.actionGenerate_Noise.setObjectName(_fromUtf8("actionGenerate_Noise"))
        self.actionTransmission_and_Background_correction = QtGui.QAction(mainGuisaxsWindows)
        self.actionTransmission_and_Background_correction.setObjectName(_fromUtf8("actionTransmission_and_Background_correction"))
        self.actionCalculate_Resolution_function = QtGui.QAction(mainGuisaxsWindows)
        self.actionCalculate_Resolution_function.setObjectName(_fromUtf8("actionCalculate_Resolution_function"))
        self.actionDesmearing = QtGui.QAction(mainGuisaxsWindows)
        self.actionDesmearing.setObjectName(_fromUtf8("actionDesmearing"))
        self.actionAbsolute_scaling = QtGui.QAction(mainGuisaxsWindows)
        self.actionAbsolute_scaling.setObjectName(_fromUtf8("actionAbsolute_scaling"))
        self.actionRadial_averaging = QtGui.QAction(mainGuisaxsWindows)
        self.actionRadial_averaging.setObjectName(_fromUtf8("actionRadial_averaging"))
        self.actionInvariant = QtGui.QAction(mainGuisaxsWindows)
        self.actionInvariant.setObjectName(_fromUtf8("actionInvariant"))
        self.actionX_ray_absorption = QtGui.QAction(mainGuisaxsWindows)
        self.actionX_ray_absorption.setObjectName(_fromUtf8("actionX_ray_absorption"))
        self.actionX_ray_absorption_Xraylib = QtGui.QAction(mainGuisaxsWindows)
        self.actionX_ray_absorption_Xraylib.setObjectName(_fromUtf8("actionX_ray_absorption_Xraylib"))
        self.actionFind_peaks = QtGui.QAction(mainGuisaxsWindows)
        self.actionFind_peaks.setObjectName(_fromUtf8("actionFind_peaks"))
        self.actionChanges = QtGui.QAction(mainGuisaxsWindows)
        self.actionChanges.setObjectName(_fromUtf8("actionChanges"))
        self.actionLicence = QtGui.QAction(mainGuisaxsWindows)
        self.actionLicence.setObjectName(_fromUtf8("actionLicence"))
        self.actionAbout = QtGui.QAction(mainGuisaxsWindows)
        self.actionAbout.setObjectName(_fromUtf8("actionAbout"))
        self.actionAppend_Dataset = QtGui.QAction(mainGuisaxsWindows)
        self.actionAppend_Dataset.setObjectName(_fromUtf8("actionAppend_Dataset"))
        self.actionExport = QtGui.QAction(mainGuisaxsWindows)
        self.actionExport.setObjectName(_fromUtf8("actionExport"))
        self.actionAddReferenceValue = QtGui.QAction(mainGuisaxsWindows)
        self.actionAddReferenceValue.setObjectName(_fromUtf8("actionAddReferenceValue"))
        self.actionRemove_dependencies = QtGui.QAction(mainGuisaxsWindows)
        self.actionRemove_dependencies.setObjectName(_fromUtf8("actionRemove_dependencies"))
        self.actionTest = QtGui.QAction(mainGuisaxsWindows)
        self.actionTest.setObjectName(_fromUtf8("actionTest"))
        self.actionModels_2 = QtGui.QAction(mainGuisaxsWindows)
        self.actionModels_2.setObjectName(_fromUtf8("actionModels_2"))
        self.actionQsdqsd = QtGui.QAction(mainGuisaxsWindows)
        self.actionQsdqsd.setObjectName(_fromUtf8("actionQsdqsd"))
        self.actionBlablqsd = QtGui.QAction(mainGuisaxsWindows)
        self.actionBlablqsd.setObjectName(_fromUtf8("actionBlablqsd"))
        self.actionDoc = QtGui.QAction(mainGuisaxsWindows)
        self.actionDoc.setObjectName(_fromUtf8("actionDoc"))
        self.actionChange_color = QtGui.QAction(mainGuisaxsWindows)
        self.actionChange_color.setObjectName(_fromUtf8("actionChange_color"))
        self.actionSet_as_reference = QtGui.QAction(mainGuisaxsWindows)
        self.actionSet_as_reference.setObjectName(_fromUtf8("actionSet_as_reference"))
        self.menuFile.addAction(self.actionOpen)
        self.menuFile.addAction(self.actionOpen_Dataset)
        self.menuFile.addAction(self.actionAppend_Dataset)
        self.menuFile.addSeparator()
        self.menuFile.addAction(self.menuRecents.menuAction())
        self.menuFile.addSeparator()
        self.menuFile.addAction(self.actionSave)
        self.menuFile.addAction(self.actionSave_As)
        self.menuFile.addAction(self.actionExport)
        self.menuFile.addSeparator()
        self.menuFile.addAction(self.actionReset_datas)
        self.menuFile.addSeparator()
        self.menuFile.addAction(self.actionExit)
        self.menuEdit.addAction(self.actionSelect_All)
        self.menuEdit.addAction(self.actionUnselect_All)
        self.menuEdit.addSeparator()
        self.menuEdit.addAction(self.actionRefresh_from_file)
        self.menuEdit.addAction(self.actionRename)
        self.menuEdit.addAction(self.actionRemove)
        self.menuEdit.addAction(self.actionDuplicate)
        self.menuEdit.addAction(self.actionDuplicate_without_links)
        self.menuEdit.addAction(self.actionRemove_dependencies)
        self.menuEdit.addSeparator()
        self.menuEdit.addAction(self.actionClip_Q_range)
        self.menuEdit.addAction(self.actionScale_Q_range)
        self.menuEdit.addSeparator()
        self.menuEdit.addAction(self.actionConcatenate)
        self.menuEdit.addAction(self.actionDerivate)
        self.menuEdit.addAction(self.actionSmooth)
        self.menuEdit.addAction(self.actionFind_Peaks)
        self.menuEdit.addAction(self.actionInterpolate)
        self.menuEdit.addAction(self.actionCalculator)
        self.menuEdit.addAction(self.actionStatistics)
        self.menuEdit.addAction(self.actionGenerate_Noise)
        self.menuEdit.addAction(self.actionAddReferenceValue)
        self.menuEdit.addSeparator()
        self.menuEdit.addAction(self.actionChange_color)
        self.menuEdit.addSeparator()
        self.menuEdit.addAction(self.actionSet_as_reference)
        self.menuTools.addAction(self.actionX_ray_absorption)
        self.menuTools.addAction(self.actionFind_peaks)
        self.menuHelp.addAction(self.menuDocuments.menuAction())
        self.menuHelp.addAction(self.actionChanges)
        self.menuHelp.addAction(self.actionLicence)
        self.menuHelp.addAction(self.actionAbout)
        self.menubar.addAction(self.menuFile.menuAction())
        self.menubar.addAction(self.menuEdit.menuAction())
        self.menubar.addAction(self.menuData_Treatment.menuAction())
        self.menubar.addAction(self.menuFit.menuAction())
        self.menubar.addAction(self.menuTools.menuAction())
        self.menubar.addAction(self.menuHelp.menuAction())

        self.retranslateUi(mainGuisaxsWindows)
        QtCore.QMetaObject.connectSlotsByName(mainGuisaxsWindows)

    def retranslateUi(self, mainGuisaxsWindows):
        mainGuisaxsWindows.setWindowTitle(QtGui.QApplication.translate("mainGuisaxsWindows", "MainWindow", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox_2.setTitle(QtGui.QApplication.translate("mainGuisaxsWindows", "Logbook", None, QtGui.QApplication.UnicodeUTF8))
        self.menuFile.setTitle(QtGui.QApplication.translate("mainGuisaxsWindows", "File", None, QtGui.QApplication.UnicodeUTF8))
        self.menuRecents.setTitle(QtGui.QApplication.translate("mainGuisaxsWindows", "Recents", None, QtGui.QApplication.UnicodeUTF8))
        self.menuEdit.setTitle(QtGui.QApplication.translate("mainGuisaxsWindows", "Edit", None, QtGui.QApplication.UnicodeUTF8))
        self.menuData_Treatment.setTitle(QtGui.QApplication.translate("mainGuisaxsWindows", "Data Treatment", None, QtGui.QApplication.UnicodeUTF8))
        self.menuFit.setTitle(QtGui.QApplication.translate("mainGuisaxsWindows", "Fit", None, QtGui.QApplication.UnicodeUTF8))
        self.menuTools.setTitle(QtGui.QApplication.translate("mainGuisaxsWindows", "Tools", None, QtGui.QApplication.UnicodeUTF8))
        self.menuHelp.setTitle(QtGui.QApplication.translate("mainGuisaxsWindows", "Help", None, QtGui.QApplication.UnicodeUTF8))
        self.menuDocuments.setTitle(QtGui.QApplication.translate("mainGuisaxsWindows", "Documents", None, QtGui.QApplication.UnicodeUTF8))
        self.actionOpen.setText(QtGui.QApplication.translate("mainGuisaxsWindows", "Open", None, QtGui.QApplication.UnicodeUTF8))
        self.actionOpen_Dataset.setText(QtGui.QApplication.translate("mainGuisaxsWindows", "Open Dataset", None, QtGui.QApplication.UnicodeUTF8))
        self.actionExit.setText(QtGui.QApplication.translate("mainGuisaxsWindows", "Exit", None, QtGui.QApplication.UnicodeUTF8))
        self.actionSave.setText(QtGui.QApplication.translate("mainGuisaxsWindows", "Save", None, QtGui.QApplication.UnicodeUTF8))
        self.actionSave_As.setText(QtGui.QApplication.translate("mainGuisaxsWindows", "Save As", None, QtGui.QApplication.UnicodeUTF8))
        self.actionReset_datas.setText(QtGui.QApplication.translate("mainGuisaxsWindows", "Reset datas", None, QtGui.QApplication.UnicodeUTF8))
        self.actionSelect_All.setText(QtGui.QApplication.translate("mainGuisaxsWindows", "Select All", None, QtGui.QApplication.UnicodeUTF8))
        self.actionUnselect_All.setText(QtGui.QApplication.translate("mainGuisaxsWindows", "Unselect All", None, QtGui.QApplication.UnicodeUTF8))
        self.actionRefresh_from_file.setText(QtGui.QApplication.translate("mainGuisaxsWindows", "Refresh from file", None, QtGui.QApplication.UnicodeUTF8))
        self.actionRename.setText(QtGui.QApplication.translate("mainGuisaxsWindows", "Rename", None, QtGui.QApplication.UnicodeUTF8))
        self.actionRemove.setText(QtGui.QApplication.translate("mainGuisaxsWindows", "Remove", None, QtGui.QApplication.UnicodeUTF8))
        self.actionDuplicate.setText(QtGui.QApplication.translate("mainGuisaxsWindows", "Duplicate", None, QtGui.QApplication.UnicodeUTF8))
        self.actionDuplicate_without_links.setText(QtGui.QApplication.translate("mainGuisaxsWindows", "Duplicate without links", None, QtGui.QApplication.UnicodeUTF8))
        self.actionClip_Q_range.setText(QtGui.QApplication.translate("mainGuisaxsWindows", "Clip Q range", None, QtGui.QApplication.UnicodeUTF8))
        self.actionScale_Q_range.setText(QtGui.QApplication.translate("mainGuisaxsWindows", "Scale Q range", None, QtGui.QApplication.UnicodeUTF8))
        self.actionConcatenate.setText(QtGui.QApplication.translate("mainGuisaxsWindows", "Concatenate", None, QtGui.QApplication.UnicodeUTF8))
        self.actionDerivate.setText(QtGui.QApplication.translate("mainGuisaxsWindows", "Derivate", None, QtGui.QApplication.UnicodeUTF8))
        self.actionSmooth.setText(QtGui.QApplication.translate("mainGuisaxsWindows", "Smooth", None, QtGui.QApplication.UnicodeUTF8))
        self.actionFind_Peaks.setText(QtGui.QApplication.translate("mainGuisaxsWindows", "Find Peaks", None, QtGui.QApplication.UnicodeUTF8))
        self.actionInterpolate.setText(QtGui.QApplication.translate("mainGuisaxsWindows", "Interpolate", None, QtGui.QApplication.UnicodeUTF8))
        self.actionCalculator.setText(QtGui.QApplication.translate("mainGuisaxsWindows", "Calculator", None, QtGui.QApplication.UnicodeUTF8))
        self.actionStatistics.setText(QtGui.QApplication.translate("mainGuisaxsWindows", "Statistics", None, QtGui.QApplication.UnicodeUTF8))
        self.actionGenerate_Noise.setText(QtGui.QApplication.translate("mainGuisaxsWindows", "Generate Noise", None, QtGui.QApplication.UnicodeUTF8))
        self.actionTransmission_and_Background_correction.setText(QtGui.QApplication.translate("mainGuisaxsWindows", "Transmission and Background correction", None, QtGui.QApplication.UnicodeUTF8))
        self.actionCalculate_Resolution_function.setText(QtGui.QApplication.translate("mainGuisaxsWindows", "Calculate Resolution function", None, QtGui.QApplication.UnicodeUTF8))
        self.actionDesmearing.setText(QtGui.QApplication.translate("mainGuisaxsWindows", "Desmearing", None, QtGui.QApplication.UnicodeUTF8))
        self.actionAbsolute_scaling.setText(QtGui.QApplication.translate("mainGuisaxsWindows", "Absolute scaling", None, QtGui.QApplication.UnicodeUTF8))
        self.actionRadial_averaging.setText(QtGui.QApplication.translate("mainGuisaxsWindows", "Radial averaging", None, QtGui.QApplication.UnicodeUTF8))
        self.actionInvariant.setText(QtGui.QApplication.translate("mainGuisaxsWindows", "Invariant", None, QtGui.QApplication.UnicodeUTF8))
        self.actionX_ray_absorption.setText(QtGui.QApplication.translate("mainGuisaxsWindows", "X-ray absorption", None, QtGui.QApplication.UnicodeUTF8))
        self.actionX_ray_absorption_Xraylib.setText(QtGui.QApplication.translate("mainGuisaxsWindows", "X-ray absorption Xraylib", None, QtGui.QApplication.UnicodeUTF8))
        self.actionFind_peaks.setText(QtGui.QApplication.translate("mainGuisaxsWindows", "Find peaks", None, QtGui.QApplication.UnicodeUTF8))
        self.actionChanges.setText(QtGui.QApplication.translate("mainGuisaxsWindows", "Changes", None, QtGui.QApplication.UnicodeUTF8))
        self.actionLicence.setText(QtGui.QApplication.translate("mainGuisaxsWindows", "License", None, QtGui.QApplication.UnicodeUTF8))
        self.actionAbout.setText(QtGui.QApplication.translate("mainGuisaxsWindows", "About", None, QtGui.QApplication.UnicodeUTF8))
        self.actionAppend_Dataset.setText(QtGui.QApplication.translate("mainGuisaxsWindows", "Append a Dataset", None, QtGui.QApplication.UnicodeUTF8))
        self.actionExport.setText(QtGui.QApplication.translate("mainGuisaxsWindows", "Export As text", None, QtGui.QApplication.UnicodeUTF8))
        self.actionAddReferenceValue.setText(QtGui.QApplication.translate("mainGuisaxsWindows", "Add a reference value", None, QtGui.QApplication.UnicodeUTF8))
        self.actionRemove_dependencies.setText(QtGui.QApplication.translate("mainGuisaxsWindows", "Remove dependencies", None, QtGui.QApplication.UnicodeUTF8))
        self.actionTest.setText(QtGui.QApplication.translate("mainGuisaxsWindows", "test", None, QtGui.QApplication.UnicodeUTF8))
        self.actionModels_2.setText(QtGui.QApplication.translate("mainGuisaxsWindows", "Models", None, QtGui.QApplication.UnicodeUTF8))
        self.actionQsdqsd.setText(QtGui.QApplication.translate("mainGuisaxsWindows", "qsdqsd", None, QtGui.QApplication.UnicodeUTF8))
        self.actionBlablqsd.setText(QtGui.QApplication.translate("mainGuisaxsWindows", "blablqsd", None, QtGui.QApplication.UnicodeUTF8))
        self.actionDoc.setText(QtGui.QApplication.translate("mainGuisaxsWindows", "doc", None, QtGui.QApplication.UnicodeUTF8))
        self.actionChange_color.setText(QtGui.QApplication.translate("mainGuisaxsWindows", "Change color", None, QtGui.QApplication.UnicodeUTF8))
        self.actionSet_as_reference.setText(QtGui.QApplication.translate("mainGuisaxsWindows", "Set as reference", None, QtGui.QApplication.UnicodeUTF8))

