# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Qtguiqwt.ui'
#
# Created: Thu Dec 20 10:42:45 2012
#      by: PyQt4 UI code generator 4.9.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    _fromUtf8 = lambda s: s

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName(_fromUtf8("MainWindow"))
        MainWindow.resize(704, 557)
        self.centralwidget = QtGui.QWidget(MainWindow)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.centralwidget.sizePolicy().hasHeightForWidth())
        self.centralwidget.setSizePolicy(sizePolicy)
        self.centralwidget.setObjectName(_fromUtf8("centralwidget"))
        self.gridLayout_2 = QtGui.QGridLayout(self.centralwidget)
        self.gridLayout_2.setObjectName(_fromUtf8("gridLayout_2"))
        self.verticalLayout = QtGui.QVBoxLayout()
        self.verticalLayout.setSpacing(0)
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.curvewidget = CurveWidget(self.centralwidget)
        self.curvewidget.setOrientation(QtCore.Qt.Horizontal)
        self.curvewidget.setObjectName(_fromUtf8("curvewidget"))
        self.verticalLayout.addWidget(self.curvewidget)
        self.gridLayout_2.addLayout(self.verticalLayout, 0, 0, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtGui.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 704, 21))
        self.menubar.setObjectName(_fromUtf8("menubar"))
        self.menuFile = QtGui.QMenu(self.menubar)
        self.menuFile.setObjectName(_fromUtf8("menuFile"))
        self.menuPlot = QtGui.QMenu(self.menubar)
        self.menuPlot.setObjectName(_fromUtf8("menuPlot"))
        self.menuGrid = QtGui.QMenu(self.menuPlot)
        self.menuGrid.setObjectName(_fromUtf8("menuGrid"))
        self.menuAxes = QtGui.QMenu(self.menuPlot)
        self.menuAxes.setObjectName(_fromUtf8("menuAxes"))
        self.menuLegend_and_Title = QtGui.QMenu(self.menuPlot)
        self.menuLegend_and_Title.setObjectName(_fromUtf8("menuLegend_and_Title"))
        self.menuHelp = QtGui.QMenu(self.menubar)
        self.menuHelp.setObjectName(_fromUtf8("menuHelp"))
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtGui.QStatusBar(MainWindow)
        self.statusbar.setObjectName(_fromUtf8("statusbar"))
        MainWindow.setStatusBar(self.statusbar)
        self.actionSave_As = QtGui.QAction(MainWindow)
        self.actionSave_As.setObjectName(_fromUtf8("actionSave_As"))
        self.actionPage_Setup = QtGui.QAction(MainWindow)
        self.actionPage_Setup.setObjectName(_fromUtf8("actionPage_Setup"))
        self.actionPrint = QtGui.QAction(MainWindow)
        self.actionPrint.setObjectName(_fromUtf8("actionPrint"))
        self.actionPrint_Preview = QtGui.QAction(MainWindow)
        self.actionPrint_Preview.setObjectName(_fromUtf8("actionPrint_Preview"))
        self.action_Close = QtGui.QAction(MainWindow)
        self.action_Close.setObjectName(_fromUtf8("action_Close"))
        self.actionGridON = QtGui.QAction(MainWindow)
        self.actionGridON.setCheckable(True)
        self.actionGridON.setChecked(True)
        self.actionGridON.setObjectName(_fromUtf8("actionGridON"))
        self.actionGridOFF = QtGui.QAction(MainWindow)
        self.actionGridOFF.setCheckable(True)
        self.actionGridOFF.setObjectName(_fromUtf8("actionGridOFF"))
        self.actionLine_format = QtGui.QAction(MainWindow)
        self.actionLine_format.setObjectName(_fromUtf8("actionLine_format"))
        self.actionMarker = QtGui.QAction(MainWindow)
        self.actionMarker.setObjectName(_fromUtf8("actionMarker"))
        self.actionY_axes = QtGui.QAction(MainWindow)
        self.actionY_axes.setObjectName(_fromUtf8("actionY_axes"))
        self.actionAutoscale = QtGui.QAction(MainWindow)
        self.actionAutoscale.setCheckable(True)
        self.actionAutoscale.setChecked(True)
        self.actionAutoscale.setObjectName(_fromUtf8("actionAutoscale"))
        self.actionSet_X_range = QtGui.QAction(MainWindow)
        self.actionSet_X_range.setCheckable(True)
        self.actionSet_X_range.setObjectName(_fromUtf8("actionSet_X_range"))
        self.actionSet_Y_range = QtGui.QAction(MainWindow)
        self.actionSet_Y_range.setCheckable(True)
        self.actionSet_Y_range.setObjectName(_fromUtf8("actionSet_Y_range"))
        self.actionXlin_ylin = QtGui.QAction(MainWindow)
        self.actionXlin_ylin.setCheckable(True)
        self.actionXlin_ylin.setObjectName(_fromUtf8("actionXlin_ylin"))
        self.actionXlin_ylog = QtGui.QAction(MainWindow)
        self.actionXlin_ylog.setCheckable(True)
        self.actionXlin_ylog.setObjectName(_fromUtf8("actionXlin_ylog"))
        self.actionXlog_ylin = QtGui.QAction(MainWindow)
        self.actionXlog_ylin.setCheckable(True)
        self.actionXlog_ylin.setObjectName(_fromUtf8("actionXlog_ylin"))
        self.actionXlog_ylog = QtGui.QAction(MainWindow)
        self.actionXlog_ylog.setCheckable(True)
        self.actionXlog_ylog.setObjectName(_fromUtf8("actionXlog_ylog"))
        self.actionAbout = QtGui.QAction(MainWindow)
        self.actionAbout.setObjectName(_fromUtf8("actionAbout"))
        self.actionLegend_ON = QtGui.QAction(MainWindow)
        self.actionLegend_ON.setCheckable(True)
        self.actionLegend_ON.setChecked(True)
        self.actionLegend_ON.setObjectName(_fromUtf8("actionLegend_ON"))
        self.actionLegend_OFF = QtGui.QAction(MainWindow)
        self.actionLegend_OFF.setCheckable(True)
        self.actionLegend_OFF.setObjectName(_fromUtf8("actionLegend_OFF"))
        self.menuFile.addAction(self.actionSave_As)
        self.menuFile.addSeparator()
        self.menuFile.addAction(self.actionPage_Setup)
        self.menuFile.addAction(self.actionPrint)
        self.menuFile.addAction(self.actionPrint_Preview)
        self.menuFile.addSeparator()
        self.menuFile.addAction(self.action_Close)
        self.menuGrid.addAction(self.actionGridON)
        self.menuGrid.addAction(self.actionGridOFF)
        self.menuAxes.addAction(self.actionAutoscale)
        self.menuAxes.addAction(self.actionSet_X_range)
        self.menuAxes.addAction(self.actionSet_Y_range)
        self.menuAxes.addAction(self.actionXlin_ylin)
        self.menuAxes.addAction(self.actionXlin_ylog)
        self.menuAxes.addAction(self.actionXlog_ylin)
        self.menuAxes.addAction(self.actionXlog_ylog)
        self.menuLegend_and_Title.addAction(self.actionLegend_ON)
        self.menuLegend_and_Title.addAction(self.actionLegend_OFF)
        self.menuPlot.addAction(self.menuGrid.menuAction())
        self.menuPlot.addAction(self.menuLegend_and_Title.menuAction())
        self.menuPlot.addAction(self.actionLine_format)
        self.menuPlot.addAction(self.actionMarker)
        self.menuPlot.addAction(self.menuAxes.menuAction())
        self.menuPlot.addAction(self.actionY_axes)
        self.menuHelp.addAction(self.actionAbout)
        self.menubar.addAction(self.menuFile.menuAction())
        self.menubar.addAction(self.menuPlot.menuAction())
        self.menubar.addAction(self.menuHelp.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QObject.connect(self.action_Close, QtCore.SIGNAL(_fromUtf8("triggered()")), MainWindow.close)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(QtGui.QApplication.translate("MainWindow", "MainWindow", None, QtGui.QApplication.UnicodeUTF8))
        self.menuFile.setTitle(QtGui.QApplication.translate("MainWindow", "File", None, QtGui.QApplication.UnicodeUTF8))
        self.menuPlot.setTitle(QtGui.QApplication.translate("MainWindow", "Plot", None, QtGui.QApplication.UnicodeUTF8))
        self.menuGrid.setTitle(QtGui.QApplication.translate("MainWindow", "Grid", None, QtGui.QApplication.UnicodeUTF8))
        self.menuAxes.setTitle(QtGui.QApplication.translate("MainWindow", "Axes", None, QtGui.QApplication.UnicodeUTF8))
        self.menuLegend_and_Title.setTitle(QtGui.QApplication.translate("MainWindow", "Legend and Title", None, QtGui.QApplication.UnicodeUTF8))
        self.menuHelp.setTitle(QtGui.QApplication.translate("MainWindow", "Help", None, QtGui.QApplication.UnicodeUTF8))
        self.actionSave_As.setText(QtGui.QApplication.translate("MainWindow", "&File", None, QtGui.QApplication.UnicodeUTF8))
        self.actionPage_Setup.setText(QtGui.QApplication.translate("MainWindow", "Page Setup", None, QtGui.QApplication.UnicodeUTF8))
        self.actionPrint.setText(QtGui.QApplication.translate("MainWindow", "Print Preview", None, QtGui.QApplication.UnicodeUTF8))
        self.actionPrint_Preview.setText(QtGui.QApplication.translate("MainWindow", "Print", None, QtGui.QApplication.UnicodeUTF8))
        self.action_Close.setText(QtGui.QApplication.translate("MainWindow", "Close", None, QtGui.QApplication.UnicodeUTF8))
        self.actionGridON.setText(QtGui.QApplication.translate("MainWindow", "ON", None, QtGui.QApplication.UnicodeUTF8))
        self.actionGridOFF.setText(QtGui.QApplication.translate("MainWindow", "OFF", None, QtGui.QApplication.UnicodeUTF8))
        self.actionLine_format.setText(QtGui.QApplication.translate("MainWindow", "Line format", None, QtGui.QApplication.UnicodeUTF8))
        self.actionMarker.setText(QtGui.QApplication.translate("MainWindow", "Marker", None, QtGui.QApplication.UnicodeUTF8))
        self.actionY_axes.setText(QtGui.QApplication.translate("MainWindow", "Y axes", None, QtGui.QApplication.UnicodeUTF8))
        self.actionAutoscale.setText(QtGui.QApplication.translate("MainWindow", "Autoscale", None, QtGui.QApplication.UnicodeUTF8))
        self.actionSet_X_range.setText(QtGui.QApplication.translate("MainWindow", "Set X range", None, QtGui.QApplication.UnicodeUTF8))
        self.actionSet_Y_range.setText(QtGui.QApplication.translate("MainWindow", "Set Y range", None, QtGui.QApplication.UnicodeUTF8))
        self.actionXlin_ylin.setText(QtGui.QApplication.translate("MainWindow", "xlin - ylin", None, QtGui.QApplication.UnicodeUTF8))
        self.actionXlin_ylog.setText(QtGui.QApplication.translate("MainWindow", "xlin - ylog", None, QtGui.QApplication.UnicodeUTF8))
        self.actionXlog_ylin.setText(QtGui.QApplication.translate("MainWindow", "xlog - ylin", None, QtGui.QApplication.UnicodeUTF8))
        self.actionXlog_ylog.setText(QtGui.QApplication.translate("MainWindow", "xlog - ylog", None, QtGui.QApplication.UnicodeUTF8))
        self.actionAbout.setText(QtGui.QApplication.translate("MainWindow", "About", None, QtGui.QApplication.UnicodeUTF8))
        self.actionLegend_ON.setText(QtGui.QApplication.translate("MainWindow", "Legend ON", None, QtGui.QApplication.UnicodeUTF8))
        self.actionLegend_OFF.setText(QtGui.QApplication.translate("MainWindow", "Legend OFF", None, QtGui.QApplication.UnicodeUTF8))

from guiqwt.plot import CurveWidget

if __name__ == "__main__":
    import sys
    app = QtGui.QApplication(sys.argv)
    MainWindow = QtGui.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())

