# coding: utf-8

"""
    COIN CRDB Rest API

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)

    OpenAPI spec version: 1.0.0
    Contact: servicedesk@coin.nl
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from pprint import pformat
from six import iteritems
import re


class EnumActivationRangeBody(object):
    """
    NOTE: This class is auto generated by the swagger code generator program.
    Do not edit the class manually.
    """


    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'enumactivationrange': 'EnumContent'
    }

    attribute_map = {
        'enumactivationrange': 'enumactivationrange'
    }

    def __init__(self, enumactivationrange=None):
        """
        EnumActivationRangeBody - a model defined in Swagger
        """

        self._enumactivationrange = None

        self.enumactivationrange = enumactivationrange

    @property
    def enumactivationrange(self):
        """
        Gets the enumactivationrange of this EnumActivationRangeBody.

        :return: The enumactivationrange of this EnumActivationRangeBody.
        :rtype: EnumContent
        """
        return self._enumactivationrange

    @enumactivationrange.setter
    def enumactivationrange(self, enumactivationrange):
        """
        Sets the enumactivationrange of this EnumActivationRangeBody.

        :param enumactivationrange: The enumactivationrange of this EnumActivationRangeBody.
        :type: EnumContent
        """
        if enumactivationrange is None:
            raise ValueError("Invalid value for `enumactivationrange`, must not be `None`")

        self._enumactivationrange = enumactivationrange

    def to_dict(self):
        """
        Returns the model properties as a dict
        """
        result = {}

        for attr, _ in iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value

        return result

    def to_str(self):
        """
        Returns the string representation of the model
        """
        return pformat(self.to_dict())

    def __repr__(self):
        """
        For `print` and `pprint`
        """
        return self.to_str()

    def __eq__(self, other):
        """
        Returns true if both objects are equal
        """
        if not isinstance(other, EnumActivationRangeBody):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """
        Returns true if both objects are not equal
        """
        return not self == other
