
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2021-01-27T18:01:36-0500",
 "dirty": false,
 "error": null,
 "full-revisionid": "ca5948fbc83c78cc1663e48d4cbf353b7d9c5740",
 "version": "1.9.0"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
