
# This file was generated by 'versioneer.py' (0.18.2) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2021-02-01T16:08:25+0000",
 "dirty": false,
 "error": null,
 "full-revisionid": "ee06402ab383c7c34632b87e5ecc297c86e3e97a",
 "version": "0.7.2"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
