
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2021-01-29T16:56:33-0800",
 "dirty": false,
 "error": null,
 "full-revisionid": "b9e5ad204acad29f79c7a97e9a148df36f3ae1f4",
 "version": "0.0.1"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
