__title__ = "basically-ti-basic"
__description__ = "Package to decompile and recompile .8Xp files from the TI-83/TI-84 calculators."
__url__ = "https://github.com/TabulateJarl8/basically-ti-basic"
__version__ = "0.1.4"
__author__ = "Tabulate"
__author_email__ = "tabulatejarl8@gmail.com"
__license__ = "MIT"
__copyright__ = "Copyright 2021 Connor Sample"
