
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2021-01-29T23:22:11+0100",
 "dirty": false,
 "error": null,
 "full-revisionid": "a2d76a4df667a2f16751b56868604c9b0f14aa25",
 "version": "0.0.2"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
