
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2021-01-27T22:09:23+0000",
 "dirty": false,
 "error": null,
 "full-revisionid": "4163f9a87dfef35332180e4f4987acdc1746cabe",
 "version": "0.8.248"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
