# Generated by Django 2.2.1 on 2019-05-30 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0042_auto_20190530_1159'),
    ]

    operations = [
        migrations.AlterField(
            model_name='operations',
            name='start',
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
    ]
