# Generated by Django 2.2.6 on 2019-10-08 16:38

from django.db import migrations
import django.db.models.deletion
import isc_common.fields.related


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0071_auto_20191008_1307'),
    ]

    operations = [
        migrations.AlterField(
            model_name='operation_material',
            name='operationitem',
            field=isc_common.fields.related.ForeignKeyCascade(on_delete=django.db.models.deletion.CASCADE, to='production.Operations_item'),
        ),
        migrations.AlterField(
            model_name='operation_resources',
            name='operationitem',
            field=isc_common.fields.related.ForeignKeyCascade(on_delete=django.db.models.deletion.CASCADE, to='production.Operations_item'),
        ),
    ]
