# Generated by Django 2.2.7 on 2019-11-17 15:27

import bitfield.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0093_delete_launch_item_refs'),
    ]

    operations = [
        migrations.AddField(
            model_name='status_launch',
            name='props',
            field=bitfield.models.BitField(('disabled', 'Неактивная запись в гриде'), db_index=True, default=0),
        ),
    ]
