# Generated by Django 2.2.8 on 2019-12-04 14:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0139_location_loading_resource_loading'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='resource_loading',
            name='launch_operations_item',
        ),
        migrations.RemoveField(
            model_name='resource_loading',
            name='resource',
        ),
        migrations.DeleteModel(
            name='Location_loading',
        ),
        migrations.DeleteModel(
            name='Resource_loading',
        ),
    ]
