# Generated by Django 3.0.3 on 2020-02-15 18:54
from django.db import migrations
from isc_common.fields.code_field import JSONFieldIVC


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0179_remove_launches_props'),
    ]

    operations = [
        migrations.AddField(
            model_name='ready_2_launch_detail',
            name='json',
            field=JSONFieldIVC(),
        ),
    ]
