# Generated by Django 3.0.3 on 2020-02-16 05:18


from django.db import migrations
from isc_common.fields.code_field import JSONFieldIVC


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0182_auto_20200215_1930'),
    ]

    operations = [
        migrations.AddField(
            model_name='ready_2_launch_detail',
            name='item_full_name_obj',
            field=JSONFieldIVC(),
        ),
    ]
