# Generated by Django 3.0.3 on 2020-02-22 16:08

import bitfield.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0197_auto_20200222_1149'),
    ]

    operations = [
        migrations.AlterField(
            model_name='operations',
            name='props',
            field=bitfield.models.BitField((('made_common_form', 'Формировать общий документ по комплектяции'),), db_index=True, default=0),
        ),
    ]
