# Generated by Django 3.0.3 on 2020-02-22 17:54

import bitfield.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0198_auto_20200222_1608'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ready_2_launch',
            name='props',
            field=bitfield.models.BitField((('check_qty', 'Проверять длительность'), ('check_num', 'Проверять № п/п'), ('check_material', 'Проверять материалы'), ('check_resources', 'Проверять ресурсы'), ('check_edizm', 'Проверять еденицу измерения'), ('check_operation', 'Проверять операцию'), ('check_colvo', 'Проверять количество')), db_index=True, default=0),
        ),
    ]
