# Generated by Django 3.0.3 on 2020-02-23 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0202_auto_20200223_1222'),
    ]

    operations = [
        migrations.AddField(
            model_name='launch_item_refs',
            name='qty',
            field=models.DecimalField(decimal_places=4, default=0.0, max_digits=19),
        ),
    ]
