# Generated by Django 3.0.7 on 2020-06-15 03:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0233_auto_20200609_1920'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='launch_operations_material',
            name='edizm',
        ),
        migrations.RemoveField(
            model_name='launch_operations_material',
            name='material',
        ),
        migrations.RemoveField(
            model_name='launch_operations_material',
            name='material_askon',
        ),
        migrations.RemoveField(
            model_name='launch_operations_material',
            name='qty',
        ),
    ]
