# Generated by Django 3.0.7 on 2020-06-23 06:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ckk', '0228_auto_20200623_0550'),
        ('production', '0250_auto_20200623_0614'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='launch_operations_item',
            unique_together={('item', 'launch', 'operation', 'num', 'props')},
        ),
    ]
