# Generated by Django 3.0.7 on 2020-06-23 07:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0252_launch_item_add'),
    ]

    operations = [
        migrations.RenameField(
            model_name='launch_item_add',
            old_name='ed_izm',
            new_name='edizm',
        ),
    ]
