# Generated by Django 3.0.7 on 2020-06-24 15:11

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import isc_common.fields.related


class Migration(migrations.Migration):

    dependencies = [
        ('ckk', '0228_auto_20200623_0550'),
        ('production', '0256_auto_20200624_1412'),
    ]

    operations = [
        migrations.CreateModel(
            name='Launch_operation_attr',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False, verbose_name='Идентификатор')),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='Дата мягкого удаления')),
                ('editing', models.BooleanField(default=True, verbose_name='Возможность редактирования')),
                ('deliting', models.BooleanField(default=True, verbose_name='Возможность удаления')),
                ('lastmodified', models.DateTimeField(db_index=True, default=django.utils.timezone.now, editable=False, verbose_name='Последнее обновление')),
                ('attr_type', isc_common.fields.related.ForeignKeyProtect(on_delete=django.db.models.deletion.PROTECT, to='ckk.Attr_type')),
                ('launch_operationitem', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='production.Launch_operations_item')),
            ],
            options={
                'verbose_name': 'Кросс таблица',
                'unique_together': {('launch_operationitem', 'attr_type')},
            },
        ),
    ]
