# Generated by Django 3.0.7 on 2020-06-26 10:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0258_auto_20200626_0941'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='launches',
            name='priority',
        ),
    ]
