# Generated by Django 3.0.8 on 2020-07-12 03:28

import bitfield.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0273_auto_20200711_0957'),
    ]

    operations = [
        migrations.AlterField(
            model_name='launch_item_refs',
            name='props',
            field=bitfield.models.BitField((('used', 'Доступность в данной производственной спецификации'), ('changed', 'Доступность в данной производственной спецификации')), db_index=True, default=1),
        ),
    ]
