# Generated by Django 3.0.8 on 2020-07-12 04:11

from django.db import migrations
import django.db.models.deletion
import isc_common.fields.related


class Migration(migrations.Migration):

    dependencies = [
        ('ckk', '0230_auto_20200708_1517'),
        ('production', '0274_auto_20200712_0328'),
    ]

    operations = [
        migrations.AlterField(
            model_name='launch_item_refs',
            name='item_refs',
            field=isc_common.fields.related.ForeignKeyProtect(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='ckk.Item_refs'),
        ),
    ]
