# Generated by Django 3.0.8 on 2020-07-12 06:10

import bitfield.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0276_auto_20200712_0537'),
    ]

    operations = [
        migrations.AddField(
            model_name='launch_operations_item',
            name='props',
            field=bitfield.models.BitField((('added', 'Операция добавлена'), ('edited', 'Операция изменена')), db_index=True, default=0),
        ),
        migrations.AddField(
            model_name='operations_item',
            name='props',
            field=bitfield.models.BitField((('added', 'Операция добавлена'), ('edited', 'Операция изменена')), db_index=True, default=0),
        ),
    ]
