# Generated by Django 3.0.8 on 2020-07-12 06:14

import bitfield.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0277_auto_20200712_0610'),
    ]

    operations = [
        migrations.AlterField(
            model_name='launch_operations_item',
            name='props',
            field=bitfield.models.BitField((('created', 'Операция добавлена'), ('updated', 'Операция изменена')), db_index=True, default=0),
        ),
        migrations.AlterField(
            model_name='operations_item',
            name='props',
            field=bitfield.models.BitField((('created', 'Операция добавлена'), ('updated', 'Операция изменена')), db_index=True, default=0),
        ),
    ]
