# Generated by Django 3.0.8 on 2020-07-27 06:34

from django.db import migrations
import django.db.models.deletion
import isc_common.fields.related


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0137_demand_date_sign'),
        ('ckk', '0241_delete_standard_colors_view'),
        ('production', '0290_auto_20200725_1110'),
    ]

    operations = [
        migrations.AddField(
            model_name='ready_2_launch',
            name='item',
            field=isc_common.fields.related.ForeignKeyCascade(default=None, on_delete=django.db.models.deletion.CASCADE, to='ckk.Item'),
        ),
        migrations.AlterField(
            model_name='ready_2_launch',
            name='demand',
            field=isc_common.fields.related.ForeignKeyCascade(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='sales.Demand'),
        ),
    ]
