# Generated by Django 3.0.8 on 2020-08-01 08:22

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('production', '0298_operation_executor'),
    ]

    operations = [
        migrations.RenameField(
            model_name='operation_executor',
            old_name='executor',
            new_name='user',
        ),
        migrations.AlterUniqueTogether(
            name='operation_executor',
            unique_together={('operation', 'user')},
        ),
    ]
