# Generated by Django 3.1 on 2020-08-07 04:43

import bitfield.models
from django.db import migrations
import isc_common.fields.code_field


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0306_auto_20200807_0017'),
    ]

    operations = [
        migrations.AlterField(
            model_name='launches',
            name='code',
            field=isc_common.fields.code_field.CodeStrictField(unique=True),
        ),
        migrations.AlterField(
            model_name='operations',
            name='props',
            field=bitfield.models.BitField((('partition_to_launch', 'Суммы разделять по запускам'), ('made_common_form', 'Формировать общий документ'), ('transportation', 'Операция транспортировки'), ('absorption', 'Операция поглощения')), db_index=True, default=0),
        ),
    ]
