# Generated by Django 3.1 on 2020-08-16 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0313_auto_20200813_1443'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='launch_operations_item',
            unique_together=set(),
        ),
        migrations.AddConstraint(
            model_name='launch_operations_item',
            constraint=models.UniqueConstraint(condition=models.Q(operationitem=None), fields=('item', 'launch', 'operation'), name='Launch_operations_item_unique_constraint_0'),
        ),
        migrations.AddConstraint(
            model_name='launch_operations_item',
            constraint=models.UniqueConstraint(fields=('item', 'launch', 'operation', 'operationitem'), name='Launch_operations_item_unique_constraint_1'),
        ),
    ]
