# Generated by Django 3.1.2 on 2020-10-06 07:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0319_launch_detail'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='operations_ext_view',
            table='production_operations_ext_view',
        ),
    ]
