# Generated by Django 3.1.4 on 2020-12-04 07:03

from django.db import migrations
import django.db.models.deletion
import isc_common.fields.related


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0321_auto_20201120_0956'),
    ]

    operations = [
        migrations.AlterField(
            model_name='operations_item',
            name='operation',
            field=isc_common.fields.related.ForeignKeyCascade(on_delete=django.db.models.deletion.CASCADE, to='production.operations'),
        ),
    ]
