# Generated by Django 2.2.1 on 2019-05-16 15:48

from django.db import migrations
import isc_common.fields.code_field


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0005_auto_20190516_1542'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='inn',
            field=isc_common.fields.code_field.CodeField(blank=True, null=True, verbose_name='ИНН'),
        ),
    ]
