# Generated by Django 2.2.1 on 2019-05-17 12:38

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import isc_common.fields.code_field
import isc_common.fields.description_field
import isc_common.fields.related


class Migration(migrations.Migration):

    dependencies = [
        ('ckk', '0044_auto_20190516_2322'),
        ('sales', '0009_precent_parent'),
    ]

    operations = [
        migrations.CreateModel(
            name='Demand',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False, verbose_name='Идентификатор')),
                ('id_old', models.BigIntegerField(blank=True, null=True, verbose_name='Идентификатор старый')),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='Дата мягкого удаления')),
                ('editing', models.BooleanField(default=True, verbose_name='Возможность редактирования')),
                ('deliting', models.BooleanField(default=True, verbose_name='Возможность удаления')),
                ('lastmodified', models.DateTimeField(db_index=True, default=django.utils.timezone.now, editable=False, verbose_name='Последнее обновление')),
                ('code', isc_common.fields.code_field.CodeField()),
                ('description', isc_common.fields.description_field.DescriptionField()),
                ('quantity', models.PositiveIntegerField(verbose_name='Количество')),
                ('priority', models.PositiveIntegerField(blank=True, null=True, verbose_name='Приоритет')),
                ('minshipment', models.PositiveIntegerField(blank=True, null=True, verbose_name='Минимальная отгрузка')),
                ('maxlateness', models.PositiveIntegerField(blank=True, null=True, verbose_name='Максимальная задержка')),
                ('deliverydate', models.DateTimeField(blank=True, null=True, verbose_name='Дата поставки')),
                ('customer', isc_common.fields.related.ForeignKeyProtect(on_delete=django.db.models.deletion.PROTECT, to='sales.Customer')),
                ('item', isc_common.fields.related.ForeignKeyProtect(on_delete=django.db.models.deletion.PROTECT, to='ckk.Item')),
                ('parent', isc_common.fields.related.ForeignKeyProtect(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='sales.Demand')),
                ('status', isc_common.fields.related.ForeignKeyProtect(default=None, on_delete=django.db.models.deletion.PROTECT, to='ckk.Status')),
            ],
            options={
                'verbose_name': 'Заказы на продажу',
            },
        ),
    ]
