# Generated by Django 2.2.1 on 2019-05-24 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0034_demand_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='demand',
            name='date',
            field=models.DateTimeField(db_index=True, default=None, verbose_name='Дата'),
        ),
    ]
