# Generated by Django 2.2.6 on 2019-10-21 20:58

import django.db.models.deletion
from django.db import migrations

import isc_common.fields.related


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0072_auto_20191021_1715'),
    ]

    operations = [
        migrations.AlterField(
            model_name='precent_items',
            name='precent',
            field=isc_common.fields.related.ForeignKeyProtect(on_delete=django.db.models.deletion.PROTECT, to='sales.Precent_dogovors'),
        ),
        migrations.AlterField(
            model_name='precent_materials',
            name='precent',
            field=isc_common.fields.related.ForeignKeyProtect(on_delete=django.db.models.deletion.PROTECT, to='sales.Precent_dogovors'),
        ),
    ]
