# Generated by Django 3.0.2 on 2020-01-21 07:42

from django.db import migrations
import django.db.models.deletion
import isc_common.fields.related


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0123_auto_20191202_1254'),
    ]

    operations = [
        migrations.AlterField(
            model_name='precent_materials',
            name='precent_item',
            field=isc_common.fields.related.ForeignKeyCascade(on_delete=django.db.models.deletion.CASCADE, to='sales.Precent_items'),
        ),
    ]
