# Generated by Django 3.0.2 on 2020-01-21 07:43

from django.db import migrations
import django.db.models.deletion
import isc_common.fields.related


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0124_auto_20200121_0742'),
    ]

    operations = [
        migrations.AlterField(
            model_name='precent_items',
            name='precent_dogovor',
            field=isc_common.fields.related.ForeignKeyCascade(on_delete=django.db.models.deletion.CASCADE, to='sales.Precent_dogovors'),
        ),
    ]
