# Generated by Django 3.0.2 on 2020-01-21 10:48

from django.db import migrations
import django.db.models.deletion
import isc_common.fields.related


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0127_auto_20200121_1047'),
    ]

    operations = [
        migrations.AlterField(
            model_name='demand',
            name='precent',
            field=isc_common.fields.related.ForeignKeyCascade(on_delete=django.db.models.deletion.CASCADE, to='sales.Precent'),
        ),
    ]
