# Generated by Django 3.1 on 2020-08-18 14:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0137_demand_date_sign'),
    ]

    operations = [
        migrations.RenameField(
            model_name='demand_materials',
            old_name='edizm',
            new_name='edi_zm',
        ),
    ]
