# Generated by Django 3.1 on 2020-08-18 14:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0138_auto_20200818_1453'),
    ]

    operations = [
        migrations.RenameField(
            model_name='demand_materials',
            old_name='edi_zm',
            new_name='edizm',
        ),
    ]
