# Generated by Django 3.1 on 2020-08-18 15:20

from django.db import migrations
import django.db.models.deletion
import isc_common.fields.related


class Migration(migrations.Migration):

    dependencies = [
        ('ckk', '0247_auto_20200803_1529'),
        ('sales', '0139_auto_20200818_1455'),
    ]

    operations = [
        migrations.AlterField(
            model_name='demand_materials',
            name='edizm',
            field=isc_common.fields.related.ForeignKeyProtect(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='ckk.ed_izm'),
        ),
    ]
