# Generated by Django 3.1 on 2020-08-18 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0145_auto_20200818_1531'),
    ]

    operations = [
        migrations.AlterField(
            model_name='demand',
            name='qty',
            field=models.DecimalField(decimal_places=4, max_digits=19),
        ),
        migrations.AlterField(
            model_name='demand',
            name='qty_for_launch',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=19, null=True),
        ),
    ]
