
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2021-02-04T17:02:03+0000",
 "dirty": false,
 "error": null,
 "full-revisionid": "f1376d26f298ec23b55da68c597f14a6c30c90f4",
 "version": "0.4.2"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
