# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'dlgAbsorption.ui'
#
# Created: Mon Apr 08 09:51:57 2013
#      by: PyQt4 UI code generator 4.9.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    _fromUtf8 = lambda s: s

class Ui_absorption(object):
    def setupUi(self, absorption):
        absorption.setObjectName(_fromUtf8("absorption"))
        absorption.resize(548, 663)
        absorption.setMaximumSize(QtCore.QSize(16777215, 663))
        self.verticalLayout = QtGui.QVBoxLayout(absorption)
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.groupBoxEnergy = QtGui.QGroupBox(absorption)
        self.groupBoxEnergy.setMaximumSize(QtCore.QSize(16777215, 150))
        self.groupBoxEnergy.setFlat(True)
        self.groupBoxEnergy.setObjectName(_fromUtf8("groupBoxEnergy"))
        self.verticalLayout_2 = QtGui.QVBoxLayout(self.groupBoxEnergy)
        self.verticalLayout_2.setObjectName(_fromUtf8("verticalLayout_2"))
        self.gridLayout = QtGui.QGridLayout()
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.lineEnergy = QtGui.QLineEdit(self.groupBoxEnergy)
        self.lineEnergy.setObjectName(_fromUtf8("lineEnergy"))
        self.gridLayout.addWidget(self.lineEnergy, 0, 1, 1, 1)
        self.label_2 = QtGui.QLabel(self.groupBoxEnergy)
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.gridLayout.addWidget(self.label_2, 0, 2, 1, 1)
        self.label = QtGui.QLabel(self.groupBoxEnergy)
        self.label.setObjectName(_fromUtf8("label"))
        self.gridLayout.addWidget(self.label, 0, 0, 1, 1)
        self.lineLambda = QtGui.QLineEdit(self.groupBoxEnergy)
        self.lineLambda.setEnabled(False)
        self.lineLambda.setObjectName(_fromUtf8("lineLambda"))
        self.gridLayout.addWidget(self.lineLambda, 0, 3, 1, 1)
        self.verticalLayout_2.addLayout(self.gridLayout)
        self.gridXraySources = QtGui.QGridLayout()
        self.gridXraySources.setObjectName(_fromUtf8("gridXraySources"))
        self.label_3 = QtGui.QLabel(self.groupBoxEnergy)
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.gridXraySources.addWidget(self.label_3, 0, 0, 1, 1)
        self.verticalLayout_2.addLayout(self.gridXraySources)
        self.verticalLayout.addWidget(self.groupBoxEnergy)
        self.groupBoxTable = QtGui.QGroupBox(absorption)
        self.groupBoxTable.setMinimumSize(QtCore.QSize(0, 250))
        self.groupBoxTable.setMaximumSize(QtCore.QSize(600, 16777215))
        self.groupBoxTable.setAutoFillBackground(True)
        self.groupBoxTable.setFlat(True)
        self.groupBoxTable.setObjectName(_fromUtf8("groupBoxTable"))
        self.gridLayout_4 = QtGui.QGridLayout(self.groupBoxTable)
        self.gridLayout_4.setMargin(0)
        self.gridLayout_4.setSpacing(0)
        self.gridLayout_4.setObjectName(_fromUtf8("gridLayout_4"))
        self.gridMendeleiev = QtGui.QGridLayout()
        self.gridMendeleiev.setSpacing(1)
        self.gridMendeleiev.setObjectName(_fromUtf8("gridMendeleiev"))
        self.gridLayout_4.addLayout(self.gridMendeleiev, 0, 0, 1, 1)
        self.verticalLayout.addWidget(self.groupBoxTable)
        self.groupBox_3 = QtGui.QGroupBox(absorption)
        self.groupBox_3.setFlat(True)
        self.groupBox_3.setObjectName(_fromUtf8("groupBox_3"))
        self.gridLayout_3 = QtGui.QGridLayout(self.groupBox_3)
        self.gridLayout_3.setContentsMargins(-1, 0, -1, 0)
        self.gridLayout_3.setObjectName(_fromUtf8("gridLayout_3"))
        self.gridLayout_2 = QtGui.QGridLayout()
        self.gridLayout_2.setObjectName(_fromUtf8("gridLayout_2"))
        self.lineNumberOfAtoms = QtGui.QLineEdit(self.groupBox_3)
        self.lineNumberOfAtoms.setMaximumSize(QtCore.QSize(30, 16777215))
        self.lineNumberOfAtoms.setObjectName(_fromUtf8("lineNumberOfAtoms"))
        self.gridLayout_2.addWidget(self.lineNumberOfAtoms, 0, 1, 1, 1)
        self.btnAdd = QtGui.QPushButton(self.groupBox_3)
        self.btnAdd.setObjectName(_fromUtf8("btnAdd"))
        self.gridLayout_2.addWidget(self.btnAdd, 0, 2, 1, 1)
        self.label_9 = QtGui.QLabel(self.groupBox_3)
        self.label_9.setObjectName(_fromUtf8("label_9"))
        self.gridLayout_2.addWidget(self.label_9, 0, 0, 1, 1)
        self.btnRemove = QtGui.QPushButton(self.groupBox_3)
        self.btnRemove.setObjectName(_fromUtf8("btnRemove"))
        self.gridLayout_2.addWidget(self.btnRemove, 0, 3, 1, 1)
        self.btnRemoveAll = QtGui.QPushButton(self.groupBox_3)
        self.btnRemoveAll.setObjectName(_fromUtf8("btnRemoveAll"))
        self.gridLayout_2.addWidget(self.btnRemoveAll, 0, 4, 1, 1)
        self.gridLayout_3.addLayout(self.gridLayout_2, 2, 0, 1, 2)
        self.formLayout_2 = QtGui.QFormLayout()
        self.formLayout_2.setFieldGrowthPolicy(QtGui.QFormLayout.AllNonFixedFieldsGrow)
        self.formLayout_2.setObjectName(_fromUtf8("formLayout_2"))
        self.label_7 = QtGui.QLabel(self.groupBox_3)
        self.label_7.setObjectName(_fromUtf8("label_7"))
        self.formLayout_2.setWidget(0, QtGui.QFormLayout.LabelRole, self.label_7)
        self.lineElementAtomicWeight = QtGui.QLineEdit(self.groupBox_3)
        self.lineElementAtomicWeight.setEnabled(False)
        self.lineElementAtomicWeight.setMaximumSize(QtCore.QSize(100, 16777215))
        self.lineElementAtomicWeight.setObjectName(_fromUtf8("lineElementAtomicWeight"))
        self.formLayout_2.setWidget(0, QtGui.QFormLayout.FieldRole, self.lineElementAtomicWeight)
        self.label_8 = QtGui.QLabel(self.groupBox_3)
        self.label_8.setObjectName(_fromUtf8("label_8"))
        self.formLayout_2.setWidget(1, QtGui.QFormLayout.LabelRole, self.label_8)
        self.lineElementMuRho = QtGui.QLineEdit(self.groupBox_3)
        self.lineElementMuRho.setEnabled(False)
        self.lineElementMuRho.setMinimumSize(QtCore.QSize(0, 15))
        self.lineElementMuRho.setMaximumSize(QtCore.QSize(100, 16777215))
        self.lineElementMuRho.setObjectName(_fromUtf8("lineElementMuRho"))
        self.formLayout_2.setWidget(1, QtGui.QFormLayout.FieldRole, self.lineElementMuRho)
        self.gridLayout_3.addLayout(self.formLayout_2, 0, 1, 2, 1)
        self.widget = QtGui.QWidget(self.groupBox_3)
        self.widget.setMinimumSize(QtCore.QSize(100, 70))
        self.widget.setObjectName(_fromUtf8("widget"))
        self.ElementSymbol = QtGui.QLabel(self.widget)
        self.ElementSymbol.setGeometry(QtCore.QRect(30, 20, 47, 33))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.ElementSymbol.setFont(font)
        self.ElementSymbol.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.ElementSymbol.setObjectName(_fromUtf8("ElementSymbol"))
        self.ElementAtomicNumber = QtGui.QLabel(self.widget)
        self.ElementAtomicNumber.setGeometry(QtCore.QRect(10, 40, 20, 24))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.ElementAtomicNumber.setFont(font)
        self.ElementAtomicNumber.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.ElementAtomicNumber.setObjectName(_fromUtf8("ElementAtomicNumber"))
        self.ElementName = QtGui.QLabel(self.widget)
        self.ElementName.setGeometry(QtCore.QRect(20, 0, 71, 25))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.ElementName.setFont(font)
        self.ElementName.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.ElementName.setObjectName(_fromUtf8("ElementName"))
        self.gridLayout_3.addWidget(self.widget, 1, 0, 1, 1)
        self.verticalLayout.addWidget(self.groupBox_3)
        self.groupBox_4 = QtGui.QGroupBox(absorption)
        self.groupBox_4.setFlat(True)
        self.groupBox_4.setObjectName(_fromUtf8("groupBox_4"))
        self.horizontalLayout = QtGui.QHBoxLayout(self.groupBox_4)
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.formLayout_3 = QtGui.QFormLayout()
        self.formLayout_3.setLabelAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.formLayout_3.setObjectName(_fromUtf8("formLayout_3"))
        self.label_10 = QtGui.QLabel(self.groupBox_4)
        self.label_10.setObjectName(_fromUtf8("label_10"))
        self.formLayout_3.setWidget(0, QtGui.QFormLayout.LabelRole, self.label_10)
        self.label_11 = QtGui.QLabel(self.groupBox_4)
        self.label_11.setObjectName(_fromUtf8("label_11"))
        self.formLayout_3.setWidget(1, QtGui.QFormLayout.LabelRole, self.label_11)
        self.label_12 = QtGui.QLabel(self.groupBox_4)
        self.label_12.setObjectName(_fromUtf8("label_12"))
        self.formLayout_3.setWidget(2, QtGui.QFormLayout.LabelRole, self.label_12)
        self.label_13 = QtGui.QLabel(self.groupBox_4)
        self.label_13.setObjectName(_fromUtf8("label_13"))
        self.formLayout_3.setWidget(3, QtGui.QFormLayout.LabelRole, self.label_13)
        self.lineActiveFormula = QtGui.QLineEdit(self.groupBox_4)
        self.lineActiveFormula.setEnabled(False)
        self.lineActiveFormula.setObjectName(_fromUtf8("lineActiveFormula"))
        self.formLayout_3.setWidget(0, QtGui.QFormLayout.FieldRole, self.lineActiveFormula)
        self.lineCompoundMuRho = QtGui.QLineEdit(self.groupBox_4)
        self.lineCompoundMuRho.setEnabled(True)
        self.lineCompoundMuRho.setObjectName(_fromUtf8("lineCompoundMuRho"))
        self.formLayout_3.setWidget(1, QtGui.QFormLayout.FieldRole, self.lineCompoundMuRho)
        self.lineDensity = QtGui.QLineEdit(self.groupBox_4)
        self.lineDensity.setObjectName(_fromUtf8("lineDensity"))
        self.formLayout_3.setWidget(2, QtGui.QFormLayout.FieldRole, self.lineDensity)
        self.lineElectronicDensity = QtGui.QLineEdit(self.groupBox_4)
        self.lineElectronicDensity.setEnabled(True)
        self.lineElectronicDensity.setObjectName(_fromUtf8("lineElectronicDensity"))
        self.formLayout_3.setWidget(3, QtGui.QFormLayout.FieldRole, self.lineElectronicDensity)
        self.horizontalLayout.addLayout(self.formLayout_3)
        self.formLayout_4 = QtGui.QFormLayout()
        self.formLayout_4.setFieldGrowthPolicy(QtGui.QFormLayout.AllNonFixedFieldsGrow)
        self.formLayout_4.setLabelAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.formLayout_4.setObjectName(_fromUtf8("formLayout_4"))
        self.label_14 = QtGui.QLabel(self.groupBox_4)
        self.label_14.setObjectName(_fromUtf8("label_14"))
        self.formLayout_4.setWidget(0, QtGui.QFormLayout.LabelRole, self.label_14)
        self.lineScatteringLengthDensity = QtGui.QLineEdit(self.groupBox_4)
        self.lineScatteringLengthDensity.setEnabled(True)
        self.lineScatteringLengthDensity.setObjectName(_fromUtf8("lineScatteringLengthDensity"))
        self.formLayout_4.setWidget(0, QtGui.QFormLayout.FieldRole, self.lineScatteringLengthDensity)
        self.label_15 = QtGui.QLabel(self.groupBox_4)
        self.label_15.setObjectName(_fromUtf8("label_15"))
        self.formLayout_4.setWidget(1, QtGui.QFormLayout.LabelRole, self.label_15)
        self.lineThickness = QtGui.QLineEdit(self.groupBox_4)
        self.lineThickness.setObjectName(_fromUtf8("lineThickness"))
        self.formLayout_4.setWidget(1, QtGui.QFormLayout.FieldRole, self.lineThickness)
        self.label_16 = QtGui.QLabel(self.groupBox_4)
        self.label_16.setObjectName(_fromUtf8("label_16"))
        self.formLayout_4.setWidget(2, QtGui.QFormLayout.LabelRole, self.label_16)
        self.lineXRayTransmission = QtGui.QLineEdit(self.groupBox_4)
        self.lineXRayTransmission.setEnabled(True)
        self.lineXRayTransmission.setObjectName(_fromUtf8("lineXRayTransmission"))
        self.formLayout_4.setWidget(2, QtGui.QFormLayout.FieldRole, self.lineXRayTransmission)
        self.horizontalLayout.addLayout(self.formLayout_4)
        self.verticalLayout.addWidget(self.groupBox_4)
        self.labelLib = QtGui.QLabel(absorption)
        self.labelLib.setTextFormat(QtCore.Qt.AutoText)
        self.labelLib.setObjectName(_fromUtf8("labelLib"))
        self.verticalLayout.addWidget(self.labelLib)
        self.buttonBox = QtGui.QDialogButtonBox(absorption)
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtGui.QDialogButtonBox.Cancel|QtGui.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName(_fromUtf8("buttonBox"))
        self.verticalLayout.addWidget(self.buttonBox)

        self.retranslateUi(absorption)
        QtCore.QObject.connect(self.buttonBox, QtCore.SIGNAL(_fromUtf8("accepted()")), absorption.accept)
        QtCore.QObject.connect(self.buttonBox, QtCore.SIGNAL(_fromUtf8("rejected()")), absorption.reject)
        QtCore.QMetaObject.connectSlotsByName(absorption)

    def retranslateUi(self, absorption):
        absorption.setWindowTitle(QtGui.QApplication.translate("absorption", "X-Rays absorption tool", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBoxEnergy.setTitle(QtGui.QApplication.translate("absorption", "Energy :", None, QtGui.QApplication.UnicodeUTF8))
        self.label_2.setText(QtGui.QApplication.translate("absorption", "lambda (Angstrom) =", None, QtGui.QApplication.UnicodeUTF8))
        self.label.setText(QtGui.QApplication.translate("absorption", "Energy (keV) :", None, QtGui.QApplication.UnicodeUTF8))
        self.label_3.setText(QtGui.QApplication.translate("absorption", "Common X-ray Sources :", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBoxTable.setTitle(QtGui.QApplication.translate("absorption", "Click to select atoms :", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox_3.setTitle(QtGui.QApplication.translate("absorption", "Element :", None, QtGui.QApplication.UnicodeUTF8))
        self.btnAdd.setText(QtGui.QApplication.translate("absorption", "Add", None, QtGui.QApplication.UnicodeUTF8))
        self.label_9.setText(QtGui.QApplication.translate("absorption", "Number of atoms =", None, QtGui.QApplication.UnicodeUTF8))
        self.btnRemove.setText(QtGui.QApplication.translate("absorption", "Remove", None, QtGui.QApplication.UnicodeUTF8))
        self.btnRemoveAll.setText(QtGui.QApplication.translate("absorption", "Remove All", None, QtGui.QApplication.UnicodeUTF8))
        self.label_7.setText(QtGui.QApplication.translate("absorption", "Atomic weight : ", None, QtGui.QApplication.UnicodeUTF8))
        self.label_8.setText(QtGui.QApplication.translate("absorption", "Mu/rho :", None, QtGui.QApplication.UnicodeUTF8))
        self.ElementSymbol.setText(QtGui.QApplication.translate("absorption", "Cu", None, QtGui.QApplication.UnicodeUTF8))
        self.ElementAtomicNumber.setText(QtGui.QApplication.translate("absorption", "29", None, QtGui.QApplication.UnicodeUTF8))
        self.ElementName.setText(QtGui.QApplication.translate("absorption", "Hydrogen", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox_4.setTitle(QtGui.QApplication.translate("absorption", "Formula :", None, QtGui.QApplication.UnicodeUTF8))
        self.label_10.setText(QtGui.QApplication.translate("absorption", "Active formula :", None, QtGui.QApplication.UnicodeUTF8))
        self.label_11.setText(QtGui.QApplication.translate("absorption", "Compound Mu/rho  (cm2/g) :", None, QtGui.QApplication.UnicodeUTF8))
        self.label_12.setText(QtGui.QApplication.translate("absorption", "Density (g/cm3) :", None, QtGui.QApplication.UnicodeUTF8))
        self.label_13.setText(QtGui.QApplication.translate("absorption", "Electronic density (1/cm3) :", None, QtGui.QApplication.UnicodeUTF8))
        self.label_14.setText(QtGui.QApplication.translate("absorption", "Scattering length density (1/cm2) :", None, QtGui.QApplication.UnicodeUTF8))
        self.label_15.setText(QtGui.QApplication.translate("absorption", "Thickness (cm) :", None, QtGui.QApplication.UnicodeUTF8))
        self.label_16.setText(QtGui.QApplication.translate("absorption", "X-ray transmission :", None, QtGui.QApplication.UnicodeUTF8))
        self.labelLib.setText(QtGui.QApplication.translate("absorption", "Calculations made with datas from ", None, QtGui.QApplication.UnicodeUTF8))

