
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2021-02-01T11:53:32-0800",
 "dirty": false,
 "error": null,
 "full-revisionid": "af4f4af0f8dfcddeb1a379bc4448e0071046cf4e",
 "version": "v1.0"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
