# Generated by Django 2.2 on 2020-01-25 16:41

from django.db import migrations


def update_things(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ("app_correct", "0002_foo"),
    ]

    operations = [
        migrations.RunPython(update_things),
    ]
