# coding: utf-8

"""
    COIN CRDB Rest API

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)

    OpenAPI spec version: 1.0.0
    Contact: servicedesk@coin.nl
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from pprint import pformat
from six import iteritems
import re


class ActivationServiceNumberSeq(object):
    """
    NOTE: This class is auto generated by the swagger code generator program.
    Do not edit the class manually.
    """


    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'numberseries': 'NumberSeries',
        'tariffinfo': 'TariffInfo',
        'pop': 'str'
    }

    attribute_map = {
        'numberseries': 'numberseries',
        'tariffinfo': 'tariffinfo',
        'pop': 'pop'
    }

    def __init__(self, numberseries=None, tariffinfo=None, pop=None):
        """
        ActivationServiceNumberSeq - a model defined in Swagger
        """

        self._numberseries = None
        self._tariffinfo = None
        self._pop = None

        self.numberseries = numberseries
        self.tariffinfo = tariffinfo
        self.pop = pop

    @property
    def numberseries(self):
        """
        Gets the numberseries of this ActivationServiceNumberSeq.

        :return: The numberseries of this ActivationServiceNumberSeq.
        :rtype: NumberSeries
        """
        return self._numberseries

    @numberseries.setter
    def numberseries(self, numberseries):
        """
        Sets the numberseries of this ActivationServiceNumberSeq.

        :param numberseries: The numberseries of this ActivationServiceNumberSeq.
        :type: NumberSeries
        """
        if numberseries is None:
            raise ValueError("Invalid value for `numberseries`, must not be `None`")

        self._numberseries = numberseries

    @property
    def tariffinfo(self):
        """
        Gets the tariffinfo of this ActivationServiceNumberSeq.

        :return: The tariffinfo of this ActivationServiceNumberSeq.
        :rtype: TariffInfo
        """
        return self._tariffinfo

    @tariffinfo.setter
    def tariffinfo(self, tariffinfo):
        """
        Sets the tariffinfo of this ActivationServiceNumberSeq.

        :param tariffinfo: The tariffinfo of this ActivationServiceNumberSeq.
        :type: TariffInfo
        """
        if tariffinfo is None:
            raise ValueError("Invalid value for `tariffinfo`, must not be `None`")

        self._tariffinfo = tariffinfo

    @property
    def pop(self):
        """
        Gets the pop of this ActivationServiceNumberSeq.

        :return: The pop of this ActivationServiceNumberSeq.
        :rtype: str
        """
        return self._pop

    @pop.setter
    def pop(self, pop):
        """
        Sets the pop of this ActivationServiceNumberSeq.

        :param pop: The pop of this ActivationServiceNumberSeq.
        :type: str
        """
        if pop is None:
            raise ValueError("Invalid value for `pop`, must not be `None`")
        if pop is not None and len(pop) > 24:
            raise ValueError("Invalid value for `pop`, length must be less than or equal to `24`")
        if pop is not None and len(pop) < 1:
            raise ValueError("Invalid value for `pop`, length must be greater than or equal to `1`")

        self._pop = pop

    def to_dict(self):
        """
        Returns the model properties as a dict
        """
        result = {}

        for attr, _ in iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value

        return result

    def to_str(self):
        """
        Returns the string representation of the model
        """
        return pformat(self.to_dict())

    def __repr__(self):
        """
        For `print` and `pprint`
        """
        return self.to_str()

    def __eq__(self, other):
        """
        Returns true if both objects are equal
        """
        if not isinstance(other, ActivationServiceNumberSeq):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """
        Returns true if both objects are not equal
        """
        return not self == other
