"""
    Corrily LivePrice

    Corrily's LivePrice lets you to interact with Corrily's localization and dynamic pricing models to localize and optimize your prices in real-time.   # noqa: E501

    The version of the OpenAPI document: 1.1.4
    Contact: founders@corrily.com
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import corrily_live_price
from corrily_live_price.model.product import Product
globals()['Product'] = Product
from corrily_live_price.model.get_batch_request import GetBatchRequest


class TestGetBatchRequest(unittest.TestCase):
    """GetBatchRequest unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testGetBatchRequest(self):
        """Test GetBatchRequest"""
        # FIXME: construct object with mandatory attributes with example values
        # model = GetBatchRequest()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
