# -*- coding: utf-8 -*-
from setuptools import setup

packages = \
['pynll', 'pynll.nlloc']

package_data = \
{'': ['*'],
 'pynll.nlloc': ['alomax_matrix/alomax_matrix.c',
                 'alomax_matrix/alomax_matrix.c',
                 'alomax_matrix/alomax_matrix.c',
                 'alomax_matrix/alomax_matrix.c',
                 'alomax_matrix/alomax_matrix.c',
                 'alomax_matrix/alomax_matrix.c',
                 'alomax_matrix/alomax_matrix.c',
                 'alomax_matrix/alomax_matrix.c',
                 'alomax_matrix/alomax_matrix.c',
                 'alomax_matrix/alomax_matrix.h',
                 'alomax_matrix/alomax_matrix.h',
                 'alomax_matrix/alomax_matrix.h',
                 'alomax_matrix/alomax_matrix.h',
                 'alomax_matrix/alomax_matrix.h',
                 'alomax_matrix/alomax_matrix.h',
                 'alomax_matrix/alomax_matrix.h',
                 'alomax_matrix/alomax_matrix.h',
                 'alomax_matrix/alomax_matrix.h',
                 'alomax_matrix/alomax_matrix_svd.c',
                 'alomax_matrix/alomax_matrix_svd.c',
                 'alomax_matrix/alomax_matrix_svd.c',
                 'alomax_matrix/alomax_matrix_svd.c',
                 'alomax_matrix/alomax_matrix_svd.c',
                 'alomax_matrix/alomax_matrix_svd.c',
                 'alomax_matrix/alomax_matrix_svd.c',
                 'alomax_matrix/alomax_matrix_svd.c',
                 'alomax_matrix/alomax_matrix_svd.c',
                 'alomax_matrix/alomax_matrix_svd.h',
                 'alomax_matrix/alomax_matrix_svd.h',
                 'alomax_matrix/alomax_matrix_svd.h',
                 'alomax_matrix/alomax_matrix_svd.h',
                 'alomax_matrix/alomax_matrix_svd.h',
                 'alomax_matrix/alomax_matrix_svd.h',
                 'alomax_matrix/alomax_matrix_svd.h',
                 'alomax_matrix/alomax_matrix_svd.h',
                 'alomax_matrix/alomax_matrix_svd.h',
                 'alomax_matrix/eigv.c',
                 'alomax_matrix/eigv.c',
                 'alomax_matrix/eigv.c',
                 'alomax_matrix/eigv.c',
                 'alomax_matrix/eigv.c',
                 'alomax_matrix/eigv.c',
                 'alomax_matrix/eigv.c',
                 'alomax_matrix/eigv.c',
                 'alomax_matrix/eigv.c',
                 'alomax_matrix/eigv.h',
                 'alomax_matrix/eigv.h',
                 'alomax_matrix/eigv.h',
                 'alomax_matrix/eigv.h',
                 'alomax_matrix/eigv.h',
                 'alomax_matrix/eigv.h',
                 'alomax_matrix/eigv.h',
                 'alomax_matrix/eigv.h',
                 'alomax_matrix/eigv.h',
                 'alomax_matrix/polarization.c',
                 'alomax_matrix/polarization.c',
                 'alomax_matrix/polarization.c',
                 'alomax_matrix/polarization.c',
                 'alomax_matrix/polarization.c',
                 'alomax_matrix/polarization.c',
                 'alomax_matrix/polarization.c',
                 'alomax_matrix/polarization.c',
                 'alomax_matrix/polarization.c',
                 'alomax_matrix/polarization.h',
                 'alomax_matrix/polarization.h',
                 'alomax_matrix/polarization.h',
                 'alomax_matrix/polarization.h',
                 'alomax_matrix/polarization.h',
                 'alomax_matrix/polarization.h',
                 'alomax_matrix/polarization.h',
                 'alomax_matrix/polarization.h',
                 'alomax_matrix/polarization.h',
                 'alomax_matrix/test_real_symmetric_eigen.c',
                 'alomax_matrix/test_real_symmetric_eigen.c',
                 'alomax_matrix/test_real_symmetric_eigen.c',
                 'alomax_matrix/test_real_symmetric_eigen.c',
                 'alomax_matrix/test_real_symmetric_eigen.c',
                 'alomax_matrix/test_real_symmetric_eigen.c',
                 'alomax_matrix/test_real_symmetric_eigen.c',
                 'alomax_matrix/test_real_symmetric_eigen.c',
                 'alomax_matrix/test_real_symmetric_eigen.c',
                 'geometry/*',
                 'matrix_statistics/matrix_statistics.c',
                 'matrix_statistics/matrix_statistics.c',
                 'matrix_statistics/matrix_statistics.c',
                 'matrix_statistics/matrix_statistics.c',
                 'matrix_statistics/matrix_statistics.c',
                 'matrix_statistics/matrix_statistics.h',
                 'matrix_statistics/matrix_statistics.h',
                 'matrix_statistics/matrix_statistics.h',
                 'matrix_statistics/matrix_statistics.h',
                 'matrix_statistics/matrix_statistics.h',
                 'matrix_statistics/matrix_statistics_DEV.c',
                 'matrix_statistics/matrix_statistics_DEV.c',
                 'matrix_statistics/matrix_statistics_DEV.c',
                 'matrix_statistics/matrix_statistics_DEV.c',
                 'matrix_statistics/matrix_statistics_DEV.c',
                 'matrix_statistics/matrix_statistics_DEV.h',
                 'matrix_statistics/matrix_statistics_DEV.h',
                 'matrix_statistics/matrix_statistics_DEV.h',
                 'matrix_statistics/matrix_statistics_DEV.h',
                 'matrix_statistics/matrix_statistics_DEV.h',
                 'matrix_statistics/test_ellipsoid.c',
                 'matrix_statistics/test_ellipsoid.c',
                 'matrix_statistics/test_ellipsoid.c',
                 'matrix_statistics/test_ellipsoid.c',
                 'matrix_statistics/test_ellipsoid.c',
                 'octtree/geometry.h',
                 'octtree/geometry.h',
                 'octtree/geometry.h',
                 'octtree/geometry.h',
                 'octtree/octtree.c',
                 'octtree/octtree.c',
                 'octtree/octtree.c',
                 'octtree/octtree.c',
                 'octtree/octtree.h',
                 'octtree/octtree.h',
                 'octtree/octtree.h',
                 'octtree/octtree.h',
                 'octtree/ran1.h',
                 'octtree/ran1.h',
                 'octtree/ran1.h',
                 'octtree/ran1.h',
                 'ran1/ran1.c',
                 'ran1/ran1.c',
                 'ran1/ran1.h',
                 'ran1/ran1.h',
                 'vector/vector.c',
                 'vector/vector.c',
                 'vector/vector.h',
                 'vector/vector.h']}

install_requires = \
['setuptools_cpp>=0.1.0,<0.2.0', 'uquake>=0.1.0,<0.2.0']

setup_kwargs = {
    'name': 'pynll',
    'version': '0.1.0',
    'description': 'wrapper around A. Lomax NLLoc',
    'long_description': None,
    'author': 'jpmercier',
    'author_email': 'jpmercier01@gmail.com',
    'maintainer': None,
    'maintainer_email': None,
    'url': None,
    'packages': packages,
    'package_data': package_data,
    'install_requires': install_requires,
    'python_requires': '>=3.8,<4.0',
}
from build import *
build(setup_kwargs)

setup(**setup_kwargs)
