
# This file was generated by 'versioneer.py' (0.19) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2021-02-02T14:58:31-0500",
 "dirty": false,
 "error": null,
 "full-revisionid": "51b91686d6416a84dc32bde9d9d029f495b846ea",
 "version": "2.2"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
