
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2021-02-04T20:02:33+0100",
 "dirty": false,
 "error": null,
 "full-revisionid": "8ca61623f2b0e0300625bd9f2c57358bd015e1cf",
 "version": "1.0.9"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
