# -*- coding: utf-8 -*-

"""
mycalculator

This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
"""


class OperationEnum(object):

    """Implementation of the 'operation' enum.

    TODO: type enum description here.

    Attributes:
        SUM: Adds the specified variables.
        SUBTRACT: Subtracts the specified variables.
        MULTIPLY: Multiplies the specified variables.
        DIVIDE: Divides the specified variables.

    """

    SUM = 'SUM'

    SUBTRACT = 'SUBTRACT'

    MULTIPLY = 'MULTIPLY'

    DIVIDE = 'DIVIDE'
