# Generated by Django 2.2.8 on 2019-12-06 08:55

import bitfield.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('planing', '0020_operation_types'),
    ]

    operations = [
        migrations.AlterField(
            model_name='operation_types',
            name='props',
            field=bitfield.models.BitField((('isoper', 'Является операцией'), ('plus', 'Приходная операция')), db_index=True, default=0),
        ),
    ]
