# Generated by Django 3.0.3 on 2020-02-29 14:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('planing', '0118_operation_attr'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Operation_attr',
        ),
    ]
