# Generated by Django 3.0.7 on 2020-06-14 08:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('planing', '0130_auto_20200614_0531'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='operation_item',
            name='item_full_name',
        ),
        migrations.RemoveField(
            model_name='operation_item',
            name='item_full_name_obj',
        ),
    ]
