# Generated by Django 3.0.7 on 2020-06-14 08:38


from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import isc_common.fields.related
from isc_common.fields.code_field import JSONFieldIVC

class Migration(migrations.Migration):

    dependencies = [
        ('planing', '0131_auto_20200614_0834'),
    ]

    operations = [
        migrations.CreateModel(
            name='Operation_item_add',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False, verbose_name='Идентификатор')),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='Дата мягкого удаления')),
                ('editing', models.BooleanField(default=True, verbose_name='Возможность редактирования')),
                ('deliting', models.BooleanField(default=True, verbose_name='Возможность удаления')),
                ('lastmodified', models.DateTimeField(db_index=True, default=django.utils.timezone.now, editable=False, verbose_name='Последнее обновление')),
                ('item_full_name', models.TextField(db_index=True)),
                ('item_full_name_obj', JSONFieldIVC()),
                ('operation_item', isc_common.fields.related.ForeignKeyCascade(on_delete=django.db.models.deletion.CASCADE, to='planing.Operation_item')),
            ],
            options={
                'verbose_name': 'Кросс таблица',
            },
        ),
    ]
