# Generated by Django 3.0.7 on 2020-06-14 10:07

import django.db.models.deletion
from django.db import migrations

import isc_common.fields.related


class Migration(migrations.Migration):
    dependencies = [
        ('production', '0233_auto_20200609_1920'),
        ('planing', '0135_auto_20200614_1004'),
    ]

    operations = [
        migrations.AddField(
            model_name='operation_item_add',
            name='launch',
            field=isc_common.fields.related.ForeignKeyCascade(default=None, on_delete=django.db.models.deletion.CASCADE, to='production.Launches'),
        ),
    ]
