# Generated by Django 3.0.7 on 2020-06-15 03:47

from django.db import migrations
import django.db.models.deletion
import isc_common.fields.related


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0235_auto_20200615_0311'),
        ('planing', '0139_auto_20200615_0303'),
    ]

    operations = [
        migrations.AlterField(
            model_name='operation_standard_prod',
            name='material',
            field=isc_common.fields.related.ForeignKeyProtect(on_delete=django.db.models.deletion.PROTECT, to='production.Operation_material'),
        ),
    ]
