# Generated by Django 3.0.7 on 2020-06-17 06:51

from django.db import migrations
import django.db.models.deletion
import isc_common.fields.related


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0240_auto_20200617_0546'),
        ('planing', '0143_delete_operation_standard_prod'),
    ]

    operations = [
        migrations.AlterField(
            model_name='operation_material',
            name='material',
            field=isc_common.fields.related.ForeignKeyProtect(on_delete=django.db.models.deletion.PROTECT, related_name='launch_operations_material', to='production.Launch_operations_material'),
        ),
    ]
