# Generated by Django 3.0.7 on 2020-06-17 06:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('planing', '0144_auto_20200617_0651'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='operation_material',
            unique_together=set(),
        ),
    ]
