# Generated by Django 3.0.7 on 2020-06-17 07:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0241_auto_20200617_0705'),
        ('planing', '0150_auto_20200617_0726'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='operation_resources',
            unique_together={('operation', 'launch_operation_resources')},
        ),
    ]
