# Generated by Django 3.0.7 on 2020-06-24 16:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('planing', '0169_operation_operation_attr'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Operation_operation_attr',
        ),
    ]
