# Generated by Django 3.0.7 on 2020-06-26 09:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('planing', '0171_production_order_by_launch'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Production_order_by_launch',
        ),
    ]
