# Generated by Django 3.0.7 on 2020-07-04 18:39

import bitfield.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('planing', '0176_production_order_opers_per_demand'),
    ]

    operations = [
        migrations.AlterField(
            model_name='status_operation_types',
            name='props',
            field=bitfield.models.BitField((('disabled', 'Неактивная запись в гриде'), ('blink', 'Мигающее поле в гриде'), ('bold', 'Жирное поле в гриде')), db_index=True, default=0),
        ),
    ]
