# Generated by Django 3.0.7 on 2020-07-05 03:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('planing', '0177_auto_20200704_1839'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Posting_items',
        ),
        migrations.DeleteModel(
            name='Write_off_items',
        ),
    ]
