# Generated by Django 3.0.8 on 2020-07-07 13:50

import bitfield.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('planing', '0183_operation_history'),
    ]

    operations = [
        migrations.AlterField(
            model_name='operation_executor',
            name='props',
            field=bitfield.models.BitField((('relevant', 'Актуальность'), ('rearrange', 'Переадресованный')), db_index=True, default=1),
        ),
    ]
