# Generated by Django 3.0.8 on 2020-07-12 18:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0279_auto_20200712_0914'),
        ('planing', '0192_operation_launch_item'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='operation_launch_item',
            unique_together={('operation', 'launch_item')},
        ),
        migrations.RemoveField(
            model_name='operation_launch_item',
            name='num',
        ),
    ]
