# Generated by Django 3.0.8 on 2020-07-13 08:55

from django.db import migrations
import django.db.models.deletion
import isc_common.fields.related


class Migration(migrations.Migration):

    dependencies = [
        ('planing', '0195_operation_launch_item_level'),
    ]

    operations = [
        migrations.AlterField(
            model_name='operation_launch_item',
            name='level',
            field=isc_common.fields.related.ForeignKeyCascade(on_delete=django.db.models.deletion.CASCADE, to='planing.Levels'),
        ),
    ]
