# Generated by Django 3.0.8 on 2020-07-17 03:08

from django.db import migrations
import django.db.models.deletion
import isc_common.fields.date_time_field
import isc_common.fields.related


class Migration(migrations.Migration):

    dependencies = [
        ('planing', '0201_auto_20200717_0308'),
    ]

    operations = [
        migrations.AlterField(
            model_name='operation_history',
            name='date',
            field=isc_common.fields.date_time_field.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='operation_history',
            name='opertype',
            field=isc_common.fields.related.ForeignKeyProtect(on_delete=django.db.models.deletion.PROTECT, to='planing.Operation_types'),
        ),
    ]
