# Generated by Django 3.1 on 2020-08-05 08:57

from django.db import migrations
import django.db.models.deletion
import isc_common.fields.related


class Migration(migrations.Migration):

    dependencies = [
        ('isc_common', '0055_auto_20200713_0552'),
        ('planing', '0220_auto_20200804_1212'),
    ]

    operations = [
        migrations.AddField(
            model_name='operation_operation',
            name='color',
            field=isc_common.fields.related.ForeignKeyProtect(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='isc_common.standard_colors'),
        ),
        migrations.AlterUniqueTogether(
            name='operation_operation',
            unique_together=set(),
        ),
    ]
