# Generated by Django 3.1 on 2020-08-22 05:57

import bitfield.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('planing', '0235_tmp_operation_value_last_tech_operation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tmp_operation_value',
            name='props',
            field=bitfield.models.BitField((('enabled', 'Всборе'),), db_index=True, default=0),
        ),
    ]
