# Generated by Django 3.1.2 on 2020-10-20 05:51

import bitfield.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('planing', '0254_auto_20201014_1030'),
    ]

    operations = [
        migrations.AlterField(
            model_name='operation_refs',
            name='props',
            field=bitfield.models.BitField((('inner_routing', 'Связь операций внутри товарной позиции'), ('outer_routing', 'Связь операций между товарными позициями'), ('product_order_routing', 'Связи в блоке задания на производство'), ('product_making', 'Связи выпуска'), ('product_making_block', 'Блок операций выпуска, удаляется как одно целое'), ('maked_for_grouped', 'Cгруппировано в задании на производство')), db_index=True, default=0),
        ),
    ]
