# Generated by Django 3.1.3 on 2020-11-20 16:17

from django.db import migrations
import django.db.models.deletion
import isc_common.fields.related


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0321_auto_20201120_0956'),
        ('planing', '0268_auto_20201120_1404'),
    ]

    operations = [
        migrations.AddField(
            model_name='production_order_tmp',
            name='launch_incom',
            field=isc_common.fields.related.ForeignKeyCascade(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='production.launches'),
        ),
    ]
