# Generated by Django 3.1.4 on 2020-12-06 06:48

from django.db import migrations
import isc_common.fields.code_field


class Migration(migrations.Migration):

    dependencies = [
        ('planing', '0298_auto_20201205_1326'),
    ]

    operations = [
        migrations.AddField(
            model_name='production_order_tmp',
            name='location_values_made',
            field=isc_common.fields.code_field.JSONFieldIVC(blank=True, default=dict, null=True),
        ),
    ]
