# Generated by Django 3.1.4 on 2020-12-09 16:04

from django.db import migrations
import django.db.models.deletion
import isc_common.fields.related


class Migration(migrations.Migration):

    dependencies = [
        ('ckk', '0270_auto_20201113_0846'),
        ('planing', '0301_production_order_tmp_last_tech_operation'),
    ]

    operations = [
        migrations.AddField(
            model_name='production_order_tmp',
            name='location',
            field=isc_common.fields.related.ForeignKeyProtect(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='Production_order_tmp_locations', to='ckk.locations'),
        ),
    ]
