# Generated by Django 3.1.4 on 2020-12-09 16:22

from django.db import migrations
import django.db.models.deletion
import isc_common.fields.related


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0322_auto_20201204_0703'),
        ('planing', '0302_production_order_tmp_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='production_order_tmp',
            name='resource',
            field=isc_common.fields.related.ForeignKeyProtect(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='Production_order_tmp_resource', to='production.resource'),
        ),
    ]
