# Generated by Django 3.1.4 on 2020-12-21 08:31

from django.db import migrations
import isc_common.fields.code_field


class Migration(migrations.Migration):

    dependencies = [
        ('planing', '0304_production_order_tmp_value_made_old'),
    ]

    operations = [
        migrations.AddField(
            model_name='production_order_tmp',
            name='locations_sector_ready',
            field=isc_common.fields.code_field.JSONFieldIVC(blank=True, default=dict, null=True),
        ),
    ]
