# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import device_service_pb2 as device__service__pb2


class DeviceServiceStub(object):
    """
    The DeviceService manages devices. Once a device is created
    it can be used in a telerobotic procedure.
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Create = channel.unary_unary(
                '/dopltechnologies.protos.DeviceService/Create',
                request_serializer=device__service__pb2.CreateDeviceRequest.SerializeToString,
                response_deserializer=device__service__pb2.CreateDeviceResponse.FromString,
                )
        self.Get = channel.unary_unary(
                '/dopltechnologies.protos.DeviceService/Get',
                request_serializer=device__service__pb2.GetDeviceRequest.SerializeToString,
                response_deserializer=device__service__pb2.GetDeviceResponse.FromString,
                )
        self.Update = channel.unary_unary(
                '/dopltechnologies.protos.DeviceService/Update',
                request_serializer=device__service__pb2.UpdateDeviceRequest.SerializeToString,
                response_deserializer=device__service__pb2.UpdateDeviceResponse.FromString,
                )
        self.List = channel.unary_stream(
                '/dopltechnologies.protos.DeviceService/List',
                request_serializer=device__service__pb2.ListDevicesRequest.SerializeToString,
                response_deserializer=device__service__pb2.ListDevicesResponse.FromString,
                )
        self.Delete = channel.unary_unary(
                '/dopltechnologies.protos.DeviceService/Delete',
                request_serializer=device__service__pb2.DeleteDeviceRequest.SerializeToString,
                response_deserializer=device__service__pb2.DeleteDeviceResponse.FromString,
                )


class DeviceServiceServicer(object):
    """
    The DeviceService manages devices. Once a device is created
    it can be used in a telerobotic procedure.
    """

    def Create(self, request, context):
        """Creates a new device
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Get(self, request, context):
        """Get information about a single device
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Update(self, request, context):
        """Update information about a single device
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def List(self, request, context):
        """Lists all devices
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Delete(self, request, context):
        """Deletes a device
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_DeviceServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Create': grpc.unary_unary_rpc_method_handler(
                    servicer.Create,
                    request_deserializer=device__service__pb2.CreateDeviceRequest.FromString,
                    response_serializer=device__service__pb2.CreateDeviceResponse.SerializeToString,
            ),
            'Get': grpc.unary_unary_rpc_method_handler(
                    servicer.Get,
                    request_deserializer=device__service__pb2.GetDeviceRequest.FromString,
                    response_serializer=device__service__pb2.GetDeviceResponse.SerializeToString,
            ),
            'Update': grpc.unary_unary_rpc_method_handler(
                    servicer.Update,
                    request_deserializer=device__service__pb2.UpdateDeviceRequest.FromString,
                    response_serializer=device__service__pb2.UpdateDeviceResponse.SerializeToString,
            ),
            'List': grpc.unary_stream_rpc_method_handler(
                    servicer.List,
                    request_deserializer=device__service__pb2.ListDevicesRequest.FromString,
                    response_serializer=device__service__pb2.ListDevicesResponse.SerializeToString,
            ),
            'Delete': grpc.unary_unary_rpc_method_handler(
                    servicer.Delete,
                    request_deserializer=device__service__pb2.DeleteDeviceRequest.FromString,
                    response_serializer=device__service__pb2.DeleteDeviceResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'dopltechnologies.protos.DeviceService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class DeviceService(object):
    """
    The DeviceService manages devices. Once a device is created
    it can be used in a telerobotic procedure.
    """

    @staticmethod
    def Create(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/dopltechnologies.protos.DeviceService/Create',
            device__service__pb2.CreateDeviceRequest.SerializeToString,
            device__service__pb2.CreateDeviceResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def Get(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/dopltechnologies.protos.DeviceService/Get',
            device__service__pb2.GetDeviceRequest.SerializeToString,
            device__service__pb2.GetDeviceResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def Update(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/dopltechnologies.protos.DeviceService/Update',
            device__service__pb2.UpdateDeviceRequest.SerializeToString,
            device__service__pb2.UpdateDeviceResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def List(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(request, target, '/dopltechnologies.protos.DeviceService/List',
            device__service__pb2.ListDevicesRequest.SerializeToString,
            device__service__pb2.ListDevicesResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def Delete(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/dopltechnologies.protos.DeviceService/Delete',
            device__service__pb2.DeleteDeviceRequest.SerializeToString,
            device__service__pb2.DeleteDeviceResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
