# Generated by Django 3.1.1 on 2020-11-23 02:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ead', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='conventiondeclaration',
            name='descriptivenote',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='corpnamepart',
            name='plain_name',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='daoset',
            name='descriptivenote',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='daosetdao',
            name='descriptivenote',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='diddao',
            name='descriptivenote',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='didphysdescstructured',
            name='descriptivenote',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='didphysdescstructured',
            name='quantity_approximate',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='famnamepart',
            name='plain_name',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='langmaterial',
            name='descriptivenote',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='languagedeclaration',
            name='descriptivenote',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='languageset',
            name='descriptivenote',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='localtypedeclaration',
            name='descriptivenote',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='namepart',
            name='plain_name',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='persnamepart',
            name='plain_name',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='physdescset',
            name='descriptivenote',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='physdescset',
            name='parallel',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='physdescsetphysdescstructured',
            name='descriptivenote',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='physdescsetphysdescstructured',
            name='quantity_approximate',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='relation',
            name='descriptivenote',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='relation',
            name='objectxmlwrap',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='repository',
            name='assembled_name',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='rightsdeclaration',
            name='descriptivenote',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='source',
            name='descriptivenote',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='source',
            name='objectxmlwrap',
            field=models.TextField(blank=True),
        ),
    ]
