# Generated by Django 3.1.1 on 2020-12-02 21:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ead', '0002_auto_20201123_0256'),
    ]

    operations = [
        migrations.AlterField(
            model_name='container',
            name='parents',
            field=models.ManyToManyField(blank=True, related_name='child_containers', to='ead.Container'),
        ),
        migrations.AlterField(
            model_name='origination',
            name='corpnames',
            field=models.ManyToManyField(blank=True, to='ead.CorpName'),
        ),
        migrations.AlterField(
            model_name='origination',
            name='famnames',
            field=models.ManyToManyField(blank=True, to='ead.FamName'),
        ),
        migrations.AlterField(
            model_name='origination',
            name='names',
            field=models.ManyToManyField(blank=True, to='ead.Name'),
        ),
        migrations.AlterField(
            model_name='origination',
            name='persnames',
            field=models.ManyToManyField(blank=True, to='ead.PersName'),
        ),
        migrations.AlterField(
            model_name='physloc',
            name='parents',
            field=models.ManyToManyField(blank=True, related_name='child_physlocs', to='ead.PhysLoc'),
        ),
        migrations.AlterField(
            model_name='repository',
            name='corpnames',
            field=models.ManyToManyField(blank=True, to='ead.CorpName'),
        ),
        migrations.AlterField(
            model_name='repository',
            name='famnames',
            field=models.ManyToManyField(blank=True, to='ead.FamName'),
        ),
        migrations.AlterField(
            model_name='repository',
            name='names',
            field=models.ManyToManyField(blank=True, to='ead.Name'),
        ),
        migrations.AlterField(
            model_name='repository',
            name='persnames',
            field=models.ManyToManyField(blank=True, to='ead.PersName'),
        ),
    ]
