# Generated by Django 3.1.1 on 2020-12-02 21:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ead', '0003_auto_20201202_2125'),
    ]

    operations = [
        migrations.AlterField(
            model_name='corpname',
            name='assembled_name',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='famname',
            name='assembled_name',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='name',
            name='assembled_name',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='persname',
            name='assembled_name',
            field=models.TextField(blank=True),
        ),
    ]
