from ExtractBQT.main import *
from ExtractBQT.classify import *
from ExtractBQT.studentCard_class import *
from ExtractBQT.drivingLicense_class import *
from ExtractBQT.idCard_class import *
from ExtractBQT.ocr import *
from ExtractBQT.processing import *
from detect.config import *
from detect.ctpn_model import *
from detect.ctpn_predict import *
from detect.ctpn_utils import *
