
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2021-02-04T13:44:09+0000",
 "dirty": false,
 "error": null,
 "full-revisionid": "6fae63a7de3f481206bbee28acf5097f43ed4d78",
 "version": "0.1.99"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
