# Generated by Django 2.2 on 2019-04-14 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ckk', '0014_auto_20190414_0801'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attr_type',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Дата мягкого удаления'),
        ),
        migrations.AlterField(
            model_name='item',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Дата мягкого удаления'),
        ),
        migrations.AlterField(
            model_name='item_line',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Дата мягкого удаления'),
        ),
        migrations.AlterField(
            model_name='item_line_refs',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Дата мягкого удаления'),
        ),
    ]
