# Generated by Django 2.2.4 on 2019-08-19 15:27

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import isc_common.fields.related


class Migration(migrations.Migration):

    dependencies = [
        ('ckk', '0140_auto_20190808_1301'),
    ]

    operations = [
        migrations.CreateModel(
            name='Material_askon',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False, verbose_name='Идентификатор')),
                ('id_old', models.BigIntegerField(blank=True, null=True, verbose_name='Идентификатор старый')),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='Дата мягкого удаления')),
                ('editing', models.BooleanField(default=True, verbose_name='Возможность редактирования')),
                ('deliting', models.BooleanField(default=True, verbose_name='Возможность удаления')),
                ('lastmodified', models.DateTimeField(db_index=True, default=django.utils.timezone.now, editable=False, verbose_name='Последнее обновление')),
                ('field0', models.CharField(db_index=True, max_length=255, verbose_name='Информация в дерево материалов')),
                ('field1', models.CharField(blank=True, max_length=255, null=True, verbose_name='Материал.Наименование и документ')),
                ('field2', models.CharField(blank=True, max_length=255, null=True, verbose_name='Материал.Код')),
                ('field3', models.CharField(blank=True, max_length=255, null=True, verbose_name='Сортамент.Наименование и документ')),
                ('field4', models.CharField(blank=True, max_length=255, null=True, verbose_name='Экземпляр сортамента.Типоразмер')),
                ('field5', models.CharField(blank=True, max_length=255, null=True, verbose_name='Экземпляр сортамента.Обозначение')),
                ('field6', models.CharField(blank=True, max_length=255, null=True, verbose_name='Экземпляр сортамента.Статус')),
                ('field7', models.CharField(blank=True, max_length=255, null=True, verbose_name='Экземпляр сортамента.Код')),
                ('parent', isc_common.fields.related.ForeignKeyProtect(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='ckk.Material_askon')),
            ],
            options={
                'verbose_name': 'Материалы из Асона',
            },
        ),
    ]
