# Generated by Django 2.2.8 on 2019-12-12 18:44

from django.db import migrations
import django.db.models.deletion
import isc_common.fields.related


class Migration(migrations.Migration):

    dependencies = [
        ('ckk', '0168_delete_item_refs_hierarcy'),
    ]

    operations = [
        migrations.AddField(
            model_name='item_refs',
            name='syntetic_child',
            field=isc_common.fields.related.ForeignKeyProtect(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='syntetic_child', to='ckk.Item'),
        ),
    ]
