# Generated by Django 3.0.2 on 2020-01-22 16:19

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ckk', '0187_auto_20200122_1613'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='locations_users',
            unique_together={('location', 'user', 'parent')},
        ),
    ]
