# Generated by Django 3.0.3 on 2020-02-23 04:00

import bitfield.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ckk', '0210_auto_20200212_0752'),
    ]

    operations = [
        migrations.AddField(
            model_name='locations',
            name='props',
            field=bitfield.models.BitField((('isWorkshop', 'Уровень цеха'),), db_index=True, default=0),
        ),
    ]
