# Generated by Django 3.0.3 on 2020-02-25 10:13

import bitfield.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ckk', '0211_locations_props'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item_refs',
            name='props',
            field=bitfield.models.BitField((('relevant', 'Актуальность'), ('used', 'Используемость в технологической спецификации')), db_index=True, default=3),
        ),
    ]
