# Generated by Django 3.0.5 on 2020-04-16 14:46

import bitfield.models
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('ckk', '0222_auto_20200413_1454'),
    ]

    operations = [
        migrations.CreateModel(
            name='Item_qty_view',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False, verbose_name='Идентификатор')),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='Дата мягкого удаления')),
                ('editing', models.BooleanField(default=True, verbose_name='Возможность редактирования')),
                ('deliting', models.BooleanField(default=True, verbose_name='Возможность удаления')),
                ('lastmodified', models.DateTimeField(db_index=True, default=django.utils.timezone.now, editable=False, verbose_name='Последнее обновление')),
                ('qty', models.PositiveIntegerField()),
                ('props', bitfield.models.BitField((('items', 'Состав изделия (Технологическая спецификация)'), ('teach', 'Производственная спецификация')), db_index=True, default=1)),
            ],
            options={
                'verbose_name': 'Количество элементов',
                'db_table': 'ckk_item_qty_view',
                'managed': False,
            },
        ),
    ]
