# Generated by Django 3.0.8 on 2020-07-08 15:17

import bitfield.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ckk', '0229_locations_view'),
    ]

    operations = [
        migrations.AlterField(
            model_name='locations_users',
            name='props',
            field=bitfield.models.BitField((('compulsory_reading', 'Обязательное прочтение'),), db_index=True, default=0),
        ),
    ]
