# Generated by Django 3.0.8 on 2020-07-17 06:10

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('ckk', '0232_item_creator'),
    ]

    operations = [
        migrations.RunSQL(
            'update ckk_item set creator_id = 0',
        ),
    ]
