# Generated by Django 3.1 on 2020-08-23 07:24

import bitfield.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ckk', '0248_auto_20200821_1509'),
    ]

    operations = [
        migrations.AddField(
            model_name='item_image_refs',
            name='props',
            field=bitfield.models.BitField((('useinprint', 'Выводим в печатную форму'),), db_index=True, default=0),
        ),
    ]
