# Generated by Django 3.1.2 on 2020-10-31 05:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ckk', '0260_auto_20201030_1424'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='item_refs_location',
            name='Item_refs_location_unique_constraint_0',
        ),
        migrations.RemoveConstraint(
            model_name='item_refs_location',
            name='Item_refs_location_unique_constraint_1',
        ),
        migrations.RemoveField(
            model_name='item_refs_location',
            name='main_item',
        ),
        migrations.AddConstraint(
            model_name='item_refs_location',
            constraint=models.UniqueConstraint(condition=models.Q(parent_id=None), fields=('child_id',), name='Item_refs_location_unique_constraint_0'),
        ),
        migrations.AddConstraint(
            model_name='item_refs_location',
            constraint=models.UniqueConstraint(fields=('child_id', 'parent_id'), name='Item_refs_location_unique_constraint_1'),
        ),
    ]
