# Generated by Django 3.1.3 on 2020-11-09 09:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ckk', '0267_auto_20201103_0932'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item_refs_location',
            name='child',
        ),
        migrations.RemoveField(
            model_name='item_refs_location',
            name='location',
        ),
        migrations.RemoveField(
            model_name='item_refs_location',
            name='parent',
        ),
        migrations.DeleteModel(
            name='Item_refs_location_view',
        ),
        migrations.DeleteModel(
            name='Item_refs_location',
        ),
    ]
