#!/usr/bin/env python
# setup.py generated by flit for tools that don't yet use PEP 517

from distutils.core import setup


setup(name='surrortgsdk',
      version='0.0.1a1',
      description='surrortgsdk',
      author='Surrogate Inc',
      author_email=None,
      url='https://github.com/SurrogateInc/surrortgsdk-sdk',
      py_modules=['surrortgsdk'],
     )
