# Generated by Django 3.0.11 on 2021-01-21 14:06

import i18nfield.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pretix_question_placeholders", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="placeholderrule",
            name="position",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="questionplaceholder",
            name="slug",
            field=models.SlugField(null=True),
        ),
        migrations.AlterField(
            model_name="placeholderrule",
            name="content",
            field=i18nfield.fields.I18nTextField(null=True),
        ),
        migrations.AlterField(
            model_name="questionplaceholder",
            name="fallback_content",
            field=i18nfield.fields.I18nTextField(null=True),
        ),
    ]
