
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2021-01-29T22:28:01+0100",
 "dirty": false,
 "error": null,
 "full-revisionid": "00c981bd6fe9c1b03008518d5d185323ad1a9e67",
 "version": "0.0.1"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
