# Generated by Django 3.0.7 on 2020-07-05 04:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0014_auto_20200705_0357'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tmp_buffer',
            name='id',
            field=models.BigAutoField(primary_key=True, serialize=False, verbose_name='Идентификатор'),
        ),
    ]
