# auto-generated by dev/info-updater.py
# using metadata from dev/metadata.py

SETUP_INFO = dict(
    name = 'walt-server',
    version = '7',
    install_requires = ['plumbum>=1.4.2', 'snimpy>=0.8.3', 'pysnmp>=4.4.12', 'ipaddress>=1.0.7', 'requests>=2.3.0', 'sdnotify>=0.3.0', 'python-dateutil>=2.4.2', 'psycopg2-binary>=2.8.2', 'walt-common==7', 'walt-virtual==7'],
    author = 'WalT developers',
    author_email = 'walt-contact@univ-grenoble-alpes.fr',
    keywords = 'WalT testbed',
    license = '3-Clause BSD',
    url = 'https://walt-project.liglab.fr',
    description = 'WalT server components.',
    entry_points = dict(
        console_scripts = ['walt-server-setup = walt.server.setup:run', 'walt-server-daemon = walt.server.daemon:run', 'walt-dhcp-event = walt.server.dhcpevent:run', 'walt-net-config = walt.server.netconfig:run']
    ),
    include_package_data = True,
    scripts = ['sh/walt-image-shell-helper']
)
