
# This file was generated by 'versioneer.py' (0.18.2) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2021-02-01T16:02:10+0000",
 "dirty": false,
 "error": null,
 "full-revisionid": "2ae6ae80f96ee354687a7367544daf03cb17bd41",
 "version": "0.7.0"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
