
# This file was generated by 'versioneer.py' (0.18.2) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2021-02-01T17:08:36+0000",
 "dirty": false,
 "error": null,
 "full-revisionid": "f402edf99645161cac9ccf146a123cb49fb0fc8f",
 "version": "0.7.5"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
