# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: derived_key.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='derived_key.proto',
  package='keychainClient.proto',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=b'\n\x11\x64\x65rived_key.proto\x12\x14keychainClient.proto\"G\n\nDerivedKey\x12\x16\n\x0ekey_generation\x18\x01 \x01(\x04\x12\x14\n\x0ckey_category\x18\x02 \x01(\t\x12\x0b\n\x03key\x18\x03 \x01(\x0c\x62\x06proto3'
)




_DERIVEDKEY = _descriptor.Descriptor(
  name='DerivedKey',
  full_name='keychainClient.proto.DerivedKey',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='key_generation', full_name='keychainClient.proto.DerivedKey.key_generation', index=0,
      number=1, type=4, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='key_category', full_name='keychainClient.proto.DerivedKey.key_category', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='key', full_name='keychainClient.proto.DerivedKey.key', index=2,
      number=3, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=b"",
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=43,
  serialized_end=114,
)

DESCRIPTOR.message_types_by_name['DerivedKey'] = _DERIVEDKEY
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

DerivedKey = _reflection.GeneratedProtocolMessageType('DerivedKey', (_message.Message,), {
  'DESCRIPTOR' : _DERIVEDKEY,
  '__module__' : 'derived_key_pb2'
  # @@protoc_insertion_point(class_scope:keychainClient.proto.DerivedKey)
  })
_sym_db.RegisterMessage(DerivedKey)


# @@protoc_insertion_point(module_scope)
