#!/usr/bin/env python
# setup.py generated by flit for tools that don't yet use PEP 517

from distutils.core import setup

packages = \
['tcl_kernel']

package_data = \
{'': ['*']}

install_requires = \
['pexpect>=3.3']

setup(name='tcl_kernel',
      version='0.0.5',
      description='A Tcl kernel for Jupyter',
      author='Ryan Pepper',
      author_email='rp20g15@soton.ac.uk',
      url='https://github.com/ryanpepper/tcl_kernel',
      packages=packages,
      package_data=package_data,
      install_requires=install_requires,
     )
