from us_pls._variables.models import Variables

OUTLET_DATA_VARIABLES = Variables(
    STABR="State",
    LibraryIdCode=Variables(
        FSCSKEY="FromIMLS",
        FSCS_SEQ="Suffix",
        LIBID="FromState",
    ),
    C_FSCS="MeetsDefinitionOfPublicLibrary",
    LIBNAME="Name",
    StreetAddress=Variables(
        ADDRESS="Address",
        CITY="City",
        ZIP="ZipCode",
        ZIP4="ZipCode_4Digit",
        CNTY="County",
        PHONE="Phone",
    ),
    C_OUT_TY="OutletType",
    SQ_FEET="SquareFootage",
    F_SQ_FT="SquareFootage_ImputationFlag",
    L_NUM_BM="Num_BookmobilesInBookmobileOutletRecord",
    HOURS="HoursOpen",
    WKS_OPEN="WeeksOpen",
    YR_SUB="SubmissionYearOfPublicLibraryData",
    OBEREG="BureauOfEconomicsAnalysisCode",
    STATSTRU="StructureChangeCode",
    STATNAME="NameChangeCode",
    STATADDR="AddressChangeCode",
    LONGITUD="Longitude",
    LATITUDE="Latitude",
    INCITSST="InternationalCommiteeForInfoTechStandardsStateCode_TwoDigit",
    INCITSCO="InternationalCommiteeForInfoTechStandardsStateCode_ThreeDigit",
    GNISPLAC="GeographicNamesInformationSystemFeatureId",
    CNTYPOP="CountyPopulation",
    CategorizationOfLocale=Variables(
        By=Variables(
            LOCALE="SizeAndProximityToCities",
            REAPLOCALE="SizeAndProximityToCities_FromRuralEducationAchievementProgram",
        )
    ),
    CENTRACT="CensusTract",
    CENBLOCK="CensusBlock",
    CDCODE="CongressionalDistrict",
    CBSA="CoreBasedStatisticalArea",
    MICROF="MetropolitanAndMicropolitcanStatisticalAreaFlag",
    GEOMATCH="Geocoding_AccuracyAndPrecision",
)
