# Generated by Django 2.2 on 2019-04-13 17:50

from django.db import migrations
import django.db.models.deletion
import isc_common.fields.related


class Migration(migrations.Migration):

    dependencies = [
        ('kd', '0008_auto_20190413_1524'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document_attrs',
            name='document',
            field=isc_common.fields.related.ForeignKeyProtect(on_delete=django.db.models.deletion.PROTECT, to='kd.Documents', verbose_name='Документ'),
        ),
    ]
