# Generated by Django 2.2 on 2019-04-14 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kd', '0011_auto_20190414_0432'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document_attrs',
            name='deleted',
            field=models.BooleanField(blank=True, db_index=True, null=True, verbose_name='Признак удаления'),
        ),
        migrations.AlterField(
            model_name='documents',
            name='deleted',
            field=models.BooleanField(blank=True, db_index=True, null=True, verbose_name='Признак удаления'),
        ),
        migrations.AlterField(
            model_name='documents_thumb',
            name='deleted',
            field=models.BooleanField(blank=True, db_index=True, null=True, verbose_name='Признак удаления'),
        ),
        migrations.AlterField(
            model_name='documents_thumb10',
            name='deleted',
            field=models.BooleanField(blank=True, db_index=True, null=True, verbose_name='Признак удаления'),
        ),
        migrations.AlterField(
            model_name='pathes',
            name='deleted',
            field=models.BooleanField(blank=True, db_index=True, null=True, verbose_name='Признак удаления'),
        ),
    ]
