# Generated by Django 2.2 on 2019-04-14 07:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kd', '0012_auto_20190414_0756'),
    ]

    operations = [
        migrations.RenameField(
            model_name='document_attrs',
            old_name='deleted',
            new_name='deleted_at',
        ),
        migrations.RenameField(
            model_name='documents',
            old_name='deleted',
            new_name='deleted_at',
        ),
        migrations.RenameField(
            model_name='documents_thumb',
            old_name='deleted',
            new_name='deleted_at',
        ),
        migrations.RenameField(
            model_name='documents_thumb10',
            old_name='deleted',
            new_name='deleted_at',
        ),
        migrations.RenameField(
            model_name='pathes',
            old_name='deleted',
            new_name='deleted_at',
        ),
    ]
