# Generated by Django 2.2.1 on 2019-05-25 09:54

from django.db import migrations
import django.db.models.deletion
import isc_common.fields.related


class Migration(migrations.Migration):

    dependencies = [
        ('kd', '0027_auto_20190518_2136'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documents_thumb',
            name='document',
            field=isc_common.fields.related.ForeignKeyCascade(on_delete=django.db.models.deletion.CASCADE, to='kd.Documents', verbose_name='КД'),
        ),
        migrations.AlterField(
            model_name='documents_thumb10',
            name='document',
            field=isc_common.fields.related.ForeignKeyCascade(on_delete=django.db.models.deletion.CASCADE, to='kd.Documents', verbose_name='КД'),
        ),
    ]
