# Generated by Django 2.2.2 on 2019-06-07 19:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kd', '0035_auto_20190607_1854'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='document_attr_cross',
            unique_together={('document', 'attribute')},
        ),
    ]
