# Generated by Django 2.2.8 on 2019-12-13 13:03

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import isc_common.fields.related


class Migration(migrations.Migration):

    dependencies = [
        ('ckk', '0177_item_refs_hierarcy'),
        ('kd', '0089_auto_20191213_1252'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lotsman_documents',
            name='attr_type',
        ),
        migrations.RemoveField(
            model_name='lotsman_documents',
            name='value_int',
        ),
        migrations.RemoveField(
            model_name='lotsman_documents',
            name='value_str',
        ),
        migrations.CreateModel(
            name='Lotsman_documents_attributes',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False, verbose_name='Идентификатор')),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='Дата мягкого удаления')),
                ('editing', models.BooleanField(default=True, verbose_name='Возможность редактирования')),
                ('deliting', models.BooleanField(default=True, verbose_name='Возможность удаления')),
                ('lastmodified', models.DateTimeField(db_index=True, default=django.utils.timezone.now, editable=False, verbose_name='Последнее обновление')),
                ('value_str', models.TextField(blank=True, db_index=True, null=True, verbose_name='Значение атрибута')),
                ('value_int', models.BigIntegerField(blank=True, db_index=True, null=True, verbose_name='Значение атрибута')),
                ('attr_type', isc_common.fields.related.ForeignKeyProtect(on_delete=django.db.models.deletion.PROTECT, to='ckk.Attr_type', verbose_name='Тип атрибута')),
                ('document', isc_common.fields.related.ForeignKeyProtect(on_delete=django.db.models.deletion.PROTECT, to='kd.Lotsman_documents')),
            ],
            options={
                'verbose_name': 'Аттрибуты документов из Лоцмана',
            },
        ),
    ]
