# Generated by Django 2.2.8 on 2019-12-13 13:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kd', '0093_auto_20191213_1322'),
    ]

    operations = [
    ]
