# Generated by Django 2.2.8 on 2019-12-15 01:05

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import isc_common.fields.related


class Migration(migrations.Migration):

    dependencies = [
        ('kd', '0107_auto_20191215_0101'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lotsman_documents_hierarcy',
            name='parent',
        ),
        migrations.AlterField(
            model_name='lotsman_documents_hierarcy',
            name='id',
            field=models.BigAutoField(primary_key=True, serialize=False, verbose_name='Идентификатор'),
        ),
        migrations.CreateModel(
            name='Lotsman_documents_hierarcy_refs',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False, verbose_name='Идентификатор')),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='Дата мягкого удаления')),
                ('editing', models.BooleanField(default=True, verbose_name='Возможность редактирования')),
                ('deliting', models.BooleanField(default=True, verbose_name='Возможность удаления')),
                ('lastmodified', models.DateTimeField(db_index=True, default=django.utils.timezone.now, editable=False, verbose_name='Последнее обновление')),
                ('child', isc_common.fields.related.ForeignKeyCascade(on_delete=django.db.models.deletion.CASCADE, related_name='Lotsman_documents_hierarcy_child', to='kd.Lotsman_documents_hierarcy')),
                ('parent', isc_common.fields.related.ForeignKeyCascade(on_delete=django.db.models.deletion.CASCADE, related_name='Lotsman_documents_hierarcy_parent', to='kd.Lotsman_documents_hierarcy')),
            ],
            options={
                'verbose_name': 'Кросс таблица',
            },
        ),
    ]
