# Generated by Django 2.2.8 on 2019-12-16 21:12

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import isc_common.fields.related


class Migration(migrations.Migration):

    dependencies = [
        ('kd', '0115_lotsman_documents_hierarcy_props'),
    ]

    operations = [
        migrations.CreateModel(
            name='Lotsman_documents_hierarcy_files',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False, verbose_name='Идентификатор')),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='Дата мягкого удаления')),
                ('editing', models.BooleanField(default=True, verbose_name='Возможность редактирования')),
                ('deliting', models.BooleanField(default=True, verbose_name='Возможность удаления')),
                ('lastmodified', models.DateTimeField(db_index=True, default=django.utils.timezone.now, editable=False, verbose_name='Последнее обновление')),
                ('path', models.TextField()),
                ('lotsman_document', isc_common.fields.related.ForeignKeyProtect(on_delete=django.db.models.deletion.PROTECT, to='kd.Lotsman_documents_hierarcy')),
            ],
            options={
                'verbose_name': 'Файлы обрабатанные для данной позиции',
            },
        ),
    ]
