# Generated by Django 2.2.8 on 2019-12-18 16:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kd', '0121_auto_20191218_1642'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lotsman_document_attr_cross',
            name='position_in_document',
        ),
    ]
