# Generated by Django 3.1.4 on 2020-12-11 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kd', '0154_uploades_view'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documents',
            name='file_document',
            field=models.TextField(blank=True, db_index=True, null=True, verbose_name='Полный путь к файлу'),
        ),
        migrations.AlterField(
            model_name='documents',
            name='file_size',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Размер файла'),
        ),
    ]
