from pyarma import *

c = cube(5,5,5,fill_randu)
c.print()
c.save("cube.bin")
c.save("cube.txt", arma_ascii)
c.save("cube.rbin", raw_binary)
c.save("rmatrix.txt", raw_ascii)
c.save("cube.csv", csv_ascii)
c.save("cube.pgm", pgm_binary)
# c.save("cube.hdf5", hdf5_binary)
d = cube()
d.load("cube.bin")
d.print()
#print(c==d)
d.load("cube.txt", arma_ascii)
d.print()
#print(c==d)
d.load("cube.rbin", raw_binary)
d.reshape(5,5,5)
d.print()
#print(c==d)
d.load("rmatrix.txt", raw_ascii)
d.print()
#print(c==d)
d.load("cube.csv", csv_ascii)
d.print()
#print(c==d)
d.load("cube.pgm", pgm_binary)
d.print()
#print(c==d)
# d.load("cube.hdf5", hdf5_binary)
# d.print()
#print(c==d)
