from pyarma import *

m = mat(5,5,fill_randu)
m.print()
m.save("matrix.bin")
m.save("matrix.txt", arma_ascii)
m.save("matrix.rbin", raw_binary)
m.save("rmatrix.txt", raw_ascii)
m.save("matrix.csv", csv_ascii)
m.save("matrix.pgm", pgm_binary)
m.save("matrix.hdf5", hdf5_binary)
n = mat()
n.load("matrix.bin")
n.print()
print(m==n)
n.load("matrix.txt", arma_ascii)
n.print()
print(m==n)
n.load("matrix.rbin", raw_binary)
n.reshape(5,5)
n.print()
print(m==n)
n.load("rmatrix.txt", raw_ascii)
n.print()
print(m==n)
n.load("matrix.csv", csv_ascii)
n.print()
print(m==n)
n.load("matrix.pgm", pgm_binary)
n.print()
print(m==n)
n.load("matrix.hdf5", hdf5_binary)
n.print()
print(m==n)
