uri_formats = {  # prefixes to use for different uris
    'doi': 'info:doi',
    'isbn': 'urn:isbn',
    'issn': 'urn:issn',
    'isan': 'urn:isan',
    'uuid': 'urn:uuid',
    'iso': 'urn:iso',
    'nbn': 'urn:nbn',
    'hgl': 'info:hdl',
}   # excludes http-like and publisher-specific URIs

work_types = (  # All work types in the Identifier Translation Service DB
    'book-section',
    'monograph',
    'report',
    'book-track',
    'journal-article',
    'book-part',
    'other',
    'book',
    'journal-volume',
    'book-set',
    'reference-entry',
    'proceedings-article',
    'journal',
    'component',
    'book-chapter',
    'report-series',
    'proceedings',
    'standard',
    'reference-book',
    'posted-content',
    'journal-issue',
    'dissertation',
    'dataset',
    'book-series',
    'edited-book',
    'standard-series',
    'peer-review',
    'proceedings-series',
)

