
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2021-02-04T21:54:11+0100",
 "dirty": false,
 "error": null,
 "full-revisionid": "3f452daad62926209d4d14b8e6702b75bceeb0ea",
 "version": "1.0.19"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
