
# This file was generated by 'versioneer.py' (0.19) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2021-02-02T00:05:09-0500",
 "dirty": false,
 "error": null,
 "full-revisionid": "9ba4f44b0a6b456737b3407c8d35545de22cfb32",
 "version": "3.0.1"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
