
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2021-02-01T10:14:57+0200",
 "dirty": false,
 "error": null,
 "full-revisionid": "e0c8534b1b1999639ed7d59b4548dc6199011c97",
 "version": "5.32.1"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
