
# This file was generated by 'versioneer.py' (0.19) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2021-02-01T04:00:59-0800",
 "dirty": false,
 "error": null,
 "full-revisionid": "135183a8d2ed7c7f41c0a483aaf58080af15da81",
 "version": "4.3.30"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
