# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from spaceone.api.report.v1 import report_pb2 as spaceone_dot_api_dot_report_dot_v1_dot_report__pb2


class ReportStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.get = channel.unary_unary(
                '/spaceone.api.report.v1.Report/get',
                request_serializer=spaceone_dot_api_dot_report_dot_v1_dot_report__pb2.GetReportRequest.SerializeToString,
                response_deserializer=spaceone_dot_api_dot_report_dot_v1_dot_report__pb2.ReportInfo.FromString,
                )
        self.get_download_url = channel.unary_unary(
                '/spaceone.api.report.v1.Report/get_download_url',
                request_serializer=spaceone_dot_api_dot_report_dot_v1_dot_report__pb2.GetDownloadURLRequest.SerializeToString,
                response_deserializer=spaceone_dot_api_dot_report_dot_v1_dot_report__pb2.ReportDownloadInfo.FromString,
                )
        self.list = channel.unary_unary(
                '/spaceone.api.report.v1.Report/list',
                request_serializer=spaceone_dot_api_dot_report_dot_v1_dot_report__pb2.ReportQuery.SerializeToString,
                response_deserializer=spaceone_dot_api_dot_report_dot_v1_dot_report__pb2.ReportsInfo.FromString,
                )
        self.create = channel.unary_unary(
                '/spaceone.api.report.v1.Report/create',
                request_serializer=spaceone_dot_api_dot_report_dot_v1_dot_report__pb2.CreateReportRequest.SerializeToString,
                response_deserializer=spaceone_dot_api_dot_report_dot_v1_dot_report__pb2.ReportInfo.FromString,
                )


class ReportServicer(object):
    """Missing associated documentation comment in .proto file."""

    def get(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def get_download_url(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def list(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def create(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_ReportServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'get': grpc.unary_unary_rpc_method_handler(
                    servicer.get,
                    request_deserializer=spaceone_dot_api_dot_report_dot_v1_dot_report__pb2.GetReportRequest.FromString,
                    response_serializer=spaceone_dot_api_dot_report_dot_v1_dot_report__pb2.ReportInfo.SerializeToString,
            ),
            'get_download_url': grpc.unary_unary_rpc_method_handler(
                    servicer.get_download_url,
                    request_deserializer=spaceone_dot_api_dot_report_dot_v1_dot_report__pb2.GetDownloadURLRequest.FromString,
                    response_serializer=spaceone_dot_api_dot_report_dot_v1_dot_report__pb2.ReportDownloadInfo.SerializeToString,
            ),
            'list': grpc.unary_unary_rpc_method_handler(
                    servicer.list,
                    request_deserializer=spaceone_dot_api_dot_report_dot_v1_dot_report__pb2.ReportQuery.FromString,
                    response_serializer=spaceone_dot_api_dot_report_dot_v1_dot_report__pb2.ReportsInfo.SerializeToString,
            ),
            'create': grpc.unary_unary_rpc_method_handler(
                    servicer.create,
                    request_deserializer=spaceone_dot_api_dot_report_dot_v1_dot_report__pb2.CreateReportRequest.FromString,
                    response_serializer=spaceone_dot_api_dot_report_dot_v1_dot_report__pb2.ReportInfo.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'spaceone.api.report.v1.Report', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class Report(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def get(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/spaceone.api.report.v1.Report/get',
            spaceone_dot_api_dot_report_dot_v1_dot_report__pb2.GetReportRequest.SerializeToString,
            spaceone_dot_api_dot_report_dot_v1_dot_report__pb2.ReportInfo.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def get_download_url(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/spaceone.api.report.v1.Report/get_download_url',
            spaceone_dot_api_dot_report_dot_v1_dot_report__pb2.GetDownloadURLRequest.SerializeToString,
            spaceone_dot_api_dot_report_dot_v1_dot_report__pb2.ReportDownloadInfo.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def list(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/spaceone.api.report.v1.Report/list',
            spaceone_dot_api_dot_report_dot_v1_dot_report__pb2.ReportQuery.SerializeToString,
            spaceone_dot_api_dot_report_dot_v1_dot_report__pb2.ReportsInfo.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def create(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/spaceone.api.report.v1.Report/create',
            spaceone_dot_api_dot_report_dot_v1_dot_report__pb2.CreateReportRequest.SerializeToString,
            spaceone_dot_api_dot_report_dot_v1_dot_report__pb2.ReportInfo.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
