# Generated by Django 2.0.8 on 2018-09-11 08:31

import imicusfat.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("imicusfat", "0002_manualfat"),
    ]

    operations = [
        migrations.CreateModel(
            name="DelLog",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("deltype", models.BooleanField(default=0)),
                ("string", models.CharField(max_length=100)),
                (
                    "remover",
                    models.ForeignKey(
                        on_delete=models.SET(imicusfat.models.get_sentinel_user),
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.AlterModelOptions(
            name="ifatlink",
            options={
                "permissions": (
                    ("manage_imicusfat", "Can manage the imicusfat module"),
                    ("stats_corp_own", "Can see own corp stats"),
                    ("stats_corp_other", "Can see stats of other corps."),
                    (
                        "stats_char_other",
                        "Can see stats of characters not associated with current user.",
                    ),
                )
            },
        ),
        migrations.RemoveField(
            model_name="ifat",
            name="station",
        ),
        migrations.RemoveField(
            model_name="ifat",
            name="user",
        ),
        migrations.AlterField(
            model_name="ifat",
            name="shiptype",
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="ifat",
            name="system",
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="ifatlink",
            name="fleet",
            field=models.CharField(max_length=254, null=True),
        ),
    ]
