# Generated by Django 2.2.14 on 2020-08-16 20:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("imicusfat", "0004_clickfatduration"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="ifatlink",
            options={
                "ordering": ("-ifattime",),
                "permissions": (
                    ("manage_imicusfat", "Can manage the imicusfat module"),
                    ("stats_corp_own", "Can see own corp stats"),
                    ("stats_corp_other", "Can see stats of other corps."),
                    (
                        "stats_char_other",
                        "Can see stats of characters not associated with current user.",
                    ),
                ),
            },
        ),
        migrations.AddField(
            model_name="ifat",
            name="deleted_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="ifatlink",
            name="deleted_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
