# Generated by Django 3.1.1 on 2020-09-25 23:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("imicusfat", "0008_auto_20200912_1121"),
    ]

    operations = [
        migrations.AddField(
            model_name="ifatlink",
            name="is_esilink",
            field=models.BooleanField(default=False),
        ),
    ]
