# Generated by Django 3.1.2 on 2020-10-19 16:49

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("imicusfat", "0012_basic_module_access_permissions"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="DelLog",
            new_name="IFatDelLog",
        ),
    ]
