# Generated by Django 2.2.1 on 2019-05-19 01:15

from django.db import migrations
import django.db.models.deletion
import isc_common.fields.related


class Migration(migrations.Migration):

    dependencies = [
        ('ckk', '0045_auto_20190517_2112'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item_refs',
            name='child',
            field=isc_common.fields.related.ForeignKeyCascade(on_delete=django.db.models.deletion.CASCADE, related_name='child', to='ckk.Item'),
        ),
    ]
