# Generated by Django 2.2.2 on 2019-06-10 20:18

import bitfield.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ckk', '0089_auto_20190610_1832'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='props1',
            field=bitfield.models.BitField((('from_cdw', 'Получено из чертежа'), ('from_spw', 'Получено из спецификации'), ('for_line', 'Строка спецификации'), ('from_pdf', 'Получено из бумажного архива')), db_index=True, default=1),
        ),
        migrations.AlterField(
            model_name='item',
            name='props',
            field=bitfield.models.BitField((('relevant', 'Актуальность'),), db_index=True, default=1),
        ),
    ]
