# Generated by Django 2.2.4 on 2019-08-19 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ckk', '0141_material_askon'),
    ]

    operations = [
        migrations.AlterField(
            model_name='Material_askon',
            name='field0',
            field=models.CharField(db_index=True, max_length=255, unique=True, verbose_name='Информация в дерево материалов'),
        ),
    ]
