# Generated by Django 3.0.3 on 2020-02-09 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ckk', '0205_auto_20200208_1609'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='materials',
            constraint=models.UniqueConstraint(condition=models.Q(nomenklatura_model=None), fields=('gost', 'location', 'materials_type'), name='Materials_unique_constraint_0'),
        ),
        migrations.AddConstraint(
            model_name='materials',
            constraint=models.UniqueConstraint(fields=('gost', 'location', 'materials_type', 'nomenklatura_model'), name='Materials_unique_constraint_1'),
        ),
    ]
