# Generated by Django 3.0.8 on 2020-07-21 08:19

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('ckk', '0240_standard_colors_view'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Standard_colors_view',
        ),
    ]
