# Generated by Django 3.0.8 on 2020-08-03 06:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ckk', '0243_auto_20200801_0711'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Tmp_Item_operations_view',
        ),
        migrations.DeleteModel(
            name='Tmp_Item_refs',
        ),
        migrations.DeleteModel(
            name='Tmp_Item_view',
        ),
    ]
