# Generated by Django 3.1.2 on 2020-10-07 14:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ckk', '0252_auto_20201007_1457'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='item_varians',
            unique_together={('item', 'child', 'parent', 'refs_props')},
        ),
    ]
