# Generated by Django 3.1.2 on 2020-10-14 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ckk', '0254_auto_20201008_1404'),
    ]

    operations = [
        migrations.AddField(
            model_name='locations',
            name='level_grouping',
            field=models.SmallIntegerField(default=0),
        ),
    ]
