# Generated by Django 3.1.2 on 2020-10-14 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ckk', '0255_locations_level_grouping'),
    ]

    operations = [
        migrations.AlterField(
            model_name='locations',
            name='level_grouping',
            field=models.SmallIntegerField(blank=True, null=True),
        ),
    ]
