# Generated by Django 3.1.2 on 2020-10-31 17:41

from django.db import migrations
import django.db.models.deletion
import isc_common.fields.related


class Migration(migrations.Migration):

    dependencies = [
        ('planing', '0256_auto_20201031_0557'),
        ('ckk', '0261_auto_20201031_0546'),
    ]

    operations = [
        migrations.AddField(
            model_name='item_refs_location',
            name='child_operation',
            field=isc_common.fields.related.ForeignKeyProtect(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='Item_refs_location_child_operation', to='planing.operations'),
        ),
        migrations.AddField(
            model_name='item_refs_location',
            name='parent_operation',
            field=isc_common.fields.related.ForeignKeyProtect(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='Item_refs_location_parent_operation', to='planing.operations'),
        ),
    ]
