# Generated by Django 3.1.2 on 2020-11-01 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ckk', '0264_auto_20201101_0940'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item_refs_location',
            name='child_operation',
        ),
        migrations.RemoveField(
            model_name='item_refs_location',
            name='parent_operation',
        ),
        migrations.AddField(
            model_name='item_refs_location',
            name='child_operation_id',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='item_refs_location',
            name='parent_operation_id',
            field=models.BigIntegerField(blank=True, null=True),
        ),
    ]
