# Generated by Django 3.1.3 on 2020-11-02 15:51

import bitfield.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ckk', '0265_auto_20201101_1206'),
    ]

    operations = [
        migrations.AddField(
            model_name='item_refs_location',
            name='props',
            field=bitfield.models.BitField((('used', 'Используемость в группировке заданий на производство'),), db_index=True, default=1),
        ),
    ]
