# Generated by Django 3.1.3 on 2020-11-09 09:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ckk', '0268_auto_20201109_0914'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Item_refs_hierarcy',
        ),
    ]
