# Generated by Django 3.1.3 on 2020-11-13 08:46

import bitfield.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ckk', '0269_delete_item_refs_hierarcy'),
    ]

    operations = [
        migrations.AlterField(
            model_name='locations',
            name='props',
            field=bitfield.models.BitField((('isWorkshop', 'Уровень цеха'), ('grouping_production_orders', 'Группировать задания на производство')), db_index=True, default=0),
        ),
    ]
