# Generated by Django 3.1.4 on 2020-12-18 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ckk', '0278_auto_20201218_1217'),
    ]

    operations = [
        migrations.AlterField(
            model_name='locations',
            name='fullname',
            field=models.TextField(),
        ),
    ]
