
# This file was generated by 'versioneer.py' (0.19) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2021-02-04T12:12:34+0100",
 "dirty": false,
 "error": null,
 "full-revisionid": "da0b46fe4e0737e5e08db2412225638dbe364240",
 "version": "1.1.7"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
