
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2021-01-30T11:39:24+0100",
 "dirty": false,
 "error": null,
 "full-revisionid": "72a1c4772a6ed65f79862d233e97f8ef01dc407c",
 "version": "0.26.0"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
