# Generated by Django 2.2.8 on 2019-12-14 21:30

from django.db import migrations
import django.db.models.deletion
import isc_common.fields.related


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0003_contants'),
    ]

    operations = [
        migrations.AddField(
            model_name='contants',
            name='parent',
            field=isc_common.fields.related.ForeignKeyProtect(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='system.Contants'),
        ),
    ]
